### ISSUE TITLE
searching for help and documentation in the QGIS site - search tool bug (any lowercase and uppercase distinction) ?

### ISSUE THREAD

**Issue by pboulerie** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#100]
Re : searching for help and documentation in the QGIS site - search tool bug (any lowercase and uppercase distinction) ?

Hello,

I can not find pages in the QGIS site - http://qgis.org/en/site/ - using the keyword PostGIS...

But if I do type : Postgis , I do find the documentation page about PostGIS...

PS Please note that users are more familiar with the writing « PostGIS » than « Postgis » or « postgis ».

Maybe the search engine or the search index has to be fixed ?

http://qgis.org/en/search.html?q=PostGIS

Search

From here you can search these documents. Enter your search words into the box below and click "search". Note that the search function will automatically search for all of the words. Pages containing fewer words won't appear in the result list.

Search Results

Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories.

http://qgis.org/en/search.html?q=Postgis
Search finished, found 1 page(s) matching the search query.

...rt is supplied by native QGIS data provider plugins), including ESRI Shapefiles, MapInfo and Microstation file formats; PostGIS, SpatiaLite, Oracle Spatial databases and many more. The vector data can also be loaded in read mode from zip an...

**Comment by rduivenvoorde** [comment]
mmm, we actually just use the default Sphinx searching stuff.

But I agree that this is not working correctly.

But it is easy to just make lowercase the full search string just before posting it...

Will look into this

**Comment by pboulerie** [comment]
> it should be easy to convert automatically to lowercase the search string just before posting it to the search engine

Thanks for the idea of the workaround.

By the way, I have also looked in the Sphinx website - http://sphinx-doc.org – to see that this is a known bug issue in the Sphinx issues at BitBucket :
https://bitbucket.org/birkenfeld/sphinx/issue/1072/search-result-was-not-shown-when-i-search

(I found a link from http://sphinx-doc.org/develop.html in the section « Issues and feature requests should be raised in the tracker. » to that other website. Previously, I had found the Sphinx website from the link given at qgis.org/en/docs/documentation_guidelines/README.html )

**Comment by DelazJ** [comment]
Still valid issue. Might be nice to have it fixed if the fix is really easy.

**Comment by DelazJ** [comment]
Also fixed: the search is case insensitive now
