### ISSUE TITLE
Broken search tool

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1004]
## Description
The website search tool does not return results; loops forever. I've tried on many devices/browsers, and it is something that has been reported to me weeks ago.

Try https://qgis.org/en/search.html?q=Qgis&check_keywords=yes&area=default

Page URL:

**Comment by nicogodet** [comment]
This is supposed to fix the search tool : https://github.com/sphinx-doc/sphinx/commit/f5289bb69993d2b1f83a509f56e418fcd5d00b87#diff-6d2685a488d0f2d01f8d2001804fe55e6882806c236f248141a2a04b5eabed4dR15

But when I try locally I have a lot of errors in web console but I'm not sure this is related as a lot of things depends on server_name (aka qgis.org)

I can push the fix which is ready (https://github.com/nicogodet/QGIS-Website/tree/fix-search) but I don't know how to test it properly...

**Comment by nicogodet** [comment]
![image](https://user-images.githubusercontent.com/39594821/186155901-26f8ecac-dfc8-498f-ad92-b4c11d254e5b.png)
![image](https://user-images.githubusercontent.com/39594821/186156088-9df425f7-a259-4807-8ce1-5eb3115e9583.png)
