### ISSUE TITLE
Google Authorization 400 Error

### ISSUE THREAD

**Issue by mrpaulhoward** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1005]
## Description

Every time open Qgis and open up a map I have worked on previously, google opens up and tells me there is an Authorization error. Also when I try to add a symbol point using a Deliminated Text Layer from an csv file, Qgis crashes and closes. Can someone assist please? 

Page URL:

**Comment by DelazJ** [comment]
@mrpaulhoward this repository is for QGIS main website management. For help request, please consider using the qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)), where you should provide more details (QGIS version, google error message, maybe crash report and project file).
In the meantime you can try running QGIS under a [new user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
Closing...
