### ISSUE TITLE
Bitdefender reports virus

### ISSUE THREAD

**Issue by fscgeus** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1009]
## Description
Dear QGIS 
I get following Antivirus Bitdefender report of malware in the downloaded QGIS 3.26.0 by OSGEO4W

Kind Regards,
Frands Schjøth

Page URL:
![Snag_ebec7](https://user-images.githubusercontent.com/19833496/177093505-aa42cc82-45c3-49fd-b0b2-b970a5f8d479.png)

**Comment by jef-n** [comment]
Not a website issue - furthermore setup.log.* is a plain text logfile.
