### ISSUE TITLE
[feature request] Automatic redirections from language code subdirectories URLs ?

### ISSUE THREAD

**Issue by pboulerie** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#101]
Re : [feature request] Automatic redirections from language code subdirectories URLs ?

There are no automatic index redirections for these URLs to the website ./site :
http://qgis.org/en/
http://qgis.org/fr/

**Comment by rduivenvoorde** [comment]
related to #33

**Comment by rduivenvoorde** [comment]
just added those for the docs sites:

http://docs.qgis.org/ru
http://docs.qgis.org/2.0/nl
etc

**Comment by rduivenvoorde** [comment]
now also for 

http://www.qgis.org/de
http://qgis.org/ru
etc

plz test and reopen if not ok
