### ISSUE TITLE
"Message for new versions points to download.qgis.org, which is not very convenient"

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1012]
## Description

See https://github.com/qgis/QGIS/issues/49446.

https://github.com/qgis/QGIS/issues/49446#issuecomment-1192388891
> It seems to me https://download.qgis.org/ used to be redirected to https://qgis.org/en/site/forusers/download.html or https://download.qgis.org/en/site/ (not existing now) at least until last April, but now it results redirected to https://download.qgis.org/downloads/.

**Comment by rduivenvoorde** [comment]
@jef-n the redirect for download.qgis.org is on qgis2 (old webserver).

Do you agree that it is better to redirect that to the (language) download page in qgis.org, like https://qgis.org/en/site/forusers/download.html?

Not sure if we are able to redirect to the right language though...

Or should we try to make a nice human url on qgis.org so qgis.org/download (not qgis.org/downloads is already used)?
