### ISSUE TITLE
searching in the help and documentation - highlighting a word in a search result on the website QGIS.org ?

### ISSUE THREAD

**Issue by pboulerie** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#102]
Re : searching in the help and documentation - highlighting a word in a search result on the website QGIS.org ?

The highlighting feature :
http://qgis.org/en/docs/user_manual/working_with_vector/supported_data.html?highlight=PostGIS
does not highlight the word in the page...

Using : Mozilla FireFox 23.0.1

**Comment by rduivenvoorde** [comment]
hi, can you provide some more info?

Is this supposed to be some default Sphinx functionality? If so can you point to an example? I do not see some added classes or markup?

Or is it  a feature request, to be added via javascript or so?

**Comment by DelazJ** [comment]
I think that I have the steps (I'm on Firefox):
1. From any page of the documentation, make a search in the search bar. let's use 'PostGIS'
2. You should got this page http://docs.qgis.org/testing/en/search.html?q=postgis&check_keywords=yes&area=default where the expression 'PostGIS' is highlighted in the results
3. Click now on any of the result, opening the page in the browser
4. The term PostGIS is supposed to be highlighted (given the url containing `highlight=PostGIS`) but actually, no highlight is in the page: you have to make a search within the page to find its occurrences.

**Comment by DelazJ** [comment]
This seems fixed now: searched word is highlighted when you open the result page.
