### ISSUE TITLE
Website doesn't match source code

### ISSUE THREAD

**Issue by Charles-Kaminski** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1020]
## Description
The repo doesn't match the website.  

The install instructions on the website are incorrect and do not work on Ubuntu because of a minor issue with the file name of the gpg key that needs to be downloaded.  I was going to propose a code change to your website, but the code change is already in your repo.  

What your website says to do:
wget -qO - https://qgis.org/downloads/qgis-2021.gpg.key | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import

The key file is incorrect and should reflect 2022. 

Page URL: https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

**Comment by DelazJ** [comment]
Fixed in https://github.com/qgis/QGIS-Website/commit/81ed014e69eb1e6eae272b6bdafc5649220c6732 Will be available after next build
