### ISSUE TITLE
Flatpak: instructions lead to install QGIS LTR instead of Stable

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1022]
## Description

Page URL: https://qgis.org/en/site/forusers/alldownloads.html#flatpak

In the Flatpak section:

> There is an QGIS flatpak for **QGIS Stable** available, maintained by the flathub community.
> 
> [...]
> 
> To install:
> 
> `flatpak install --from  https://flathub.org/repo/appstream/org.qgis.qgis.flatpakref`

Anyway `flatpak install --from  https://flathub.org/repo/appstream/org.qgis.qgis.flatpakref` install QGIS LTR instead of QGIS Stable.

**Comment by rduivenvoorde** [comment]
@agiudiceandrea I just tested, with me I got 3.26 (= latest, not LTR)?

Maybe flatpak community names stuff 'stable' not sure how that is defined.

The flatpakref file also names it 'stable':

```
[Flatpak Ref]
Name=org.qgis.qgis
Branch=stable  <= STABLE !?
Title=org.qgis.qgis from flathub
IsRuntime=false
Url=https://dl.flathub.org/repo/
SuggestRemoteName=flathub
```

We could change the site to tell: "There is an QGIS flatpak for QGIS Latest available", that is easy.

I do not think it is wise to let flatpak package LTR? 
My guess is that flatpak users want the newest stuff (@aleixpol what you think? Best to stick to (what in the QGIS community is named) 'latest')?

**Comment by agiudiceandrea** [comment]
@rduivenvoorde, really strange!
On Ubuntu 22.04 `flatpak install --from https://flathub.org/repo/appstream/org.qgis.qgis.flatpakref` installs QGIS LTR 3.22.8 and 
https://flathub.org/repo/appstream/org.qgis.qgis.flatpakref contains:
```
[Flatpak Ref]
Name=org.qgis.qgis
Branch=lts
Title=org.qgis.qgis from flathub
IsRuntime=false
Url=https://dl.flathub.org/repo/
SuggestRemoteName=flathub
GPGKey=[truncated]
```

**Comment by rduivenvoorde** [comment]
Huh??? I'm on Debian Testing, and even clicking your url now (so retrieving with browser en opening with gedit), shows me:

```
[Flatpak Ref]
Name=org.qgis.qgis
Branch=stable
Title=org.qgis.qgis from flathub
IsRuntime=false
Url=https://dl.flathub.org/repo/
SuggestRemoteName=flathub
GPGKey=mQINBFlD2sABEADsiUZ...(truncated)
RuntimeRepo=https://dl.flathub.org/repo/flathub.flatpakrepo
```

or (you need -L to follow redirect)

```
$ curl -L https://flathub.org/repo/appstream/org.qgis.qgis.flatpakref
[Flatpak Ref]
Name=org.qgis.qgis
Branch=stable
Title=org.qgis.qgis from flathub
IsRuntime=false
Url=https://dl.flathub.org/repo/
SuggestRemoteName=flathub
GPGKey=mQINBFlD2sABEADsiU...
```

**Comment by agiudiceandrea** [comment]
~~OK, it seems it was a caching issue with my ISP... Just changing my dynamic IP fixes the issue and now the stable branch is installed.~~
It continues to be inconsistently containing "Branch=lts" when retrieved from https://flathub.org/repo/appstream/org.qgis.qgis.flatpakref ...

**Comment by agiudiceandrea** [comment]
@rduivenvoorde, doing some tests on different systems/machines (Windows 7/10 and Ubuntu), it seems to me the Flatpak Ref file retrieved using https://flathub.org/repo/appstream/org.qgis.qgis.flatpakref inconsistently contains "Branch=lts" or "Branch=stable" while the one retrieved using https://dl.flathub.org/repo/appstream/org.qgis.qgis.flatpakref always contains "Branch=stable".
Anyway, I think it's better to avoid any redirection, so I've submitted a PR to change such URL https://github.com/qgis/QGIS-Website/pull/1023.
