### ISSUE TITLE
Broken download link - QGIS-OSGeo4W-3.26.2-2.msi

### ISSUE THREAD

**Issue by robbitt** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1024]
## Description

I tried to download QGIS Standalone Installer Version 3.26 for Windows, but it resulted in a 404 Not Found error.
Page URL: https://download.osgeo.org/qgis/windows/QGIS-OSGeo4W-3.26.2-2.msi

**Comment by agiudiceandrea** [comment]
In the meantime, the correct links are:

3.22.10: https://qgis.org/downloads/QGIS-OSGeo4W-3.22.10-1.msi | https://qgis.org/downloads/QGIS-OSGeo4W-3.22.10-1.sha256sum

3.26.2: https://qgis.org/downloads/QGIS-OSGeo4W-3.26.2-1.msi | https://qgis.org/downloads/QGIS-OSGeo4W-3.26.2-1.sha256sum
