### ISSUE TITLE
Broken download links for plugins (using plugin manager within QGIS)

### ISSUE THREAD

**Issue by ESEMSE** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1026]
Not sure whether this is right place for this issue, so you may want to categorise as an issue with the application.

Attempting to install plugins from within QGIS fails.

Error: Plugin installation failed: Error transferring https://plugins.qgis.org/plugins/closest_points/version/1.0.1/download/ - server replied: Gateway Timeout

Page URL: https://plugins.qgis.org/plugins/NNJoin/version/3.1.3/download/

**Comment by nicogodet** [comment]
Already reported on correct repo : https://github.com/qgis/QGIS-Django/issues/248
