### ISSUE TITLE
Latest macOS Builds Not Available

### ISSUE THREAD

**Issue by davidafuller01** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1029]
## Description
Download page not yet populated with QGIS 3.26.2 'Buenos Aires' and QGIS 3.22.10 'Białowieża' which were released on 12.08.2022.

Page URL: https://download.qgis.org/downloads/macos/

**Comment by davidafuller01** [comment]
Anyone able to repair this? The new version was released 10 days ago and still not available for download.
<img width="1214" alt="Screen Shot 2022-08-22 at 07 32 15" src="https://user-images.githubusercontent.com/2762809/185933449-3a22f6b7-cd80-483f-a3d8-f013d7a6aaf4.png">

**Comment by davidafuller01** [comment]
@DelazJ  - Looks like the qgis-macos-ltr.dmg build is now working, but qgis-macos-pr.dmg is not yet updated.

**Comment by nicogodet** [comment]
@davidafuller01 https://github.com/qgis/QGIS-Mac-Packager/issues/154#issuecomment-1224226682

**Comment by agiudiceandrea** [comment]
This is fixed now.
