### ISSUE TITLE
update po strings in html templates are not sent automatically to transifex ?

### ISSUE THREAD

**Issue by haubourg** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1032]
Hi @rduivenvoorde 

I'm digging into a translation issue that appeared 24 days ago with this commit, adding iOS to the list of supported OS's : bd28eec5a4997f33aa5114320e0c384e751a20af in `themes/qgis-theme/forusers_download.html` file.

From what I understand building locally the website, the po strings in html template files are not pushed automatically to transifex, and they are all into one `sphinx.po` file. I may however have missed something.

I have a branch ready to this particular issue by manually changing the po file, but I would like to know if we can improve things to automatically add those po strings to transifex pull process, or at least document how to do it. 
I'm available to work on this during the hackfest. Do you have some pointers or caveat informations to help making this happen?

My branch :  https://github.com/qgis/QGIS-Website/compare/master...haubourg:QGIS-Website:fix_po_html_templates?expand=1

Cheers!

cc @PeterPetrik https://github.com/qgis/QGIS-Website/pull/1013 originated some translations inconsistencies ( no blaming, just trying to keep info clean)

**Comment by DelazJ** [comment]
@haubourg I think #1033 is looking into automating the process

**Comment by rduivenvoorde** [comment]
@haubourg you are right, there were/are no automatic pushes or automation

All rst files have their own resource, but (because we wanted more fancy loading pages some year ago), the landingpages are not rst but html(templates), and indeed via some trick those strings all end up in sphinx.po

and @m-kuhn is busy now to automate some stuff

**Comment by haubourg** [comment]
> and @m-kuhn is busy now to automate some stuff

yep, we 've been chatting and https://github.com/qgis/QGIS-Website/pull/1033 seems to fix this nicely. 
Now the only issue is a UX matter in transifex, since "sphinx.po" ressource is not that explicit, and translators might have trouble finding the strings in it. But I don't think we can change sphinx behavior, that's a minor issue.
