### ISSUE TITLE
german changelog states wrong version for 3.26

### ISSUE THREAD

**Issue by wiesehahn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1038]
## Description

Not sure if this is the right plaxe to mention it, but the German website for the changelog of 3.26 states it is version 3.16.

Page URL:
https://www.qgis.org/de/site/forusers/visualchangelog326/index.html

**Comment by rduivenvoorde** [comment]
Thanks, fixed. 

https://www.transifex.com/qgis/qgis-website/translate/#de/site_forusers_visualchangelog326_index/428971939

small translation error, will be viewable tomorrow after next rebuild of the site
