### ISSUE TITLE
ubuntu download sections mixed up

### ISSUE THREAD

**Issue by jef-n** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#104]
http://www.qgis.org/en/site/forusers/alldownloads.html#ubuntu is wrong.  It merges 2.6.1 and 2.6.2 from http://hub.qgis.org/wiki/quantum-gis/Download#26-Ubuntu, which it shouldn't.

2.6.1 describes how to get qgis from our repository for ubuntu (i.e. w/o anything from ubuntugis) and 2.6.2 describes how to get qgis from ubuntugis (i.e. w/o anything from our repository) - mixing the two will create a mess.

For the ubuntugis nightlies it's different.  We have newer qgis versions in our repository, so mixing will fetch the nightly qgis from our repository and dependencies from ubuntugis.

**Comment by jef-n** [comment]
See also http://lists.osgeo.org/pipermail/qgis-developer/2013-September/028657.html and http://lists.osgeo.org/pipermail/qgis-developer/2013-September/028644.html

**Comment by rduivenvoorde** [comment]
I cleaned/merged/restructured both download pages, see

http://www.qgis.org/en/site/forusers/download.html
and
http://www.qgis.org/en/site/forusers/alldownloads.html

please check if ubuntu sections are now right and clear enough

**Comment by jef-n** [comment]
The keys are outdated.    the current key is 47765B75.  997D3880 is expired.

And the available distributions have changed:

Debian:
2.0.1: wheezy, jessie and unstable
nightly: wheezy, jessie and unstable

Ubuntu:
2.0.1: lucid, precise, quantal, raring and saucy
nightly plain: lucid, precise, quantal, raring and saucy
nightly ubuntugis: lucid, precise, quantal and raring

**Comment by rduivenvoorde** [comment]
ok, changed this in 00a8a5bbbdfa51f0119f23941e4536a66c6758bb

should be available now on http://www.qgis.org/en/site/forusers/alldownloads.html

about QGIS 2.0 (QGIS Stable) via ubuntugis: 

http://www.qgis.org/en/site/forusers/alldownloads.html#via-ubuntugis

We say "Current packages available for lucid, maverick, natty, oneiric, precise and raring."

But looking here:

https://launchpad.net/~ubuntugis/+archive/ubuntugis-unstable/+index?batch=75&memo=150&start=150

I see lucid, precise, quanta,l and raring for 2.0.1 and for oneiric a 1.8.0 version

Should I change the text to this?

**Comment by rduivenvoorde** [comment]
will close this, plz reopen when there still are issues
