### ISSUE TITLE
Transifex push action is failing

### ISSUE THREAD

**Issue by m-kuhn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1049]
Tx push action is failing, see https://github.com/qgis/QGIS-Website/actions/runs/2977249556 

Any idea?

_Originally posted by @rduivenvoorde in https://github.com/qgis/QGIS-Website/issues/1048#issuecomment-1235155988_

**Comment by m-kuhn** [comment]
@rduivenvoorde not sure how the missing file documentation.po is supposed to be created?

**Comment by jef-n** [comment]
source/site/forusers/documentation.rst was removed in 8c9bdb0252d262a70998764b4353d960f084190a.  363a7a615a5f42ef532a2d9fec3114f0c7c34dd0 removes all files from .tx/config so create_transifex_resources.sh can re-detect them on the fly.
