### ISSUE TITLE
Missing "List of Project Steering Committee Resolutions" from 2021 onwards?

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1050]
## Description
In the Governance page, only the "List of Project Steering Committee Resolutions - 2019" and the "List of Project Steering Committee Resolutions - 2020" sub pages are available.

Page URL: https://qgis.org/en/site/getinvolved/governance/index.html

**Comment by DelazJ** [comment]
@anitagraser @mbernasocchi @andreasneumann can any of you help fix this please? Thanks

**Comment by anitagraser** [comment]
The practice of copying the resolutions to the website was not sustainable for us. We keep on publishes the minutes including resolutions to https://github.com/qgis/QGIS/wiki#psc-meetings
I assume the new website will do away with these sub pages.
