### ISSUE TITLE
Link for nightly install unavailable ?

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1056]
At https://qgis.org/en/site/forusers/download.html#, Source tab, it is stated:
> Note that you can also install the development version (nightly) via an installer from the normal downloads for your platform: [here](https://qgis.org/en/site/forusers/download.html#)

Clicking that link brings you to the "Installation downloads" tab (I can't tell to what item it brings you precisely). There afaict, there is no (obvious) installer, no instructions on where to find those nightlies nor how to install them.

**Comment by agiudiceandrea** [comment]
I think that line should be removed along with the next line

> Plugins for QGIS are also available here

as the section is about the source code and the same line is also present in the "ALL RELEASES" section.
