### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1058]
## Description

The phrase "QGIS is available on Windows, macOS, Linux, Android and iOS." which is present in the Download page https://github.com/qgis/QGIS-Website/blob/b8ebd0fc10dbeb18f8243daaf9fee03ffe5f6d63/themes/qgis-theme/forusers_download.html#L7 and in the "All Download" page https://github.com/qgis/QGIS-Website/blob/b8ebd0fc10dbeb18f8243daaf9fee03ffe5f6d63/source/site/forusers/alldownloads.rst#L11 reults not translated in Italian language while the translation is available in Transifex (since more than 2 weeks).

![image](https://user-images.githubusercontent.com/16253859/189823726-6b0b7dab-d9d4-4a50-8db5-cbf94f16059d.png)
![image](https://user-images.githubusercontent.com/16253859/189823775-244c35d1-8de2-4e57-9aa2-4678b963ed99.png)
![image](https://user-images.githubusercontent.com/16253859/189824050-7af086a1-78c5-45a4-a064-cbbe5fd05ada.png)

Page URL:
https://qgis.org/it/site/forusers/download.html
https://qgis.org/it/site/forusers/alldownloads.html#qgis-installers

**Comment by agiudiceandrea** [comment]
Also: "New release: 3.26!"
![image](https://user-images.githubusercontent.com/16253859/190028682-91ae1cdb-0fa3-4dee-a50f-01e311cdd3b4.png)

![image](https://user-images.githubusercontent.com/16253859/190028746-038d8ecf-2d2f-4e26-89bc-3fc83b69f0a7.png)

**Comment by rduivenvoorde** [comment]
@m-kuhn @jef-n should the github machinery do this (the push to transifex)?

Or should I (still) do this manually?

```
# ONLY to be done by a transifex Maintainer for the project, as it overwrites
# the english source resources
# 1) make springclean (removing all building cruft)
# 2) make pretranslate (getting all strings from sources and create new pot files)
# 3) scripts/create_transifex_resources.sh (will update the .tx/config file with new resources)
# 4) tx push -fs --no-interactive (push the source (-f) files forcing (-f) overwriting the ones their without asking (--no-interactive)
# note that you need a valid .transifexrc file in ~ for credentials
```

Mmm, looking at .tx/config... I see it is empty:
https://github.com/qgis/QGIS-Website/commit/363a7a615a5f42ef532a2d9fec3114f0c7c34dd0

Then maybe the "let tx_push.yml detect the resources" is not working <= @jef-n ?

I just pushed manually the strings, not sure if this fixes this issue though...

**Comment by jef-n** [comment]
> @m-kuhn @jef-n should the github machinery do this (the push to transifex)?

That just pushes the translations to transifex.

> Mmm, looking at .tx/config... I see it is empty: [363a7a6](https://github.com/qgis/QGIS-Website/commit/363a7a615a5f42ef532a2d9fec3114f0c7c34dd0)
> 
> Then maybe the "let tx_push.yml detect the resources" is not working <= @jef-n ?

Is pulling the translations not working anymore in the actual build?    Pushing was complaining about resources in .tx/config that didn't exist anymore (IIRC site/forusers/documentation.po).

**Comment by rduivenvoorde** [comment]
Indeed pulling translations from tx does not work anymore::

 langs=it ./docker-world.sh full
 ... 
 Pulling it from transifex
 tx INFO: Done.

Nothing pulled...
Have to look into this...

**Comment by rduivenvoorde** [comment]
AH!! that is because .tx/config is empty!!!

Because the contents of that file are pulled...

Will recreate it again...

**Comment by rduivenvoorde** [comment]
Yes, now the docker runs on qgis6 are pulling translations again.
(I found out because sphinx.po did NOT contain the italian translation for "New release: 3.26!", while it is on transifex...)

![gnome-shell-screenshot-ghslml](https://user-images.githubusercontent.com/731673/190116051-597ce2ba-57f4-40cb-920f-ecbe6e29da94.png)


But (as I'm not fully aware what others are automating via github), it is off course also possible to make sure that the po file are updated via other routes (and pushed/merged into github)...
(what I want to say: the tx pull during the build is not necessary if other processes can make sure the po files are fresh (on github))

**Comment by agiudiceandrea** [comment]
Thanks @rduivenvoorde.
The issue at https://qgis.org/it/site/forusers/alldownloads.html#qgis-installers is also fixed
![image](https://user-images.githubusercontent.com/16253859/190120597-79254c85-7cd8-4b88-a296-7f9b7d1d9933.png)


While the issues at https://qgis.org/it/site/forusers/download.html are not yet fixed
![image](https://user-images.githubusercontent.com/16253859/190120912-46b3c35e-799d-4dbd-8c99-d893ae26b73b.png)

**Comment by rduivenvoorde** [comment]
![gnome-shell-screenshot-28iu82](https://user-images.githubusercontent.com/731673/190121664-c15c8dd5-35e5-444e-9941-f7d70672c7cb.png)

![gnome-shell-screenshot-b30oan](https://user-images.githubusercontent.com/731673/190121911-87c80462-30d5-4470-80e5-a73462ea3953.png)

cache? Try: https://nocache.qgis.org/it/site/forusers/download.html (that one is NOT going via cloudflare)

also I see a lot of discussion about the exact wording there.. so some strings are maybe already changed?

**Comment by agiudiceandrea** [comment]
@rduivenvoorde, thanks again! the nocache URL contains the correct translation.

**Comment by agiudiceandrea** [comment]
So, can we close this now?

**Comment by rduivenvoorde** [comment]
Mmm, yes, I think. Unless @jef or @m-kuhn think that I'm doing things which do not correspond to the new workflows...

**Comment by m-kuhn** [comment]
> AH!! that is because .tx/config is empty!!!
> 
> Because the contents of that file are pulled...
> 
> Will recreate it again...

How? Is this/does that need to be a manual process?

**Comment by rduivenvoorde** [comment]
@m-kuhn yes, whenever new pages are added, you have to update the list using the `scripts/create_transifex_resources.sh` script. I did this whenever I knew new pages were added, like when a new visual changelog was created or a new user story or so.. OR when translators complained that they could not find strings from a certain resource.
But I think it is ok to run it every time... 

But my question would be: did you not do something (or had plans) which made transifex sync from github?

**Comment by m-kuhn** [comment]
> But my question would be: did you not do something (or had plans) which made transifex sync from github?

Yes, but so far the step to create transifex resources has not been integrated and it failed with an outdated .tx/config file.
