### ISSUE TITLE
Download link Windows standalone installer 3.26.3

### ISSUE THREAD

**Issue by pathmapper** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1059]
## Description

The link on https://qgis.org/en/site/forusers/download.html is still pointing to 

https://qgis.org/downloads/QGIS-OSGeo4W-3.26.2-1.msi  

despite

https://qgis.org/downloads/QGIS-OSGeo4W-3.26.3-1.msi

is available. Is this expected?

![grafik](https://user-images.githubusercontent.com/20856381/189897780-6f2a4294-b036-4133-be70-a412ee5da6d6.png)

**Comment by nicogodet** [comment]
fixed

**Comment by pathmapper** [comment]
Thanks @jef-n
