### ISSUE TITLE
filter QGIS hub issues by category without waiting for final check ?

### ISSUE THREAD

**Issue by pboulerie** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#106]
Re : filter QGIS hub issues by category without waiting for final check ?

Hello,

There is a bug or missing feature in the interface :
http://hub.qgis.org/projects/quantum-gis/issues?set_filter=1

In that page http://hub.qgis.org/projects/quantum-gis/issues
if I add the filter Category
then in the menu Category, my final choice is not applied automatically.

I have to refresh my screen using the link \* with the green V- mark (a.icon.icon-checked)...
## http://hub.qgis.org/images/true.png
- in French : Appliquer
  (Apply)

**Comment by rduivenvoorde** [comment]
this issue list is only for issue of QGIS-Website, sorry.

I think you need to copy this issue, either to https://github.com/qgis/QGIS-Redmine-Hub or ask on the dev list where to issue these problems.

plz close this one if that is done
