### ISSUE TITLE
Broken link to What's new in the carousel

### ISSUE THREAD

**Issue by anitagraser** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#107]
Print
 QGIS 2 Print Composer has received a major face-lift ... check out the new features

points to:
http://www.qgis.org/en/docs/user_manual/whats_new/whats_new.html#map-composer

should be:
http://www.qgis.org/en/docs/user_manual/preamble/whats_new.html#map-composer

**Comment by rduivenvoorde** [comment]
hi anita,
the 'docs' part of the website come actually straight from the QGIS-Documentation repository.
So I close this one, and created one at docs:

https://github.com/qgis/QGIS-Documentation/issues/161

**Comment by anitagraser** [comment]
Hi Richard,
So the link in the carousel should be correct? Strange but if you say so ....

**Comment by rduivenvoorde** [comment]
Nope sorry, it was not clear to me that you were talking about a link in the carroussel in the website.

Fixed now in https://github.com/qgis/QGIS-Website/commit/a6ce38d107986aefe3f3d8ac167e154fb4aa6a90
