### ISSUE TITLE
ERROR-202 (anl_arc, anl_node, anl_connec) (DB OM):There is/are 10 which id is not an integer. Please, check your data before continue

### ISSUE THREAD

**Issue by dayanaa2727** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1071]
ERROR-202 (anl_arc, anl_node, anl_connec) (DB OM):There is/are 10 which id is not an integer. Please, check your data before continue

how can i solve the error?

**Comment by DelazJ** [comment]
> how can i solve the error?

@dayanaa2727 First, I'd suggest to follow what the message reports, that is, check your data and find the 10 features whose Id field is not an integer and fill it correctly.
Then, when reporting issue/requesting help, please take the time to provide some context (what were you doing/expecting?) to help others help you. They shouldn't have to guess it.

Last, this repository is for handling QGIS website. It is not for the sotware or plugins issues, or help users. See [support channels](http://qgis.org/en/site/forusers/support.html). I'm thus closing. Thanks for understanding.
