### ISSUE TITLE
Missing Thank You / Donation overlay text in the Download page

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1077]
## Description

The Download page used to display an overlay with thanks and a Donation button after the user clicked on a download link.

![image](https://user-images.githubusercontent.com/16253859/199955755-ae52e540-a280-4e99-ab92-4ae2623864fd.png)

Now such overlay is no longer displayed.

It seems to me this is an unwanted side effect of the "Download page simplification" PR https://github.com/qgis/QGIS-Website/pull/1046.

Looking at the qgis-donations bot activity https://github.com/qgis-donations, such side effect may be responsible for the decrease in donations reported by the qgis-donations bot after the 9th of September (when the "Download page simplification" was merged).

![image](https://user-images.githubusercontent.com/16253859/199957779-5ff9f7bb-49ba-4db7-a14c-f10f2db8399f.png)

See also the thread at https://lists.osgeo.org/pipermail/qgis-community-team/2022-November/006083.html.

Page URL: https://qgis.org/en/site/forusers/download.html

**Comment by agiudiceandrea** [comment]
The issue is caused by the change in the names of the classes for the download buttons and links, while the JavaScript function at https://github.com/qgis/QGIS-Website/blob/4a6d80034926ce530bb23289ada22aa1a6884310/themes/qgis-theme/languageswitch.html#L110-L113 was incorrectly not changed accordigly.

Changing it with something like:
```javascript
            $('a.btn.btn-large.btn-success').click(function(){
                $('#thankyou').show();
                return true;
            });
            $('a.secondary-download-link').click(function(){
                $('#thankyou').show();
                return true;
            });
```
would fix the issue and let the overlay with thanks and a Donation button display after the user clicked on a download link in the main download page for primary and secondary links for Windows (excluding OSGeo4W Network Installer) and macOS.

**Comment by faebebin** [comment]
thanks @agiudiceandrea for reporting this IMO important bug. I would rather add the `reference` class to template. Will open a PR

**Comment by jmckenna** [comment]
For the record I initially reported this at https://lists.osgeo.org/pipermail/qgis-community-team/2022-November/006082.html I agree, very very important.
