### ISSUE TITLE
2 comments about README.html in the documentation guidelines

### ISSUE THREAD

**Issue by pboulerie** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#108]
Re : 2 comments about README.html in the documentation guidelines

About page : http://qgis.org/en/docs/documentation_guidelines/README.html

> use of rst

use of rst files (Python ReStructuredText – RST – formatted files)

(Please always explain unknown acronyms to newbies : I had never heard about rst files before I came to the insights of QGIS documentation...)

Please also add a final section in the Introduction, or a final section « Miscellaneous » or « Other), with the following content :

To know more about the QGIS.org documentation website engine itself which is based on Sphinx, please visit their website at : http://sphinx-doc.org
(and to report about issues concerning the behaviour of Sphinx itself, please use their Sphinx bug issue tracker at BitBucket :
https://bitbucket.org/birkenfeld/sphinx/issue/ )

**Comment by DelazJ** [comment]
This is somehow fixed in https://github.com/qgis/QGIS-Documentation/commit/d12de3fee4ec1c3b3303edd22f973a69d279787c. I'm not sure it's relevant to point to upstream issue tracker.

**Comment by rduivenvoorde** [comment]
Agree with @DelazJ 

Let's close this one.
