### ISSUE TITLE
v3.28.0 is marked with "RC" on main page

### ISSUE THREAD

**Issue by IanCundall** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1081]
Should this be removed, if 3.28.0 is Production-ready? My user with 3.26.3 is being prompted that 3.28.0 is available but we have a policy of not deploying beta/RC software so have baulked at this stage.

Page URL: https://qgis.org/en/site/

**Comment by nicogodet** [comment]
It should not. It will be removed on .1 and 3.28 will become LTR on .4.
