### ISSUE TITLE
https://www.qgis.org/fr/docs/index.html points to 3.22 and 3.16

### ISSUE THREAD

**Issue by nicogodet** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1088]
## Description

Page URL: https://www.qgis.org/fr/docs/index.html

**Comment by rduivenvoorde** [comment]
That is deliberate. That is the 'docs index' page in the website

We do not have translations/builds for 3.28 yet.

We do have english (only) builds for 3.28: https://docs.qgis.org/testing/en/docs/

3.22 is still LTR
