### ISSUE TITLE
The "Push strings to transifex" action is continuosly failing since Nov, 17th

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1089]
## Description

See https://github.com/qgis/QGIS-Website/actions/workflows/tx_push.yml

**Comment by DelazJ** [comment]
Looks like we need a tx token, hence someone with admin rights on this repo... @m-kuhn can you give it a look please?

**Comment by m-kuhn** [comment]
The API version 2 on transifex was recently phased out, right now only API version 3 is available if I'm not wrong. https://pypi.org/project/transifex-client/ is not compatible with the new version and a different client need to be used instead.

**Comment by agiudiceandrea** [comment]
Any news about this issue which is probably the root cause of the issue https://github.com/qgis/QGIS-Website/issues/1092?

**Comment by m-kuhn** [comment]
I've tried to change the toke with no success.
@why-not-try-calmer could you have a look at this?

**Comment by DelazJ** [comment]
@m-kuhn Have you tried to setup [a github<->transifex integration ](https://help.transifex.com/en/articles/6265125-github-via-transifex-ui). We have this implemented for the docs ([here](https://github.com/qgis/QGIS-Documentation#translating) and [here](https://www.transifex.com/qgis/qgis-documentation/settings/integrations/) and push and pulls seem to work. But TBH I no longer understand the logic of the website translation system so maybe my suggestion is useless.

**Comment by m-kuhn** [comment]
No, I have no experience with that.

**Comment by why-not-try-calmer** [comment]
Thanks for meging @DelazJ, to avoid the multiplication of PRs for fixing Transifex workflows I'll open one last PR to host all future commits related to the fix if that's ok for you. I'll mark it as not-to-be-merged-until-everything-works.

**Comment by DelazJ** [comment]
@why-not-try-calmer I'm fine with whatever suits you. Just do, and tell us when you think it is ready.

**Comment by why-not-try-calmer** [comment]
Tracking efforts & improvements in #1111. This issue could be closed.

**Comment by DelazJ** [comment]
Let's then follow #1111
