### ISSUE TITLE
Qgis crash

### ISSUE THREAD

**Issue by Alejandro-imta** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1090]
Crash ID: [203625fd141be7a0269147ea51d928b3c1551033](https://github.com/qgis/QGIS/search?q=203625fd141be7a0269147ea51d928b3c1551033&type=Issues)

Stack Trace

RtlpFreeHeapInternal :
RtlFreeHeap :
free free.c:51
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:881
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CApartmentActivator::CreateInstance actvator.cxx:2189
CProcessActivator::CCICallback actvator.cxx:1640
CProcessActivator::AttemptActivation actvator.cxx:1527
CProcessActivator::ActivateByContext actvator.cxx:1371
CProcessActivator::CreateInstance actvator.cxx:1271
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CClientContextActivator::CreateInstance actvator.cxx:570
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
ICoCreateInstanceEx objact.cxx:2032
CComActivator::DoCreateInstance immact.hxx:392
CoCreateInstance actapi.cxx:121
InsHook_CoCreateInstance :
BdhkmIsApiInDllImports :
BdhkmIsApiInDllImports :
CByteHashTable::_AddUpdateItem :

QGIS Info
QGIS Version: 3.22.13-Bia?owie?a
QGIS code revision: 02ff117c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0
Running against GDAL: 3.6.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by agiudiceandrea** [comment]
@Alejandro-imta, you have reported the issue in the wrong GitHub repository. Please close this issue report and open a new issue report in the correct GitHub repository at https://github.com/qgis/QGIS/issues providing all the requested information.
