### ISSUE TITLE
QGIS functions not working

### ISSUE THREAD

**Issue by Amirboger123** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1091]
hello,
my name is Amir, Im a QGIS user,
and today I found out that most of the functions (such as "merge", "refactor" ext...) are simply not avilable.
In addition, the functions window is simply not there (and I coulden't find it).
Any Idea why is this happening?
thanks :)

**Comment by nicogodet** [comment]
Can you check if "Processing provider" is activated in extensions ?
![image](https://user-images.githubusercontent.com/39594821/206181172-eaeab1d0-060e-4c0c-a840-5a53cc2540df.png)

**Comment by nicogodet** [comment]
And QGIS related issue should be reported in https://github.com/qgis/QGIS/issues

**Comment by Amirboger123** [comment]
It worked!
thanks!
and no problem, I'll send it to this section next time :)

**Comment by agiudiceandrea** [comment]
@Amirboger123, could you please close this issue report?
