### ISSUE TITLE
Download of Windows installer fails - 404 Not Found

### ISSUE THREAD

**Issue by ronzulu** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1093]
## Description

Page URL:

https://www.qgis.org/en/site/forusers/download.html

Clicking on either latest 3.28 or LTR 3.22 leads to the following links:
https://qgis.org/downloads/QGIS-OSGeo4W-3.28.2-1.msi
https://qgis.org/downloads/QGIS-OSGeo4W-3.22.14-1.msi

Download doesn't occur
https://download.osgeo.org/qgis/windows/QGIS-OSGeo4W-3.28.2-1.msi?US

404 Not Found

**Comment by agiudiceandrea** [comment]
@ronzulu, it seems the issue is fixed now. Could you check again?

**Comment by ronzulu** [comment]
Yes, all good now. Thanks, and thanks to whoever fixed it :-)
