### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by drharshitsinha** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1095]
Dear GIS team
I have MacBook Pro (Retina, 15-inch, Mid 2015)
While downloading any version I am getting this message
“3 Install QGIS 3.18.pkg” cannot be opened because it is from an unidentified developer.”
"MacOS cannot verify that this app is free from malware"
Please provide valuable suggestions to overcome this problem and download the desired version of QGIS on my Macbook Pro
Email: [drharshitsinha@consultant.com](mailto:drharshitsinha@consultant.com) or can call me +91-93777 31225

**Comment by agiudiceandrea** [comment]
@drharshitsinha, have you read the advise in the QGIS installer for macOS download page?
"macOS High Sierra (10.13) or newer is required. QGIS is not yet notarized as required by macOS Catalina (10.15) security rules. On first launch, please right-click on the QGIS app icon, hold down the Option key, then choose Open."
![image](https://user-images.githubusercontent.com/16253859/210157002-5c8dd631-61ec-48d0-9837-c6370b67f61a.png)
Is such advise useful for you?

**Comment by agiudiceandrea** [comment]
I think this issue report should be closed.
