### ISSUE TITLE
Transifex translations fail to update from CI

### ISSUE THREAD

**Issue by why-not-try-calmer** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1111]
The Github action updating translations [fails](https://github.com/qgis/QGIS-Website/actions/runs/4141176480/jobs/7160516416) because the configuration file (`.tx/config`) is being dynamically re-written to a deprecated format.

I will fix it in the upcoming hours. This Issue is purposed with tracking the work under way, as one PR was not enough.

 Tracking action logs:

_TX\_TOKEN_501_
- #1112 => https://github.com/qgis/QGIS-Website/actions/runs/4144664749/jobs/7168003352
- #1113 => https://github.com/qgis/QGIS-Website/actions/runs/4162097289/jobs/7200842354

**Comment by why-not-try-calmer** [comment]
@jef-n Thanks for merging #1113, would it be possible to regenerate TX_TOKEN? Might be the culprit or at least help narrow down on the culprit.

**Comment by agiudiceandrea** [comment]
@why-not-try-calmer it seems to me this si fixed now. Could you check?

**Comment by why-not-try-calmer** [comment]
> @why-not-try-calmer it seems to me this si fixed now. Could you check?

From what I see looking at the Github Action outputs, it is indeed fixed! Feel free to reopen should any problem arise.
