### ISSUE TITLE
Typo in Download page (Windows)

### ISSUE THREAD

**Issue by nickbearman** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1114]
## Description

There is a typo in the https://qgis.org/de/site/forusers/download.html page, in the for Windows section. 

It says:
"Looking for the most stable version? Get QGIS 3.22LTR"

there should be a space between 3.22 and LTR

"Looking for the most stable version? Get QGIS 3.22 LTR"

Page URL: https://qgis.org/de/site/forusers/download.html

Also the 'fix me' link takes me to https://github.com/qgis/QGIS-Website/edit/master/source/site/forusers/download.rst, where this text isn't present. It mentions HTML texts but I don't know where they are. 

Thanks! :-)

**Comment by jef-n** [comment]
Not visible here - both in the (untranslated) german version and in English.

**Comment by DelazJ** [comment]
> Also the 'fix me' link takes me to https://github.com/qgis/QGIS-Website/edit/master/source/site/forusers/download.rst, where this text isn't present. It mentions HTML texts but I don't know where they are.

@nickbearman Here https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/forusers_download.html

**Comment by nickbearman** [comment]
Thanks - it's there now. 
Thanks for speedy response. 
Best wishes, Nick.

**Comment by nickbearman** [comment]
Useful link too - thanks!
https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/forusers_download.html

Would it be ok to add that into here?
https://github.com/qgis/QGIS-Website/edit/master/source/site/forusers/download.rst

That will help me when I forget in the future!

**Comment by DelazJ** [comment]
I don't think it would hurt. And probably to the other pages that behave the same (bring to an empty rst file while the sources are in https://github.com/qgis/QGIS-Website/tree/master/themes/qgis-theme)
