### ISSUE TITLE
QGIS新建Shapefile图层时，使用中文作为表头新建成功保存后，表头成为乱码，UTF-8、GBK编码都无法转回中文

### ISSUE THREAD

**Issue by dt123456789** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1115]
QGIS新建Shapefile图层时，使用中文作为表头新建成功保存后，表头成为乱码，UTF-8、GBK编码都无法转回中文

**Comment by DelazJ** [comment]
@dt123456789 Please report in English, and notice that this repository is for managing QGIS website, not the [software](https://github.com/qgis/QGIS/issues)

**Comment by dt123456789** [comment]
@DelazJ Excuse me, where should I give feedback on my questions? Please guide me. Thank you.

**Comment by DelazJ** [comment]
@dt123456789 I do not understand your initial message so hard to tell; Translate and I can try to help.

**Comment by dt123456789** [comment]
@DelazJ    When QGIS creates a new Shapefile layer, it uses Chinese as the header of the table. After it is successfully saved, the header becomes garbled, and the UTF-8 and GBK codes cannot be converted back to Chinese. What is the problem, or my operation problem, please guide me, thank you

**Comment by DelazJ** [comment]
Clear now.
Can you try on a new QGIS user profile (https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)? If the bug still occurs, the right place is at https://github.com/qgis/QGIS/issues but please fill all the requested information there about your environment (OS, QGIS version (better if it is 3.22 or 3.28), exact steps to reproduce,...). Hope that helps.

**Comment by dt123456789** [comment]
@DelazJ Please tell me where the feedback is. I can't find the entrance. After entering the entrance on the upper right, I don't know where to enter

![1676427832946](https://user-images.githubusercontent.com/45315055/218911252-bc658ff4-f34a-4e4a-b1f7-3578b2d14773.jpg)
![image](https://user-images.githubusercontent.com/45315055/218911474-23e0dd24-2245-44cb-bf7c-875c8685a8f6.png)

**Comment by DelazJ** [comment]
The first option (bug/crash...)

**Comment by dt123456789** [comment]
@DelazJ 
This?

![image](https://user-images.githubusercontent.com/45315055/218912362-955ba57f-11c6-40d0-a7f3-f06598b618d4.png)

**Comment by DelazJ** [comment]
Yes.
Did you try to fix the issue with a new QGIS user profile, as suggested above?

**Comment by dt123456789** [comment]
@DelazJ 
The problem has not been solved. Thank you for your help. My English is not good. Please understand. Thank you

**Comment by dt123456789** [comment]
@DelazJ Which country do you come from?

**Comment by DelazJ** [comment]
No worries about your English. It is good and clear.
France

**Comment by dt123456789** [comment]
@DelazJ For QGIS, this is a very good software. I originally wanted to use the original version, but I can't use English. I can only download the local version. What time is it in France now

**Comment by agiudiceandrea** [comment]
@DelazJ I think this issue report can be closed. See https://github.com/qgis/QGIS/issues/51867.
