### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1116]
## Description

The translation of some strings, which is available on Transifex since months, is missing on the Website.

For example, in the page https://qgis.org/it/site/forusers/download.html

![image](https://user-images.githubusercontent.com/16253859/220875871-1cb4150f-511b-43fb-a2a9-81d9ab78980a.png)
![image](https://user-images.githubusercontent.com/16253859/220876379-e104985d-5341-4600-bf6c-7e3ea203adc0.png)
![image](https://user-images.githubusercontent.com/16253859/220876602-dedf2cf2-faf5-4a6c-b8ae-31aae6cefe3e.png)
and probably other strings...

**Comment by rduivenvoorde** [comment]
Hi Andrea, should this be fixed by: https://github.com/qgis/QGIS-Website/issues/1111 ?
As in: is this a github action now?
Or should I manually update the strings ?

**Comment by DelazJ** [comment]
@rduivenvoorde From a quick glance, I can see action to push to transifex but I couldn't find instructions regarding pulling. Probably still a manual work for now...

**Comment by agiudiceandrea** [comment]
@DelazJ @rduivenvoorde, moreover, the translations are available on transifex since months. The translations were online last December https://web.archive.org/web/20221204060155/https://qgis.org/it/site/forusers/download.html

![image](https://user-images.githubusercontent.com/16253859/220880547-24645f3b-0af7-4722-94ea-19976fedfdb2.png)

**Comment by rduivenvoorde** [comment]
Not sure what your message is?

Do you think it is an issue with pulling from transifex? As: the sources are uptodate, translated, but not pulled/build?

**Comment by DelazJ** [comment]
Afair, pulling from Transifex has always been a manual process so if nobody took this in charge in the last months, then it is normal the website is not up to date with translations

**Comment by agiudiceandrea** [comment]
@DelazJ there was something like a "regression": various strings already translated since months in transifex and already displayed translated on the website last December, "regressed" to the untranslated version.

**Comment by rduivenvoorde** [comment]
> Afair, pulling from Transifex has always been a manual process so if nobody took this in charge in the last months, then it is normal the website is not up to date with translations

I do not think so? What I did manually was (often when there was some new release of bigger update of the website), is to create the list of resources, AND the new source file (the english one) and push that to transifex.

But the pulling from transifex was always part of the build scripts... (tx pull...)

But I think the pulling is now done by Sphinx itself? Or by some automagic action? 
 
I will try to do the italian build now... and see if stuff is pulled...

**Comment by rduivenvoorde** [comment]
Ok, I see this: 

```
Already up to date.                                                                                               
rm -rf source/static                                                                                              
# something in i18n/pot dir creates havoc when using gettext: remove it                  
rm -rf i18n/pot                                                                                                   
rm -rf i18n/*/LC_MESSAGES/docs/*/                                                                                 
rm -rf output/html/it/*                                                                                           
rm -f source/docs_conf.py*                                                                                        
rm -rf source/docs/*/                                                                                             
# all .mo files                                                                                                   
find i18n/*/LC_MESSAGES/ -type f -name '*.mo' -delete                                                             
                                                                                                                  
Pulling it from transifex                                                                                         
tx ERROR: not enough values to unpack (expected 2, got 1)                       
make html                                                                                                         
make: [Makefile:149: full] Error 1 (ignored)                                                                      
make[1]: Entering directory '/site'                                                                                                                                                                                                  
rm -rf source/static                                                                                              
                                                                                                                  
Removing all static content from source/static. 
```

**Comment by agiudiceandrea** [comment]
See also https://github.com/qgis/QGIS-Website/issues/1058.

**Comment by DelazJ** [comment]
@rduivenvoorde did you update tx to the new tool (https://github.com/transifex/cli)?

**Comment by rduivenvoorde** [comment]
@DelazJ @jef-n @why-not-try-calmer not sure what is going on here, but 
https://github.com/qgis/QGIS-Website/commit/5be4d374e226cbc651dbdbe18a56f285a551b626
added a tx binary(!) to the repo?
and replaced our README with a copy from (I think) the tx cli repo?

@DelazJ IF we need a new tx tool we have to create a (docker) images so it is included in either the images, or we should make it available on the build server? 

(I'm fairly lost in the build process now, sorry)

**Comment by why-not-try-calmer** [comment]
> @DelazJ @jef-n @why-not-try-calmer not sure what is going on here, but [5be4d37](https://github.com/qgis/QGIS-Website/commit/5be4d374e226cbc651dbdbe18a56f285a551b626) added a tx binary(!) to the repo? and replaced our README with a copy from (I think) the tx cli repo?
> 
> @DelazJ IF we need a new tx tool we have to create a (docker) images so it is included in either the images, or we should make it available on the build server?
> 
> (I'm fairly lost in the build process now, sorry)

Apparently my fork used the CI from upstream (this repository) to re-commit the wrong README. Thanks for raising this to my attention => #1117.

**Comment by DelazJ** [comment]
>  added a tx binary(!) to the repo?

Yes I noticed that while working on the docs repo update (forgot to ask whether it is desirable). We need the github action to take care of their removal also IMHO. Or maybe should we just go with https://github.com/transifex/cli-action? What do you think @why-not-try-calmer ?
> @DelazJ IF we need a new tx tool

We DO need the new tool. I had scripts failing in docs too. The old transifex-client no longer works (officially for months but actually for 1 or 2 wweks). And the new tool is the one ued in this repo now, so we need to align our tools.
> we have to create a (docker) images so it is included in either the images, or we should make it available on the build server?

I'm not versed in these considerations but I'd say better add it to the docker image?

**Comment by DelazJ** [comment]
Question: is it expected to not have 'en' in [i18n folder](https://github.com/qgis/QGIS-Website/tree/master/i18n)? It used to be there (https://github.com/qgis/QGIS-Website/commits/master/i18n: present in 062251a3a84d9bdd53b72b9068e420b385ae66aa, removed in 9e1bf2fc0f45347a9eb0776197d8636a970473e2)

**Comment by agiudiceandrea** [comment]
The translations are missing in the latest build of the website (feb 24, 2023), too. The same translated texts are missing also in other languages, probably in all:
![image](https://user-images.githubusercontent.com/16253859/221096797-c152443d-479f-4359-a652-df40bf8640f6.png)
![image](https://user-images.githubusercontent.com/16253859/221096872-8239ea9f-548b-41a1-9e0a-d7aee43cd36d.png)

It seems currently a manual update is needed like last time https://github.com/qgis/QGIS-Website/issues/1058.

**Comment by DelazJ** [comment]
Seems manual pulling fixes the issue. Reopening so that it gets fixed on server side. Locally it required:
* remove any trace of transifex, spinx-intl[transifex] "packages" (also remove the latter from REQUIREMENTS.txt)
* update the .transifexrc file to new format
* install the tx-cli

**Comment by rduivenvoorde** [comment]
Ok, I have updated/tested the docker images and pushed them to hub.docker.com

For what I see, now the website is building as it should

I did have to change stuff to make tx work with the local .transifexrc file.. so probably the doc sites also have to be updated...

**Comment by rduivenvoorde** [comment]
Mmm apperently those (looking at docs 3.22)  do not use the tx cli to pull translations into the build. So probably all will be fine \o/

**Comment by DelazJ** [comment]
Thanks for the efforts @rduivenvoorde. Closing the report....
> Mmm apperently those (looking at docs 3.22) do not use the tx cli to pull translations into the build. So probably all will be fine \o/

Indeed, docs translation follows [another route](https://github.com/qgis/QGIS-Documentation#translating) and the repo on server is only the end point. Pulling is done directly by Transifex or from a local repo (until https://github.com/qgis/QGIS-Documentation/issues/7827 one day).

**Comment by agiudiceandrea** [comment]
> For what I see, now the website is building as it should

Thanks, @rduivenvoorde and @DelazJ.
