### ISSUE TITLE
Installation instructions for Ubuntu are not working

### ISSUE THREAD

**Issue by Nadjoo** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1125]
## Description

The installation instructions on https://www.qgis.org/de/site/forusers/alldownloads.html#debian-ubuntu (german) for adding the APT sources file /etc/apt/sources.list.d/qgis.sources is broken somehow:

> Suites in den obigen Zeilen hängt von der verwendeten Distribution ab. lsb_release -cs zeigt den Distributionsnamen an.
> 
> In manchen Distributionen (wie Linux Mint) zeigt [``](https://www.qgis.org/de/site/forusers/alldownloads.html#id1)./etc/os-release; echo „$UBUNTU_CODENAME“ den richtigen Distributionsnamen an.
> 
> Siehe [Available codenames](https://www.qgis.org/de/site/forusers/alldownloads.html#available-codenames).

While the command should be `. /etc/os-release && echo $UBUNTU_CODENAME`, the command in the documentation is not correctly shown and cannot be copied.

I see this as very important because this would sometimes frighten users to install QGIS.

Page-URL: https://www.qgis.org/de/site/forusers/alldownloads.html#debian-ubuntu

**Comment by jef-n** [comment]
fixed in transifex
