### ISSUE TITLE
Crash writing 3D animation images

### ISSUE THREAD

**Issue by funkenbeachin** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1128]
QGIS versions 3.22.15 and 3.22.16 LTR and 3.28.3 (not 3.22.14) crash suddenly while writing animation image files in the 3D view.  Windows 10 home on 3 years old PC, 64G memory, plenty of disk space, no other programs running.  The crash occurred 3 times after writing ~500 files. One time it crashed while building the pan path.  Camera angle was ~45 degrees.  Project files are DEM raster tif.  

QGIS v3.22.14 works fine, is robust in many projects.  I would point to the new features in the 3D panel in 3.22.15  LTR and 3.28.3 as the cause.

**Comment by DelazJ** [comment]
Hi @funkenbeachin,

Please report this in the [application issue tracker](https://github.com/qgis/QGIS/issues) with details of your QGIS version (the Help --> About page) and with a project file to help devs reproduce. You may also want to retry with [a clean profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)
This repository is dedicated to [QGIS Website](https://qgis.org) issues, hence I'm closing.
Thanks.
