### ISSUE TITLE
Stripe not working, button is greyed out

### ISSUE THREAD

**Issue by frspp** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1129]
Hi!

I tried to donate in https://donate.qgis.org/ using Stripe. Cannot because the Checkout button stays greyed out always.

Latest Windows 11
Latest Firefox in strick private mode
Latest Chrome in private

**Comment by rduivenvoorde** [comment]
Can you try to do a hard refresh (like ctrl-F5 or so).
In my case at first the button was greyed out with me also, but after the refresh the 'captcha' appeared (maybe also need to accept the cookies??).

After I finished the captcha, the button worked...

**Comment by frspp** [comment]
Ah yes, accepting the cookies and/or force refresh on firefox does the trick. So kinda buggy.

**Comment by rduivenvoorde** [comment]
Well, it's just not easy to script against the stripe api... 
Without gaptcha de widget could be use to  'check validity of creditcard numbers'...
So we needed the gaptcha... 
Anyway, closing for now
