### ISSUE TITLE
SplitFeatures function cannot create 3D vertex

### ISSUE THREAD

**Issue by Speed1987sS** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1130]
Before update I use version 3.24
I can use "splitfeatures" function to split 3Dpolyline and 3Dpolygon with z value created with result.
After update to 3.30, I split 3Dpolyline and 3Dpolygon, i get "0" z value with vertex i splited.
Can anyone help to fix it?

**Comment by rduivenvoorde** [comment]
Hi,

This is the issue tracker for the Website. 

Please subscribe to the user or developer mailing list, to be able to ask there.

Or create an issue (with more info the here, preferably some example data) in the issue tracker of QGIS itself: https://github.com/qgis/QGIS/issues
