### ISSUE TITLE
qgis database - error working

### ISSUE THREAD

**Issue by Rscherer2087** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1132]
## Description

Page URL:

QGIS DATABASE IS LOCKED: THIS FILE IS A WAL - ENABLED DATABASE. IT CANNOT BE OPENED BECAUSE IT IS PRESUMABLY READ ONLY OR IN A RED ONLY DIRECTORY

**Comment by DelazJ** [comment]
Hi @Rscherer2087
I am afraid that nobody here knows what you are talking about. There is no context: what you were doing? what file type? where did you get this? what are your expectations (question, bug report)?... As you can see, there are too many gaps in your message.
Anyway... This repository is meant to address issues with QGIS website. Issues with Desktop should be clearly reported at https://github.com/qgis/QGIS/issues (with as much details as possible) and questions should be asked in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)).
Closing.
