### ISSUE TITLE
Qgis model review unattended

### ISSUE THREAD

**Issue by NicolasCadieux** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1141]
## Description

Hi,
It appears no one is reviewing or approving QGIS Models on the site.   https://plugins.qgis.org/models/?order_by=-upload_date&&is_gallery=true  

I have 3 models waiting to be approved since March the 10th (17 days agos) and the models are still not available to the public.  I tried emailing twice on the developers list but I still can't reach anyone.  I also tried sending an email to the site developer ItOpen, but I still have no response.  

Can someone help?
Thanks you very much
Nicolas Cadieux
 

Page URL:

**Comment by agiudiceandrea** [comment]
@NicolasCadieux, is this issue report still valid?

**Comment by agiudiceandrea** [comment]
@NicolasCadieux, is this issue report still valid?

**Comment by DelazJ** [comment]
I think it is good to close (https://lists.osgeo.org/pipermail/qgis-developer/2023-April/065690.html)
