### ISSUE TITLE
Download Version 3.0 for windows not working

### ISSUE THREAD

**Issue by henning410** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1145]
When I try to download QGIS 3.0 for windows, the download is not working. It starts, but is not doing any progress at all.
![image](https://user-images.githubusercontent.com/44315209/230089486-05bcf8b8-dcdc-4507-add6-4947008aa213.png)

I started at the same time downloading Version 3.28 LTR. This works!

**Comment by DelazJ** [comment]
@henning410 you meant 3.30 or 3.0?

**Comment by jef-n** [comment]
Which download did you actually get redirected to?
