### ISSUE TITLE
Error en la pestaña de escala Qgis 3.30.1

### ISSUE THREAD

**Issue by Danny-Vasco** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1146]
Saludos tengo un error en la pestaña de la escala de la página principal de Qgis, aparece recortada y cuando hago click  el programa después de unos segundos se cierra automáticamente.

![image](https://user-images.githubusercontent.com/91226131/230091030-178e50b2-d540-42a3-a511-0702127aa590.png)
![image](https://user-images.githubusercontent.com/91226131/230091297-bacdd36b-0e22-4f85-92d2-a76ab9c771c7.png)

**Comment by DelazJ** [comment]
@Danny-Vasco this repository is for QGIS web site. For issues with QGIS Desktop, please report at https://github.com/qgis/QGIS/issues (preferably in English - use an online translator if necessary). Thanks.
