### ISSUE TITLE
Plugin update issue

### ISSUE THREAD

**Issue by LScislowski** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1148]
Hi,
I have a problem with update my plugin. I try to add new file with plugin but I get window with information: 
*Gateway time-out Error code 504,
*plugins.qgis.org Host Error,
*What happened?  The web server reported a gateway time-out error,
*What can I do? Please try again in a few minutes.

I get information about errors in Console (Chrome DevTools):
*POST https://plugins.qgis.org/plugins/wody_polskie_wms/version/add/ 504 (Gateway Time-out)

I've been trying to update the plugin for a few days.
Can you help me?
Łukasz Ścisłowski

**Comment by rduivenvoorde** [comment]
Hi Łukasz,

I can at THIS moment (when logged in) just upload a plug to
https://plugins.qgis.org/plugins/add/
can you try that too?

You are using a script? Maybe there is something with the api endpoint (@timlinux ?)

**Comment by LScislowski** [comment]
Thank you for your very quick reply.
I also tried to update via https://plugins.qgis.org/plugins/add/ but the error is the same. I didn't use a script to update.

**Comment by LScislowski** [comment]
Thank you for your very quick reply.
I also tried to update via https://plugins.qgis.org/plugins/add/ but the error is the same. I didn't use a script to update.

***@***.***

**Comment by rduivenvoorde** [comment]
I'll sent an email to the dev list...

**Comment by nicogodet** [comment]
I just uploaded a plugin without issue. Could you retry @LScislowski  ?

**Comment by LScislowski** [comment]
[update error.pdf](https://github.com/qgis/QGIS-Website/files/11232278/update.error.pdf)

**Comment by LScislowski** [comment]
I've also tried on a different browser (Chrome, Edge) and different network infrastructure. Maybe it's a problem with my file? But my plugin file works when I install it directly in the program.

**Comment by nicogodet** [comment]
Could you share it here ?

**Comment by LScislowski** [comment]
[wody_polskie_wms_1_0_2.zip](https://github.com/qgis/QGIS-Website/files/11236681/wody_polskie_wms_1_0_2.zip)

I would like to update my old plugin (v.1.0.1). I shared my plugin (v.1.0.2).

**Comment by timlinux** [comment]
@dimasciput could you take a look please?

**Comment by dimasciput** [comment]
Hi @LScislowski,

It's because the homepage URL in the metadata.txt cannot be reached. Can you please update the link first?

**Comment by LScislowski** [comment]
I changed my homepage URL and it works. I'm waiting for approval now.
Thank you very much for your help.
