### ISSUE TITLE
Broken "Fix me" link for translation at the bottom of the pages

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1153]
1. Open a page on https://qgis.org, in a translated language
2. Go to the bottom of the page and cick on "Fix me" because you spotted a missing translation
3. At the best, you get in Transifex a page with ALL the strings to translate. It used to bring you to the resources filtered on the page you were reading online (much easier to translate/fix what you saw in published docs)
4. You can also try the "Translate page" link in the bottom left menu of the QGIS 3.28 docs pages. Same behavior.
5. The link now expects a md5 value of the file path in replacement of page name variable.

SO If you know how to calculate a md5 value of a string in a HTML template file, your help is more than welcome. Or if you have any idea how this Transifex URL works, welcome.

If you want more details, https://github.com/qgis/QGIS-Documentation/issues/8195

**Comment by rduivenvoorde** [comment]
What about leave it like this. Don't you think it is enough for translators to just be sent to Transifex?
I think they make it to complex now... (it was already a hassle years ago to make this work for all pages...)

There are apparently some libs needed:
https://stackoverflow.com/questions/1655769/fastest-md5-implementation-in-javascript
(but I haven't looked into this)

Note that the webpage/qgis.org still works for me! ?

**Comment by DelazJ** [comment]
Sorry @rduivenvoorde I forgot to send my reply
> What about leave it like this. Don't you think it is enough for translators to just be sent to Transifex?

Speaking for myself as a translator, no, it is not enough. Many translation sessions I do are triggered by an untranslated or wrongly translated string I came across while browsing docs or website. Getting directly to the page the issue lays on is much more convenient and time saver than having to filter the whole resources to find it.
I finally found a solution using Python for the docs repo (https://github.com/qgis/QGIS-Documentation/pull/8222). _For the website, well..._
> Note that the webpage/qgis.org still works for me! ?

what do you mean by `the webpage/qgis.org`?

**Comment by DelazJ** [comment]
This is fixed. Maybe it was some bug on tx side as I can't see any related changes in this repo...
