### ISSUE TITLE
plugin 

### ISSUE THREAD

**Issue by Chandumouli21** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1154]
i could not able to find the   plugin" add coordinates to point"

**Comment by agiudiceandrea** [comment]
@Chandumouli21, where did you find a reference to such "add coordinates to point" plugin? Have you tried to search in the QGIS Python Plugins Repository at https://plugins.qgis.org/? What should this plugin actually do in details?

**Comment by agiudiceandrea** [comment]
I think this issue report should be closed.
