### ISSUE TITLE
Donation page HTTPS Certificate is out of date

### ISSUE THREAD

**Issue by SolarDesalination** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1166]
I tried to donate via the website by clicking the donate website and my browser sent me a warning saying that the site is insecure and is not HTTPS.

**Comment by rduivenvoorde** [comment]
@SolarDesalination thanks for telling!

You are right, https://donate.qgis.org/ has (accidently) the certificate of https://hangelog.qgis.org

ping @timlinux @dimasciput

**Comment by dimasciput** [comment]
Hi @rduivenvoorde @SolarDesalination ,

The page is now fixed.

**Comment by rduivenvoorde** [comment]
Cool, thanks @dimasciput for the prompt actions!

Closing
