### ISSUE TITLE
Apple's system has been updated to OS X 10.9

### ISSUE THREAD

**Issue by tuojian** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#117]
Apple's system has been updated to OS X 10.9, the new version does not seem to be able to For OS X Snow Leopard, Lion & Mt Lion. When can the OS X10.9, look forward to. Thank you.

**Comment by rduivenvoorde** [comment]
Sorry to say, but this issuelist is only for website related issues.

As the QGIS builds are managed by William Kyngesburye, I think you should either keep your eyes on:  http://www.kyngchaos.com/software/qgis 
OR contact devs via the dev-mailinglist: http://www.qgis.org/en/site/getinvolved/mailinglists.html#qgis-mailinglists
OR one of the other contact possibilities, see http://www.qgis.org/en/site/forusers/support.html
