### ISSUE TITLE
Update MIERUNE LLC -> MIERUNE Inc.

### ISSUE THREAD

**Issue by Yfuruchin** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1171]
Could you please update the name in the "Sustaining Member" page from "MIERUNE LLC" to "MIERUNE Inc." ?

Page URL:
https://www.qgis.org/en/site/about/sustaining_members.html

Cf
https://www.mierune.co.jp/aboutus?lang=en

**Comment by andreasneumann** [comment]
Hi @Yfuruchin - thank you for the correction.

The sustaining memberships are generated from a database. I just corrected the entry in our database. In a couple of hours it should be updated in the website - there is a cronjob for regular exports from the DB for the website.

**Comment by Yfuruchin** [comment]
@andreasneumann 
Thank you for your prompt response. One thing I forgot to tell you, our official name of MIERUNE does not include lower case letters.


Mierune LLC -> MIERUNE INC.

 If this is not reflected in this update, please check again. Sorry for the double trouble, and thank you in advance for your patience m(_ _)m

**Comment by andreasneumann** [comment]
Done --> https://changelog.qgis.org/en/qgis/member/drvbrt/
