### ISSUE TITLE
Add a batch export KML function, it is best to load the folder directly, so that all the shp file is loaded in, one-time batch conversion KML. All names should be SHP FILE names.

### ISSUE THREAD

**Issue by xuxiaochun1268** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1176]
## Description
Add a batch export KML function, it is best to load the folder directly, so that all the shp file is loaded in, one-time batch conversion KML. All names should be SHP FILE names.

**Comment by DelazJ** [comment]
Hi @xuxiaochun1268 
You should report your request in the [application issue tracker](https://github.com/qgis/QGIS/issues).This repository is dedicated to [QGIS Website](https://qgis.org) issues, hence I'm closing.
Thanks.
