### ISSUE TITLE
No more "last updated on" information in pages footer

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1185]
Well, I'd have sworn there used to be an information in pages footer of their last update. Doesn't seem to display anymore. But as far as I can see, the conf.py parameter supposed to do that is still there and I couldn't find any related changes 🤔 🤔 🤔 

https://github.com/qgis/QGIS-Website/blob/e5dc45984dd2e68b9cd545fd069ef89682d35300/source/conf.py#L149-L153

**Comment by agiudiceandrea** [comment]
Using web.archive.org to view the previous version of the QGIS website pages, it looks like "Last updated on" has been always (at least in the latest 5 years) displayed only in the website home page, but not in other pages (as the Download page).

**Comment by agiudiceandrea** [comment]
See also; https://github.com/qgis/QGIS-Website/blob/facac32e179007008c479b7974c6b17901d6b6c5/themes/qgis-theme/page.html#L43-L48

**Comment by DelazJ** [comment]
Thanks for the investigation, @agiudiceandrea. I dreamt it then.
Sorry for the noise.

**Comment by rduivenvoorde** [comment]
Yeah, just for historical knowledge: because we wanted to use browser/cloudflare cache as much as possible, we deliberately did not change ALL pages (by changing the footer every day), but only the front page :-)
