### ISSUE TITLE
Bad CRS projection for AWS S3 raster file

### ISSUE THREAD

**Issue by searchant01** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1187]
## Description

I am adding a Raster layer from AWS S3 bucket file (.tif) , this Raster file shows (?) first in layer  window  with warning : no coordination system. After correct with the CRS (NAD83/16N) , the raster image is in wrong location.  However, the raster image is in right location when I added from local file instead of AWS S3.

**Comment by searchant01** [comment]
My QGIS version is 3.28

**Comment by agiudiceandrea** [comment]
@searchant01, this GitHub repository is about the QGIS website. Since the issue occurs using QGIS, please report the issue to the QGIS source code repository at https://github.com/qgis/QGIS.
