### ISSUE TITLE
Numeric scale error when print

### ISSUE THREAD

**Issue by Bearol** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#119]
I found that there is an error in the numeric scale in the "print composer" (composeur d'impression en français). For example, if we print with a scale of 1:20 000, the distances on the map are in reality around 1:15 000.

Thanks for your time.

**Comment by rduivenvoorde** [comment]
Hi Bearol,

here you can create issues for the QGIS website.

Issues in the composer (or QGIS), should be filed there.

See: http://www.qgis.org/en/site/forusers/support.html#issue-tracker

I'm closing this one here.
