### ISSUE TITLE
C++ API: missing "Inheritance graph" image in classes docs

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1193]
## Description

![image](https://github.com/qgis/QGIS-Website/assets/16253859/443b3c6e-c4fc-4452-8c17-10042ccb66a0)

...I don't remember if this is the right repository...

Page URL: https://api.qgis.org/api/master/classQgsGeometry.html

**Comment by DelazJ** [comment]
> ...I don't remember if this is the right repository

I think qgis/QGIS could be more suitable (there is an API-related bug reporting entry, the website is fed by changes in that repo,...)

**Comment by agiudiceandrea** [comment]
I think the issue somethink
g
