### ISSUE TITLE
Clarify instructions for QGIS download for OSX / Mac to bypass notarization issue

### ISSUE THREAD

**Issue by nickbearman** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1195]
## Description

When installing QGIS on a Mac / OSX / MacOS you have to bypass the notarisation issue by using Control-Click and choose open on the menu. This is what we have on the page currently:

https://qgis.org/en/site/forusers/download.html

![V0fJhpEDFByVjtW1](https://github.com/qgis/QGIS-Website/assets/6410645/2afdc9e6-bfb9-4407-8b00-440b530d6a84)

When working with novice users it often confuses them. I understand that QGIS is looking to notarise the installer to completely bypass the issue and I am not sure what the current status of this is. 
https://github.com/qgis/QGIS-Enhancement-Proposals/issues/218 
https://github.com/qgis/QGIS/issues/32167

In the mean time, I suggest updating the text on the website. I am working with a client who needed to install QGIS on a Mac, and got confused. I explained what need to be done, and asked them what changes they suggested to clarify this. 

He suggested this:

<img width="634" alt="image002" src="https://github.com/qgis/QGIS-Website/assets/6410645/6301ebbb-7585-4ef0-aed5-2dacaf3fef9f">

"Were it me, I’d probably format it slightly differently (I’m drawn to the big green button and not to the stuff below it, personally). Quick mock-up below of what would probably made me read it, with some slight change on the focus of the wording. 

Hope this is useful; apologies if this is a bit OTT but I did a big UX project on exactly this sort of thing for a holiday rental business previously, so it’s sort of ingrained in me!"

Can we make these changes? What do you think?

Best wishes,
Nick.

**Comment by agiudiceandrea** [comment]
Please see also https://lists.osgeo.org/pipermail/qgis-user/2023-November/053612.html

**Comment by agiudiceandrea** [comment]
Latest changes
![image](https://github.com/qgis/QGIS-Website/assets/16253859/e16e4357-5aa3-4e18-8db1-ee37fcfa1587)
https://github.com/qgis/QGIS-Website/commit/5ba991c56d58bf401489c2b8c3484c7354b9c930

**Comment by nickbearman** [comment]
Thanks @agiudiceandrea !

Is it possible to move the text above the button? People tend to read down a page, so will probably click the big green button and may not even see the text!

**Comment by nickbearman** [comment]
Also, how about tweaking the text slightly. I'm trying to put the most important stuff first:

On first launch, please control-click on the icon and choose Open from the context menu, after which a confirmation dialog is shown and you need to click the Open button. This is needed because QGIS is not yet notarized as required by macOS security rules. macOS High Sierra (10.13) or newer is required.

**Comment by agiudiceandrea** [comment]
Another related issue report: https://github.com/qgis/QGIS/issues/55663.
