### ISSUE TITLE
Home page banner not updated for QGIS 3.34 release

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1198]
## Description

Page URL: https://qgis.org/en/site/index.html

**Comment by rduivenvoorde** [comment]
Ah, Juergen was faster: https://github.com/qgis/QGIS-Website/commit/5b11a40d8a63830d54f69e699bb1fd855fb0e9b5
