### ISSUE TITLE
The "Download QGIS 3.34" link for macOS points to QGIS 3.32.3 instead of QGIS 3.34.0

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1199]
## Description

Clicking on [Download QGIS 3.34](https://qgis.org/downloads/macos/qgis-macos-pr.dmg) incorrectly makes the users to download the QGIS 3.32.3 installer instead of QGIS 3.34.0.

This is a recurring issue, due to failing builds of macOS installers. https://github.com/qgis/QGIS-Mac-Packager/issues/175

I suggest to avoid to have a "Download QGIS 3.34" link in the macOS section until there is actually a QGIS 3.34 installer available for macOS: see also https://github.com/qgis/QGIS-Website/issues/925.

See also https://lists.osgeo.org/pipermail/qgis-user/2023-November/053628.html.

Page URL: https://qgis.org/en/site/forusers/download.html#mac

**Comment by DrVesuvius** [comment]
Any updates on this? How can one tell when the latest version will be up?

**Comment by agiudiceandrea** [comment]
@DrVesuvius, waiting for the issue to be fixed you will find at https://download.qgis.org/downloads/macos/pr/?C=M;O=D the QGIS 3.34.0 .dmg installer when available. You can also check if a 3.34.0 installer is available looking at the failing and passing builds at https://github.com/qgis/QGIS-Mac-Packager.

**Comment by agiudiceandrea** [comment]
Fixed by https://github.com/qgis/QGIS-Website/commit/5ba991c56d58bf401489c2b8c3484c7354b9c930.

**Comment by agiudiceandrea** [comment]
@DrVesuvius, the dmg installer for QGIS 3.34.0 is currently available.

**Comment by DrVesuvius** [comment]
great, thanks!
