### ISSUE TITLE
Bitcoin for donations

### ISSUE THREAD

**Issue by Matthias84** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#120]
www.bitcoin.org is also an OpenSource project that is dedicated to an distributed open payment system. As Paypal had some very bad politics (Wikileaks, Crowdfunding, ...) and also other commercial providers have higher fees, I like to suggest to make use of BTCs for donations as full electronic comfortable way to donate.

**Comment by rduivenvoorde** [comment]
@Matthias84 we do not have a BT-account, and do not have knowledge about this. We also tried other micropayment systems before, but often the time to implement/create accounts did not make up for the few payments we got from these.
But if you give clear instructions and a way to make real money from it, you could try to sent this info and this request to the PSC-mailing list (or just psc@qgis.org)....
Will close this now to clean up the issue list some more.
