### ISSUE TITLE
diferencias en la medidas al exportar a dxf

### ISSUE THREAD

**Issue by andrestoralcona** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1206]
hace poco que estoy aprendiendo a usar Qgis, el dia de hoy exporte unos resutados de una interseccion vectorial teniendo precaucion de definir bien el sistema de proyeccion cartografico.

Al comprarar las areas y medidas tanto en autucad  como en qgis presentan diferencias, en porcentaje estamos en menos de 0.5% de diferencias, pero creo que no debieran de existir estas diferencias o ser mas imperceptibles. Otra cosa, existe alguna manera de que los poligonos que exportan NO sean achurados ?, esto es un problema en autocad ya que le asignan mucho peso en video para visualizar los resultado, ideal seria que solo generara polilineas cerradas, lo mas simple posible.

Y lo ultimo, me es imposible instalar el complemento para trabajar con imagenes satelitales RGB, al parecer esta instalacion es mas compleja y requiere otras instalaciones iniciales, Me podrian ayudar porfavor, gracias Andres de Chile

**Comment by DelazJ** [comment]
Hi Andres,
This repository is dedicated to issues related to the [main website](https://qgis.org) of QGIS project.
Please ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)), with more detailed information on data (e.g. CRS in use) and steps you follow.
Thanks.
