### ISSUE TITLE
Display number of selected features in layer tree

### ISSUE THREAD

**Issue by sivansakthi** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1216]
Display number of selected features in layer tree

![image](https://github.com/qgis/QGIS-Website/assets/92709125/ebb8e815-8923-40a4-a1fa-8faa41e132cc)

Display source path like ArcMap as shown in below screen capture

![image](https://github.com/qgis/QGIS-Website/assets/92709125/93f2e739-7750-4bc7-b6de-36147d71b581)

**Comment by DelazJ** [comment]
Hi @sivansakthi
This is a feature request related to the application, hence should be opened at https://github.com/qgis/QGIS/issues. Check first that the same request does not already exist.
This repository is dedicated to [QGIS Website](https://qgis.org) issues, hence I'm closing.
Thanks.
