### ISSUE TITLE
[FEATURE] Add a roadmap

### ISSUE THREAD

**Issue by m-kuhn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#122]
Now that we have a fixed release cycle, it would be nice to publish this on the webpage (feature freeze/translation window/release date)

**Comment by rduivenvoorde** [comment]
A link to

http://qgis.org/en/site/getinvolved/development/index#road-map

is here

http://qgis.org/en/site/getinvolved/index.html

If one wants to have more info there, please add.

If ok, plz close.

**Comment by m-kuhn** [comment]
oh cool

sorry for the noise
