### ISSUE TITLE
qgis is not working with Window home 11

### ISSUE THREAD

**Issue by maferly19** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1226]
Hi, my QGIS stopped completely working on my WindWos Home 11, and i have tried all the ways, but it seems to be still not working, not even opening.

Could you please get in touch with me  for further support on that?

**Comment by jef-n** [comment]
Not a website issue.

**Comment by maferly19** [comment]
Ah so can I get in touch with someone from the technical department to help me out with this?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DelazJ** [comment]
> Ah so can I get in touch with someone from the technical department to help me out with this?

Hi @maferly19
QGIS is a community driven Free and Open Source project. There is no such a technical department but you can either hire a developer to help you fix issues or ask the community (see [support channels](http://qgis.org/en/site/forusers/support.html)).
In both cases, you'll need to provide more details about your environment and what you actually tried (version of QGIS, msi file or osgeo4w download, actions done, error messages if any...)
