### ISSUE TITLE
doc page in german missing

### ISSUE THREAD

**Issue by rkrucker** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#123]
The german version of qgis works very nicely. However, if one wants to access the doc page through the help menu (or presses f1), he is directed to a non-existing link.
Off course a german help page would be perfect, but in the meantime I think that a direct to the english version of the doc page should take place.

**Comment by rduivenvoorde** [comment]
hi, 
which version are you running? 

Because for what I know in recent 2.0 we point to this url:
http://docs.qgis.org/2.0/en/docs/user_manual/
for which we created a rewrite rule (in short: it is working here).

Which url do you see?

**Comment by rkrucker** [comment]
Hi
thanks for your reply. Im running version 2.0.1 and the url is:
http://docs.qgis.org/2.0/html/de/docs/user_manual/
so it seems to point to a german version which doesnt exist.
kind regards

Am 10.12.2013 23:56, schrieb Richard Duivenvoorde:

**Comment by rduivenvoorde** [comment]
ok, I added a temporarily redirect. So at  least the link above is fixed now.

**Comment by rkrucker** [comment]
Perfect, thanks alot, have a nice day
Am 11.12.2013 09:15, schrieb Richard Duivenvoorde:
