### ISSUE TITLE
Variable |yeartag| doesn't seem to render on page

### ISSUE THREAD

**Issue by DiGro** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1237]
## Description
Variable |yeartag| doesn't seem to render on page.

On the page getinvolved/faq/index the variable |yeartag| doesn't seem to render.

Line 85 / 91 and a few more  -->  on the page on the website it is rendered as %Y

Page URL: https://www.qgis.org/nl/site/getinvolved/faq/index.html
                 https://www.qgis.org/it/site/getinvolved/faq/index.html
                 https://www.qgis.org/de/site/getinvolved/faq/index.html

**Comment by agiudiceandrea** [comment]
@DiGro @jonnyforestGIS @rduivenvoorde, looking at the archived page via https://web.archive.org/, it looks like the functionality introduced with https://github.com/qgis/QGIS-Website/pull/810 has been broken in a date between 8th and 28th of September 2022. The issue has been probably introduced by https://github.com/qgis/QGIS-Website/commit/7f0cbe674549dfe9db84b6fa69e60f0553672379#diff-7fb09d9c93c5b9e807628c723d479e34bb753665a1cb1cbc1c3b09e4768789a5R221

Proposed patch: https://github.com/qgis/QGIS-Website/pull/1239.
