### ISSUE TITLE
Docs for ‘QGIS testing’. Visit http://docs.qgis.org for QGIS 2.0 docs and translations.

### ISSUE THREAD

**Issue by m-kuhn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#124]
If one goes to the [User Guide](https://qgis.org/en/docs/user_manual/preamble/preamble.html), the text

> Docs for ‘QGIS testing’. Visit http://docs.qgis.org for QGIS 2.0 docs and translations.

appears on top.

Issues
- The styling does not match the styling of the rest of the page (sorry to say, but it looks terribly out of place)
- Even worse, the link sends you back to the documentation section where the first link  (User Guide/Manual) brings you back to the affected documentation. There is a link further down the page (in the "Note"-Box), which brings you to a good page.

To fix this:
- The top-most link on the documentation page should point to a stable user guide.
- The styling of the warning box should be adjusted to suit the look-and-feel of the rest of the site.

**Comment by rduivenvoorde** [comment]
Mmm, not sure what happened. The building of the website actually checks out branch 2.0.

But apparently one of the commits in master is merged into this branch :-(
https://github.com/qgis/QGIS-Documentation/commit/a562a2959c6788dab29fcddd87fad577e5d5cb31
is the commit in which after branching from master, all 'this is testing' messages are brought back into testing.
But apparently I or somebody else merged these back into 2.0 too....

Can I remove this commit (from 2.0 only)?

**Comment by rduivenvoorde** [comment]
I do not understand your problem with the styling. Does it look different from other pages? If so can you add a screenshot?

**Comment by m-kuhn** [comment]
`git revert a562a29` will remove it from your current working branch.

Concerning the styling I attached a screenshot. It's just plain red with no shadows or gradient or a reduce saturation like all the other colors on the page.
Instead of this I would recommend to e.g. have something like the Note on this page https://qgis.org/en/docs/index.html but with a red exclamation mark icon.

![disclaimer](https://f.cloud.github.com/assets/588407/1731425/7eb1bf8a-6306-11e3-8188-a9c32f14c383.png)

**Comment by rduivenvoorde** [comment]
ah, ok clear. I agree with you know.

I think you were talking about the 'index page' of the documentation. And now would also agree on that too. The first three menu items have all a nice mondern html landing page while docs have their own classical rst page.... We can fix that also

**Comment by rduivenvoorde** [comment]
problem is that this 'disclaimer' not as easy to style as the admonitions, because of the way they are inserted into the text.
I've styled them now like this (top is new, middle is normal admonition, bottom is old)

![screenshot from 2013-12-14 12 41 16](https://f.cloud.github.com/assets/731673/1748340/1bc4a300-64b5-11e3-87f8-8403e967b7f2.png)

Will close this one for now, plz reopen if not satisfied
