### ISSUE TITLE
QGIS user group membership application form links broken 404

### ISSUE THREAD

**Issue by geomenke** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1240]
## Description
The links to all three membership application forms (German, English & French) are broken. These are under the **Organization** heading.

When one clicks on any of these links you get a 404 page not found error. These are the 3 links:

- german: https://www.qgis.ch/de/verein/beitrittserklaerung
- english: https://www.qgis.ch/en/association/qgis-usergroup-switzerland-membership-application-form
- french: https://www.qgis.ch/fr/association/declaration-d2019adhesion

Page URL: https://qgis.org/en/site/forusers/usergroups.html#qgis-usergroups

**Comment by andreasneumann** [comment]
oh - sorry about that. The Swiss QGIS user group web page was re-organized. I will provide a fix to the new pages this weekend.

**Comment by andreasneumann** [comment]
Fixed in https://github.com/qgis/QGIS-Website/commit/8f49c82cc834d7575f2f60779157904182eb940c

Unfortunately, there is no English version anymore ... we decided to maintain only 2 languages for the qgis-ch webpage.
