### ISSUE TITLE
Qgis plugins repository web page not working

### ISSUE THREAD

**Issue by BioMeg** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1246]
When I try to access the qgis plug-ins repository I am getting a gateway timeout error. 

plugins.qgis.org is reporting a host error.

It says try again in a few minutes but I have been trying all day and nothing has improved.

**Comment by martinkean** [comment]
Still nothing from https://plugins.qgis.org/plugins/, also the plugin Installer in QGIS the app is also not working, gateway timeout due to the server being down. This is a major problem, is there fix date for this please?

**Comment by agiudiceandrea** [comment]
@martinkean @BioMeg please see https://lists.osgeo.org/pipermail/qgis-user/2024-May/054439.html

**Comment by agiudiceandrea** [comment]
@BioMeg @martinkean does the issue still occur?

**Comment by martinkean** [comment]
@agiudiceandrea @BioMeg [https://plugins.qgis.org/plugins/](https://plugins.qgis.org/plugins/) seems to working fine now! Thank you!

**Comment by shawndegroot** [comment]
i am having an issue where on the plugin manager, under "settings", the QGIS Official Plugin Repository is listed but its status is "unavailable". i am able to install plugins via from zip, but then they don't seem to work. For example i am able to download the QuickMapServices plugin via zip, but then when i load the OSM Standard layer as a basemap, nothing shows up on my QGIS console.

**Comment by agiudiceandrea** [comment]
> when i load the OSM Standard layer as a basemap, nothing shows up on my QGIS console.

@shawndegroot this means that your system or QGIS on your system may have some issue connecting to Internet.

**Comment by shawndegroot** [comment]
ok, thanks for your help! Problem solved, had SOCKS proxy checked in my wifi settings.
