### ISSUE TITLE
[qgis2.0] [merge features ] [take attributes from selected featur ] failed

### ISSUE THREAD

**Issue by kar98k** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#125]
[take attributes from selected featur ]  dose not work , need fill the merge attributes one by one manully

**Comment by rduivenvoorde** [comment]
@kar98k this is the issue tracker for errors in the website. If you find issues in QGIS application, please go to:

http://hub.qgis.org/issues/

plz read http://hub.qgis.org/wiki/quantum-gis/Bugreports how to create an account.

Going to close this issue, plz reopen if nessecary
