### ISSUE TITLE
Regarding Checking loops and connectivity

### ISSUE THREAD

**Issue by adarshshet** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#126]
Hi,

Is there any way to create geometry and trace lines and check for loops in QGIS.

With Regards,
Adarsh

**Comment by rduivenvoorde** [comment]
Hi Adarsh,
this bug tracker is only for website related issues.
please consult http://qgis.org/en/site/forusers/support.html 
best is to ask on the user mailinglist or StackExchange
