### ISSUE TITLE
Problem with download page

### ISSUE THREAD

**Issue by katagen** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1264]
The download page www.qgis.org/download/ points to www.qgis.org

So it is impossible to go to the main installers page.

**Comment by jmckenna** [comment]
In the mean time, here are some places to download from:
- https://download.qgis.org/downloads/
- https://download.osgeo.org/qgis/

**Comment by jmckenna** [comment]
The issue seems fixed now
