### ISSUE TITLE
Qgis fechando apos usar o LF tools

### ISSUE THREAD

**Issue by TercioNovais** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1266]
Quando estou utilizando a função de fechar polígono com azimutes de distancias pelo LF Tools, apos fazer todo o procedimento quando vou fazer alteração ou salvar a shape o Qgis da o erro : 

Windows fatal exception: access violation
Current thread 0x00002158 (most recent call first):

![print](https://github.com/user-attachments/assets/4004f673-dc31-43b7-aacf-6af39e7dee75)

alguem pode me ajudar?

**Comment by rduivenvoorde** [comment]
Closing, becaus this is NOT the issue-tracker for the QGIS application, but for the (old) website.

If this issue only pops up when you use the LF Tools plugin, it is better to create an issue there:
https://github.com/LEOXINGU/lftools/issues

But make sure you describe exactly what you do (with what kind of data), so the developers can try to reproduce your problem.
