### ISSUE TITLE
dead links in pyqgis cookbook 

### ISSUE THREAD

**Issue by warrieka** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#127]
On page:
http://www.qgis.org/en/docs/pyqgis_developer_cookbook/network_analysis.html#building-graph

links to network analyses api-documetation are dead:
http://qgis.org/api/api/classQgsGraphBuilder.html , http://qgis.org/api/api/classQgsLineVectorLayerDirector.html ,
http://qgis.org/api/api/classQgsGraph.html ...

**Comment by m-kuhn** [comment]
Fixed in https://github.com/qgis/QGIS-Documentation/commit/fcac745bd3ac3935f11603ab7861ee6483e7fa86

Thank you very much
