### ISSUE TITLE
Bad link to changelog

### ISSUE THREAD

**Issue by m-kuhn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#129]
On the page:
http://qgis.osgeo.org/en/docs/user_manual/preamble/whats_new.html

The link to the changelog points to:
http://changelog.linfiniti.com/version/1/

which only says "not found" :(

**Comment by rduivenvoorde** [comment]
mmm, it was there :)

if @timlinux  can tell me where it is now, I'll update the link

**Comment by dassau** [comment]
I updated it in the docs for 2.0 branch and current master

**Comment by mach0** [comment]
Seems that the numbering changed ..

http://changelog.linfiniti.com/qgis/version/200/
http://changelog.linfiniti.com/qgis/version/20http://changelog.linfiniti.com/qgis/version/200/
1/

depending on which versions changelog you want to have ..

**Comment by timlinux** [comment]
Sorry we made some improvements to the site which unfortunately included
changing the URL scheme.

Regards

Tim

On Mon, Jan 13, 2014 at 11:03 AM, Werner Macho notifications@github.comwrote:

> Seems that the numbering changed ..
> 
> http://changelog.linfiniti.com/qgis/version/200/
> http://changelog.linfiniti.com/qgis/version/20<
> http://changelog.linfiniti.com/qgis/version/200/>
> 1/
> 
> depending on which versions changelog you want to have ..
> 
> On Mon, Jan 13, 2014 at 9:58 AM, Richard Duivenvoorde <
> notifications@github.com> wrote:
> 
> > mmm, it was there :)
> > 
> > if @timlinux https://github.com/timlinux can tell me where it is now,
> > I'll update the link
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/qgis/QGIS-Website/issues/129#issuecomment-32152945>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/qgis/QGIS-Website/issues/129#issuecomment-32153217
> .

## 

# Tim Sutton - QGIS Project Steering Committee Member

Visit http://linfiniti.com to find out about:
- QGIS programming services
- GeoDjango web development
- FOSS Consulting Services
  Skype: timlinux Irc: timlinux on #qgis at freenode.net
  ==============================================
