### ISSUE TITLE
I have an error in QGIS with the plugin Openlayers

### ISSUE THREAD

**Issue by greciaechenique** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#136]
Hi everybody, I have a problem with QGIS 2.0 because I installed the plugin Openlayers succesfully, but when I try to add a layer, it appears this message:

An error has occured while executing Python code

Traceback (most recent call last):
File "C:\Users\Usuario/.qgis2/python/plugins\openlayers_plugin\openlayers_plugin.py", line 50, in addLayer
self.plugin.addLayer(self)
File "C:\Users\Usuario/.qgis2/python/plugins\openlayers_plugin\openlayers_plugin.py", line 204, in addLayer
layer = OpenlayersLayer(self.iface, self.coordRSGoogle, self.olLayerTypeRegistry)
File "C:\Users\Usuario/.qgis2/python/plugins\openlayers_plugin\openlayers_layer.py", line 64, in init
self.page = OLWebPage()
File "C:\Users\Usuario/.qgis2/python/plugins\openlayers_plugin\openlayers_layer.py", line 38, in init
proxy = getProxy()
File "C:\Users\Usuario/.qgis2/python/plugins\openlayers_plugin\tools_network.py", line 42, in getProxy
proxy.setPort(settings.value("/proxyPort", 10, type=int))
TypeError: unable to convert a QVariant of type 10 to a QMetaType of type 2

Versión de Python:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

Versión de QGIS:
2.0.1-Dufour Dufour, d94c044

Ruta de Python: ['C:/PROGRA~1/QGISDU~1/apps/qgis/./python/plugins\processing', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python', 'C:\Users\Usuario/.qgis2/python', 'C:\Users\Usuario/.qgis2/python/plugins', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python/plugins', 'C:\PROGRA~1\QGISDU~1\bin\python27.zip', 'C:\PROGRA~1\QGISDU~1\apps\Python27\DLLs', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISDU~1\bin', 'C:\PROGRA~1\QGISDU~1\apps\Python27', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg', 'C:\PROGRA~1\QGISDU~1\apps\qgis\python\plugins\fTools\tools']

Please, I need help!!!!

Thanks for your attention.

Grecia.

**Comment by m-kuhn** [comment]
Hi @greciaechenique 

This bugtracker is for the QGIS website only and not for the software QGIS or a plugin. Please submit a bug to the tracker referenced here: http://plugins.qgis.org/plugins/openlayers_plugin/ so the people in charge will notice this problem.

Can somebody with appropriate rights please close this bug.
