### ISSUE TITLE
Make sure search is properly setup for i18n

### ISSUE THREAD

**Issue by jj0hns0n** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#15]

**Comment by pcav** [comment]
Do you mean search should work across $lang? IMHO better if every lang is separated

**Comment by rduivenvoorde** [comment]
@jj0hns0n please elaborate

search will be working for i18n I think. Because we will have real separate copies of the website for every language. So if you you search when you are in NL you will search in the NL website. If in another lang you will search that site.

**Comment by jj0hns0n** [comment]
Want to make sure the strings used in the search pages themselves are setup for i18n. Looks like some are in js and perhaps not translate able. 

+1 on separate search per Lang, that's how it works now.

**Comment by pcav** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Il 31/08/2013 15:26, Jeffrey Johnson ha scritto:

> Want to make sure the strings used in the search pages themselves are setup for i18n.
> Looks like some are in js and perhaps not translate able.

this may well be the case; perhaps also text in links, have to check.

---

Paolo Cavallini - Faunalia
www.faunalia.eu
Full contact details at www.faunalia.eu/pc
Nuovi corsi QGIS e PostGIS: http://www.faunalia.it/calendario
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.14 (GNU/Linux)
Comment: Using GnuPG with Icedove - http://www.enigmail.net/

iEYEARECAAYFAlIiH5MACgkQ/NedwLUzIr7P0wCeMrUdQP6AgnDekN+PnJC3McbW
8X0AnjOxiBi/siubt0w43m6+Pz5FCNin
=aUE7
-----END PGP SIGNATURE-----

**Comment by mach0** [comment]
_push_ still valid? to me everything seems to work fine as it is now ..

**Comment by rduivenvoorde** [comment]
Yep, I think it can be closed
