### ISSUE TITLE
download 2.01 and 2.2

### ISSUE THREAD

**Issue by anvalanz** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#151]
the file https://github.com/qgis/QGIS-Website/blob/master/i18n/it/LC_MESSAGES/site/forusers/download.po
is not updated
the italian version refers to version 2.01 and the english version refers to version 2.2

**Comment by rduivenvoorde** [comment]
![screenshot from 2014-03-04 13 45 01](https://f.cloud.github.com/assets/731673/2321048/d5e8c10c-a39a-11e3-9c42-cc0ecc97c690.png)

On QGIS.org http://qgis.org/it/site/forusers/download.html is translated in my browser, see screendump above.
Are you looking to a cache version in your browser?

The file in github (download.po), is only a backup and not to be used for translations. 

We translate via transifex, and the strings for the page:
http://qgis.org/it/site/forusers/download.html
can be found here: 
https://www.transifex.com/projects/p/qgis-website/viewstrings/#it/sphinx/17319657
