### ISSUE TITLE
QGIS Cloud

### ISSUE THREAD

**Issue by JohnStudley** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#160]
I am trying to upload about ten GIS layers from my notebook to QGIS Cloud but I keep running into problems - I am not sure if there are data size restrictions or not but the uploader just spins or crashes

**Comment by rduivenvoorde** [comment]
Hi John,
this is the issuetracker for the QGIS Website (qgis.org). Please contact qgiscloud for help on that: http://www.qgiscloud.com/
