### ISSUE TITLE
Modifying shapefile into QGIS 2.2 seems OK, but it is not?...

### ISSUE THREAD

**Issue by ilikeqgis** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#161]
Hello,

It is the first time that i write to you... but today, i have a problem with ESRI Shapefile created inside QGIS, modified inside, because loaded inside is different of loaded inside another program : BlueKenue version 3.1.3 (you can download it here: https://www.nrc-cnrc.gc.ca/eng/solutions/advisory/blue_kenue_index.html )

Inside QGIS 2.2 Valmeira, i have drawn a polyline and save it.
After, i have added one node between 2 others and move this node to the north.
When i look it inside QGIS, it seems OK but...

When i use BlueKenue, i see the old draw with the new draw...

Any Solutions?

In Python, i have tried this:
        driver = ogr.GetDriverByName("ESRI Shapefile")
        infilename = "C:\BlueKenue_test\essai.shp"
        datasource = driver.Open(infilename, 1)
        layer = datasource.GetLayer()
        datasource.ExecuteSQL('REPACK ' + layer.GetName())
But i optained no change...

Then, I used the function:
ogr2ogr -f "ESRI Shapefile" temp.shp essai.shp
ogr2ogr -f "ESRI Shapefile" -overwrite essai.shp temp.shp

And the result was, is and seems OK when i reload essai.shp inside QGIS and BlueKenue!!!

Can you modify something inside QGIS to resolve this problem? Or can you propose me a solution in Python?...

Thanks a lot for your GIS solution,
Olivier ATHIMON (a french QGIS-User)
![qgis_2p2_valmeira_here_essai_shp_created_modified_and_loaded_inside_qgis_seem_ok_but_it_is_not](https://cloud.githubusercontent.com/assets/7483093/2874199/8b5fc6f0-d3db-11e3-9722-8b2d84942f1b.jpg)
![same_file_essai_shp_when_i_load_it_inside_bluekenue_3p1p3_i_have_old_and_new_draw](https://cloud.githubusercontent.com/assets/7483093/2874198/8b5c5ac4-d3db-11e3-8080-7bb82056ebb0.jpg)

**Comment by rduivenvoorde** [comment]
sorry, this is the issuetreacker for qgis website. Please (re)ask your question on the developers emailinglist. See http://qgis.org/en/site/forusers/support.html
There is also a french speaking community forum: http://georezo.net/forum/viewforum.php?id=55
