### ISSUE TITLE
Features page content is off topic / would be duplicate of docs

### ISSUE THREAD

**Issue by anitagraser** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#169]
The features page http://qgis.org/en/site/about/features.html#qgis-desktop actually covers the different applications developed within the qgis project but not qgis features.

If the features page would cover what the title suggests, it would duplicate http://docs.qgis.org/2.2/en/docs/user_manual/preamble/features.html. Maybe it should be emptied and just link to the docs.

**Comment by m-kuhn** [comment]
How about moving the page about/features.html to something like about/products.html?

**Comment by anitagraser** [comment]
+1 for moving. Not sure if "products" is the best term, maybe "applications"? The desktop application, server application, ...?
