### ISSUE TITLE
Add Sponsors to footer using snippet template

### ISSUE THREAD

**Issue by jj0hns0n** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#17]
The sponsors can be shown _at all times_ in the footer. This may not contain all sponsors, but new and big ones and a link to all of them. This should be able to be optionally included by using a snippet template.

**Comment by rduivenvoorde** [comment]
Tim, Paolo.

only on the website part isn't it? Not on documentation page?

Would be nice if this could be a separate template html file. Then we can do a conditional include in the layout.html

**Comment by pcav** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Il 31/08/2013 07:34, Richard Duivenvoorde ha scritto:

> only on the website part isn't it? Not on documentation page?

apparently not: http://qgis.org/en/sponsorship.html

> Would be nice if this could be a separate template html file. Then we can do a
> conditional include in the layout.html

beware that includes AFAIK are not translatable

---

Paolo Cavallini - Faunalia
www.faunalia.eu
Full contact details at www.faunalia.eu/pc
Nuovi corsi QGIS e PostGIS: http://www.faunalia.it/calendario
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.14 (GNU/Linux)
Comment: Using GnuPG with Icedove - http://www.enigmail.net/

iEYEARECAAYFAlIhhIAACgkQ/NedwLUzIr4JBQCgp9XxOmn0NVoo/US0Ut55Lscr
RqoAn2M/D3ydEVLUvmYZoCeBwvQGev8b
=JLcJ
-----END PGP SIGNATURE-----

**Comment by jj0hns0n** [comment]
@rduivenvoorde can make a small snippet template for this to optionally include and then link to the full sponsors page.

**Comment by jj0hns0n** [comment]
@pcav I think we have it setup such that they are now, but we will verify.

**Comment by rduivenvoorde** [comment]
ok, we added sponsor images to frontpage and moved governance pages (with sponsorship text) into the website, making them translatable.
