### ISSUE TITLE
Donations page should be merged with Get involved

### ISSUE THREAD

**Issue by anitagraser** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#170]
http://qgis.org/en/site/getinvolved/donations.html and http://qgis.org/en/site/getinvolved/index.html already share some introduction text as well as the "get involved" heading. On first sight, it is easy to mistake the donations page for the get involved page. Also, the donations page looks like a top-level page but it cannot be reached via the main menu at the top which makes navigation difficult.
Additionally, the donations page lacks information for sponsors, which is at least linked from the get involved page.

**Comment by pcav** [comment]
Agreed, thanks Anita.

On 23 maggio 2014 19:20:53 CEST, anitagraser notifications@github.com wrote:

> http://qgis.org/en/site/getinvolved/donations.html and
> http://qgis.org/en/site/getinvolved/index.html already share some
> introduction text as well as the "get involved" heading. On first
> sight, it is easy to mistake the donations page for the get involved
> page. Also, the donations page looks like a top-level page but it
> cannot be reached via the main menu at the top which makes navigation
> difficult.
> Additionally, the donations page lacks information for sponsors, which
> is at least linked from the get involved page. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/qgis/QGIS-Website/issues/170

## 

http://faunalia.eu/

**Comment by anitagraser** [comment]
I've restructured the pages. The landing page of qgis.org now links to get involved and from there, the visitor can find both a link to the list of current sponsors/donors as well as a link to the donations page with information about how to donate to the project.
