### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by nothinglimited** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#171]
404 Not Found:

http://www.qgis.org/en/docs/user_manual/index.html

http://www.qgis.org/en/docs/gentle_gis_introduction/index.html

**Comment by nothinglimited** [comment]
These links are on 
http://www.qgis.org/en/site/forusers/index.html

**Comment by rduivenvoorde** [comment]
thanks for noting!
