### ISSUE TITLE
English error in about page

### ISSUE THREAD

**Issue by petebrew** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#175]
The English in section: Features on the following page needs rewording:
http://qgis.org/en/site/about/index.html

Original:
QGIS provides a continously grow-fluiding number of capabilities provided by core functions and plugins. You can visualize, manage, edit, analyse data, and compose printable maps. Get a first impression with a more detailed feature list. 

Suggested:
The capabilities of QGIS are continuously expanding, provided by core functions and plugins.  You can visualize, manage, edit, analyse data, and compose printable maps. Get a first impression with a more detailed feature list.

**Comment by m-kuhn** [comment]
Fixed in 49411a2e
I hope this is also ok for English speakers. Or is the solution by @petebrew better? (I am not a native speaker)
