### ISSUE TITLE
Dead links in page "For users"

### ISSUE THREAD

**Issue by raunilillemets** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#183]
In page http://www.qgis.org/en/site/forusers/index.html#docs,
links 
- "Read QGIS Documentation" -> http://docs.qgis.org/2.4/en/docs/user_manual/index.html
- "A Gentle Introduction to GIS" -> http://docs.qgis.org/2.4/en/docs/gentle_gis_introduction/index.html

are dead.

**Comment by rduivenvoorde** [comment]
ok, thanks for noting.

fixed by redirecting to 2.2 docs (as 2.4 docs are not there yet)
