### ISSUE TITLE
Is this an installation problem?

### ISSUE THREAD

**Issue by Robotuner** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#184]
Hi, I'm just starting to look at QGIS.  Installed on Win8 x64 machine.  When I start QGIS from the "QGIS Desktop2.4.0" icon on my desktop, I get:
Runtime Error!
Program: C:\Program~1QGISCH~1\bin\qgis-bin.exe
R6034
An application has made an attempt to load the C runtime library incorrectly.  Please contact the application's support team for more information.

If I ignore it, QGIS appears to open successfully.  The message appears even if I run as administrator.

Thanks.

**Comment by angelicata** [comment]
I'm trying to download the new version 2.4.0 but or just download OSGEO and MSYS Chugiak (without the application QGIS) or download the 2.5 version.

**Comment by rduivenvoorde** [comment]
@Robotuner sorry, this is the issue tracker for website related problems, try to find a solution via
http://qgis.org/en/site/forusers/support.html

@angelicata on http://qgis.org/en/site/forusers/download.html you can either download a classical installer (msi installer) which indeed installs msys etc, but you should also end up wiht 2.5 == Chugiak. The network installer is a second but more complex option.

closing this one as not website related
