### ISSUE TITLE
Add links to switch between $lang

### ISSUE THREAD

**Issue by pcav** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#2]
Perhaps with a list of flags

**Comment by jj0hns0n** [comment]
this is done (thanks @rduivenvoorde) no flags yet, but we can add this with css

currently can be seen here: http://new.qgis.org/html/en/

**Comment by pcav** [comment]
There are reasons not to use flags, so it's ok for me as it is. Just the box is too wide and tall.

**Comment by rduivenvoorde** [comment]
Somebody mentioned on the list that flags as notion of language is bad practice. And pointed to
http://www.worldaccent.com/blog/2012/09/flags-multilingual-website-navigation.html

So I think (also for implementation reasons), the dropdown as is is fine.

IF we want flags, we can put it one somewhere in the layout.html so it can be seen on ALL pages. Languages then can override this image (which by the way can contain several flags then, as you can read in the link, a language can map to several countries)

**Comment by jj0hns0n** [comment]
Note, I found we couldnt use non-ascii chars in this snippet (make gettext
complained). I think the existing dropdown with some css, showing langs
strings correctly (i.e. Español and not Spanish) is best.

**Comment by pcav** [comment]
Shouldn't we use ASCII codes, like &agrave; ?

**Comment by rduivenvoorde** [comment]
I was already wondering about what @jj0hns0n mentions: what kind of string do you need in a language dropdown:
'dutch' (english) or 'nederlands' (dutch in dutch ;-) )

Because in the second case (which I think is the right one, same as wikipedia: http://en.wikipedia.org/wiki/Qgis ) we would need to write 'chinese' in chinese characters which are not in ASCII or html codes. So we will need utf8 probably?

**Comment by pcav** [comment]
Agreed, second case should be the good one. I assume gettext interprets UTF-(, right?

**Comment by jj0hns0n** [comment]
Yeah, should be UTF-8 and as such, chinese is 中文 ... I will see if I can
figure this one out. Should we close this ticket and open a new one for
UTF-8 support?

**Comment by rduivenvoorde** [comment]
ok created new one: #31
