### ISSUE TITLE
How add a company who offers commercial support?

### ISSUE THREAD

**Issue by rmarzocchi84** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#201]
My comapny (Gter srl - Italy) currently uses QGIS / QGIS server / QGIS Web Client and offers training courses on QGIS. How it is possible add us on the commercial support website? 

http://www.qgis.org/it/site/forusers/commercial_support.html#qgis-commercial-support

Thanks in advanced

R

**Comment by m-kuhn** [comment]
The most promising way is to create a pull request with the support page updated to include your company.

**Comment by anitagraser** [comment]
Please specify in the pull request which services you are providing and add information if and how you contribute to the QGIS project. This information can be used to evaluate if the link is appropriate. (One of the things we have to take care of is to avoid that unrelated companies just add a link to their website for advertising purposes.)

**Comment by DelazJ** [comment]
@rmarzocchi84 what's the current status of this issue? Do you still plan to add your company and follow steps provided above or should we close this issue report?
Thanks.
