### ISSUE TITLE
Website displays 2.2 documentation when current release is 2.4 (2.6 release pending)

### ISSUE THREAD

**Issue by elil** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#204]
Going to the website and clicking documentation presents 2.2 documentation as the current documentation.  I would expect 2.4 documentation.  

Related to this, going to the testing documentation warns "Docs for ‘QGIS testing’. Visit http://docs.qgis.org for QGIS 2.2 docs and translations."  That should probably say 2.4 once the above is updated.

**Comment by anitagraser** [comment]
Afaik there is no 2.4 documentation we could link to. Therefore I'm not sure if this actually is a "website" issue.
