### ISSUE TITLE
ippj-5.3.dll não foi encontrado

### ISSUE THREAD

**Issue by gtfvalongo** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#207]
Já reinstalei por diversas vezes o software QGIS, ultima versão, e aparece-me sempre esta janela ao executar o desktop:

![image](https://cloud.githubusercontent.com/assets/9107744/4574441/5bdd4762-4f9c-11e4-8e3a-7b0c9bfe6efe.png)

![screenshot_qgis](https://cloud.githubusercontent.com/assets/9107744/4574451/6c97fac0-4f9c-11e4-9b16-b2778f525679.jpg)

Gostaria de saber como resolver o problema...

**Comment by gtfvalongo** [comment]
Também isto:

Package: Unknown package
    gpsbabelfe.bat exit code 1
    ka-map.bat exit code 1
    monteverdi.bat exit code 1
    qgis-common.bat exit code -1073741515
    qgis-dev.bat exit code -1073741515
    shell.bat exit code 1

**Comment by m-kuhn** [comment]
Hi, this is the issue queue for the QGIS Website. Please open an issue report. See here how to do it: http://www.qgis.org/pl/site/getinvolved/development/index.html#bugs-features-and-issues
