### ISSUE TITLE
QgsMessageBar plugin example does not work

### ISSUE THREAD

**Issue by markcoletti** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#213]
On http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/communicating.html#showing-messages-the-qgsmessagebar-class the last example does not work as is because the proper imports  haven't been made for QgsMessageBar.

**Comment by alexbruy** [comment]
Works fine for me

**Comment by rduivenvoorde** [comment]
@alexbruy 

I think what @piprrr means is that you need to add

```
from qgis.gui import *
```

otherwise the example 

```
iface.messageBar().pushMessage("Error", "I'm sorry Dave, I'm afraid I can't do that", level=QgsMessageBar.CRITICAL)
```

just does not work

@piprrr can you fix this and do a Pull Request?

**Comment by timlinux** [comment]
Also note that we should avoid making examples where we import \* from any module - its bad juju. Rather:

``` python
from qgis.gui import QgsMessageBar
iface.messageBar().pushMessage("Error", "I'm sorry Dave, I'm afraid I can't do that", level=QgsMessageBar.CRITICAL)
```

**Comment by elpaso** [comment]
Maybe we should consider adding a footer on all documentation pages with the proper link for filing documentation bugs? (i.e. https://github.com/qgis/QGIS-Documentation/issues )

**Comment by rduivenvoorde** [comment]
Well, there is already (at least in the master docs) the footer:

Textual error, missing text or you know better: fix me

where 'fix me' brings you to just the right rst file in github.... Can add another link though and make it:

Textual error, missing text or you know better: fix me or 'create an issue' 

where that part has a link to the issue tracker?

**Comment by elpaso** [comment]
@rduivenvoorde sorry, I didn't see the link was already there. We can't probably do better.
