### ISSUE TITLE
Debugging using PDB instructions do not work

### ISSUE THREAD

**Issue by markcoletti** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#215]
When following the instructions in http://docs.qgis.org/2.2/en/docs/pyqgis_developer_cookbook/ide_debugging.html#debugging-using-pdb I get the following error:

Got exception:  global name 'pyqtRemoveInputHook' is not defined

**Comment by alexbruy** [comment]
Works fine here

**Comment by mbernasocchi** [comment]
closing as stale,  If this is still relevant, please reopen
Cheers
