### ISSUE TITLE
Section 9.4.2: more_analysis folder not available in exercise_data

### ISSUE THREAD

**Issue by ghost** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#216]
I'm working through the QGIS Training Manual Release 2.2, and, in section 9.4.2, the reader is instructed to refer to the more_analysis directory (exercise_data/more_analysis). However, this directory is not available in the .zip file of the sample data (http://qgis.org/downloads/data/training_manual_exercise_data.zip). Please, where is this data available? Thank you!

**Comment by Javieda** [comment]
I'm in the same situation! with 2.8. version.

Googling I've founded a Dropbox link (https://www.dropbox.com/sh/n7kzrv7b8fzprxp/AABrvs2LQdNdJrCsC1VA3stMa?dl=0), on this website: http://gis.stackexchange.com/questions/107136/qgis-exercise-data.

Saludos!

**Comment by timlinux** [comment]
My apologies for this - please find it here:

https://www.dropbox.com/s/q5evvkizuunrcs0/more_analysis.zip?dl=0

We will get it onto the website asap.

**Comment by DelazJ** [comment]
@timlinux What's the current status of the license of these data? It seems that there's a problem with it according to https://github.com/qgis/QGIS-Documentation/issues/246#issuecomment-59697151.
Could these data be added now to the exercise data repo?

**Comment by timlinux** [comment]
@DelazJ The person who provided the data subsequently gave me permission to redistribute it, so go ahead and share it, thanks.

**Comment by DelazJ** [comment]
Thanks for the information

**Comment by DelazJ** [comment]
Trying to push the data in github (https://github.com/qgis/QGIS-Training-Data) repo, I encounter an error

> # git push origin MoreAnalysis
> Counting objects: 34, done.
> Delta compression using up to 4 threads.
> Compressing objects: 100% (31/31), done.
> Writing objects: 100% (34/34), 108.58 MiB | 101.00 KiB/s, done.
> Total 34 (delta 3), reused 0 (delta 0)
> remote: warning: File training_manual_data/more_analysis/Rainfall/reprojected/rainfall.tif is 95.62 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
> remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
> remote: error: Trace: de4307890a54b2796307983166e0db49
> remote: error: See http://git.io/iEPt8g for more information.
> remote: error: File training_manual_data/more_analysis/DEM/reprojected/DEM is 200.09 MB; this exceeds GitHub's file size limit of 100.00 MB
> To https://github.com/DelazJ/QGIS-Training-Data.git
>  ! [remote rejected] MoreAnalysis -> MoreAnalysis (pre-receive hook declined)
> error: failed to push some refs to 'https://github.com/DelazJ/QGIS-Training-Data.git'

We obviously have files larger than what GitHub allows. Any way to bypass this?

**Comment by DelazJ** [comment]
Found https://help.github.com/articles/versioning-large-files/ with git LFS solution which sounds to be a paid one. Any way to reduce the data (a DEM) size?

**Comment by Andre-J** [comment]
Unfortunately, the issue of https://github.com/qgis/QGIS-Documentation/issues/246#issuecomment-71265056 is still unsolved. The file  admin_boundaries/Western_Cape_33S.dbf is missing in the dropbox zip file. Hence the attribute table is empty. See also https://gis.stackexchange.com/questions/252606/qgis-2-14-problem-with-training-manual-exercise-data
