### ISSUE TITLE
Update 'Get Involved' Page and add light styling

### ISSUE THREAD

**Issue by jj0hns0n** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#22]
- [ ] mailinglist
- [ ] compile howtos
- [ ] IRC
- [ ] python developement & plugins
- [ ] api docs etc etc
- [ ] wiki
- [ ] release
- [ ] hub.qgis.org
- [ ] translation etc etc 

See http://www.flickr.com/photos/97361298@N07/9603909791/lightbox/

**Comment by rduivenvoorde** [comment]
So I think we should think of a design in which you either can jump from thiis page to these. 
Or create (design and rst?) a more general kind of jump page we can reuse for other places.
Or create two step jump for this list
