### ISSUE TITLE
Download link on main download page directing to v2.4 not v2.6

### ISSUE THREAD

**Issue by hzrimtrog** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#223]
The download link on the main page directs to http://www.qgis.org/en/site/forusers/download.html 
but that page still has the download files for v2.4, not v2.6 as advertised.

**Comment by rduivenvoorde** [comment]
not sure for which OS you are looking, but those that are available (windows, Linux) are there (plz do a hard refresh of the page, you may looking into your local cached page).
If still unavailable, please let us know, else close this issue.

**Comment by hzrimtrog** [comment]
Well, I feel like a fool.  Yes, it was a cache issue, page refresh solved it. Thank you for the help.
