### ISSUE TITLE
OPENLAYERS PLUGGIN doesn't work.

### ISSUE THREAD

**Issue by gabispaiva** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#230]
Guys,
I'm using the new version of Qgis (2.6) and the openlayers pluggin doesn't work!When we tried to zoom the layer,it's frozen and you can't do anything on this project.
I hope you can solve our problems!
Thank you!
![image](https://cloud.githubusercontent.com/assets/9964715/5204590/cb1243ac-7577-11e4-86a4-3c9d34d00c82.png)

**Comment by rduivenvoorde** [comment]
please use the issue tracker of the openlayers plugin itself for problems with the plugin and qgis:

http://hub.qgis.org/projects/openlayers/issues

this is the issue list for the QGIS website
