### ISSUE TITLE
Shape labeling

### ISSUE THREAD

**Issue by franhm** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#231]
Dear all,
I'm trying to put labels into a layer formed by an SQL Server table where I obtain a scoring (float format) for each polygon, its identifier and its GEOM reference. I was succesfull in colouring every part of the map based on a scale, depending on that score. Now, my purpose is to show the same score on top of the layer. I procceeded as described in several tutorials but was unsuccessful. In fact, just one label out of 19 appears initially on the map. Then, zooming in and moving randomly around the map area, at least apparently, some other (score labels) appear, although some others disappear. Can it be motivated by using an SQL table as layer source? How can I transform it, in case it is posible to, into a SHP file to come over and try to label it again, afterwards?

Many thanks in advance for your help.
Fran

**Comment by m-kuhn** [comment]
Dear Fran,

This is the issue page for the website www.qgis.org.

Your question would be better suited on one of the mailing lists or gis.stackexchange.com as described here:

http://qgis.org/en/site/forusers/support.html

Thank you for asking again there
