### ISSUE TITLE
Old versions for android

### ISSUE THREAD

**Issue by smanchon** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#241]
Hi,

Would it be possible to install an oldest version for android? Since the latest version was released, it appears as not available any more and the new one doesn't work properly in some tabs.

Thanks in advance.
Sergio.

**Comment by rduivenvoorde** [comment]
@smanchon this is the issue tracker for the QGIS Website. If you want to issue android specific issues, please do that here:

http://hub.qgis.org/projects/android-qgis/issues
