### ISSUE TITLE
Q GIS inquiry

### ISSUE THREAD

**Issue by jiinsystem** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#257]
i am a software developer of Ji-in System in Korea.
i am developing a software to visualize the drive information of the driverless car.
the software is supplied  to the Agency for Defense Development of Korea.
the agency will use the software continuously fot other closed research projects.
i want to use QGIS dll as a map visualization component to for the software. 
i know QGIS license IS GPL.
but i wondering i can use QGIS dll free for the software .
i read an article "QGIS for commercial usage"
http://comments.gmane.org/gmane.comp.gis.qgis.user/25446
brend wood said below
The QGIS licence (and the licences of other software it uses, such as GDAL, PROJ.4, QT, etc) fully enable commercial use of the software.
You are free to sell the software, sell products you create with the software, or sell services you provide using the software. There are no restrictions on any such use.

is he right?
but if the component is not free,

how can i buy it and how much is it?

best regards.

**Comment by m-kuhn** [comment]
Hi,

This is the QGIS-Website issue queue. Normally such information can be better discussed on one of the mailing lists [user or developer](http://qgis.org/en/site/getinvolved/mailinglists.html#qgis-mailinglists]) so for more information please contact there.

To answer your question shortly, you are free to use and sell the .dll as part of your work. Be aware however that creating derivative work of software with a GPL license automatically applies the GPL to everything included in that derivative work. So you will likely need to distribute your whole software under terms of the GPL. Please note that I am not a lawyer and you should get a professional opinion.
