### ISSUE TITLE
QGIS User Group Wales

### ISSUE THREAD

**Issue by breconbeacons** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#262]
This is undoubtedly the wrong place, bu I have no idea of where to send new content.

Please can you promote the QGIS User Group – Wales on your ‘Upcoming user & development meetings’ section of the QGIS website?

The event will be held Cardiff Mercure Holland Hotel, on Tuesday 6th October. There are only 50 spaces available. More details can be found at qgis.eventbrite.co.uk.

**Comment by rduivenvoorde** [comment]
@breconbeacons yes, will do it.

For later: either sent me or the community email list a message, 

OR (depending how github savvy your are): clone QGIS-Website repository and edit this file: 
https://github.com/qgis/QGIS-Website/blob/master/source/feeds/qugsnews.atom
and do a pull request

**Comment by breconbeacons** [comment]
Thanks very much for updating the website and for the info. 
Much appreciated.

**Comment by rduivenvoorde** [comment]
done

**Comment by breconbeacons** [comment]
Thank you ☺
Much appreciated.
