### ISSUE TITLE
QGIS plugins listing 'sort by average vote' no longer works 

### ISSUE THREAD

**Issue by lo-ise** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#271]
When choosing to sort by average vote, it retains sorting by a-z plugin name:

ie. http://plugins.qgis.org/plugins/?sort=-average_vote

**Comment by elpaso** [comment]
https://github.com/qgis/QGIS-Django/commit/82a0345c84e7fbbe00c98096a6a64be6e841ea7a
