### ISSUE TITLE
Distance calculation tool and table of content: error in distance

### ISSUE THREAD

**Issue by JuBrach** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#272]
Dear,

I have a problem with the distance calculation, it appear that even when I put my computer in SCR wgs 84 / UTM 19s #unity m. I obtain distance calculation and superficie which one's doesn't correspond to reality.

Can you give me a solution?

Faithfully,
Julien

**Comment by rduivenvoorde** [comment]
Hi, this is the issue tracker of the website, please use the qgis issuetracker for this issue:

http://qgis.org/en/site/getinvolved/development/index.html#bugs-features-and-issues

closing this one
