### ISSUE TITLE
Google Chrome - Blocking Website/Security Error

### ISSUE THREAD

**Issue by ClemaGem** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#273]
Google Chrome is currently blocking all QGIS.org websites via a "security error." This can be bypassed by clicking the Details link, then "visit this site." I am using Chrome version 44.0.2403.130. I have attached screenshots generated by Chrome; security error warning and the Chrome Diagnostic.

![googlechrome_1](https://cloud.githubusercontent.com/assets/1561047/9112969/12f1336c-3c20-11e5-8bb6-1236397b0812.PNG)
![googlechrome_2_diagnostic](https://cloud.githubusercontent.com/assets/1561047/9113003/2c2c104a-3c20-11e5-9833-d1407110f012.PNG)

**Comment by m-kuhn** [comment]
Seems like only http://www.qgis.org is affected but not http://qgis.org
https://www.google.com/safebrowsing/diagnostic?site=http%3A%2F%2Fwww.qgis.org%2Fpyqgis-cookbook%2F&client=googlechrome&hl=en-US

**Comment by rduivenvoorde** [comment]
All is ok with me now...  http://imgur.com/gyB8D79

plz reopen if you still find a problem...

**Comment by ClemaGem** [comment]
Thank you. Works on my end as well.
