### ISSUE TITLE
SSL certificate for blog.qgis.org

### ISSUE THREAD

**Issue by m-kuhn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#275]
https://blog.qgis.org/

shows a certificate error

> This server could not prove that it is blog.qgis.org; its security certificate is from *.wordpress.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

**Comment by timlinux** [comment]
I think we may be using a cname record to redirect to the wp hosted site.

**Comment by rduivenvoorde** [comment]
@m-kuhn mmm, we use the hosted services from wordpress.com, and according to their docs 

https://en.support.wordpress.com/domains/

https://en.support.wordpress.com/map-existing-domain/

we added a cname record to redirect to the wp hosted site.

Off course http://blog.qgis.org is working...

Not sure if we can put our certificate on their servers to make http work ...

Off course if you are concerned for the plain text travelling of passwords, you should use
https://qgisblog.wordpress.com/wp-login.php to login and write an entry.

so theoretically only avid httpS users will have this problem

but I've posted a question on support forum, see what they come up with:

https://en.forums.wordpress.com/topic/use-of-https-for-wordpresscom-site-via-c-record?replies=1#post-2448991

**Comment by rduivenvoorde** [comment]
ok, that was fast...

https://en.forums.wordpress.com/topic/redirecting-to-subdomains-and-ssl-certificates?replies=3#post-2434939

or in short: "At the moment, we actually don't support SSL for mapped domains and subdomains, but we are working on it, hopefully before the end of the year. "

so three options:
-1- only use http for blog.qgis.org and if you want to write an article use qgisblog.wordpress.com
-2- host our own wordpress instance (BUT we miss the very nice statistics of wordpress.com then, AND we need to manage it ourself)
-3- wait until the end of this year ...

I vote for for 1 and 3

**Comment by andreasneumann** [comment]
I would go with option 1 and change back to https once it becomes available.

**Comment by m-kuhn** [comment]
~~@rduivenvoorde If it is mapped, I guess there is a wp.com url which matches the certificate?~~

Ooops, you answered it above already (https://qgisblog.wordpress.com)

**Comment by timlinux** [comment]
Hi

> On 19 Aug 2015, at 21:10, Richard Duivenvoorde notifications@github.com wrote:
> 
> ok, that was fast...
> 
> https://en.forums.wordpress.com/topic/redirecting-to-subdomains-and-ssl-certificates?replies=3#post-2434939 https://en.forums.wordpress.com/topic/redirecting-to-subdomains-and-ssl-certificates?replies=3#post-2434939
> or in short: "At the moment, we actually don't support SSL for mapped domains and subdomains, but we are working on it, hopefully before the end of the year. "
> 
> so three options:
> -1- only use http for blog.qgis.org and if you want to write an article use qgisblog.wordpress.com
> -2- host our own wordpress instance (BUT we miss the very nice statistics of wordpress.com then, AND we need to manage it ourself)
> -3- wait until the end of this year ...
> 
> I vote for for 1 and 3

Im ok with 1 then 3

Regards

Tim

> —
> Reply to this email directly or view it on GitHub https://github.com/qgis/QGIS-Website/issues/275#issuecomment-132746162.

—

Tim Sutton

Visit http://kartoza.com http://kartoza.com/ to find out about open source:
- Desktop GIS programming services
- Geospatial web development
- GIS Training
- Consulting Services

Skype: timlinux Irc: timlinux on #qgis at freenode.net
Tim is a member of the QGIS Project Steering Committee

Kartoza is a merger between Linfiniti and Afrispatial

**Comment by pcav** [comment]
Il 21/08/2015 20:56, Tim Sutton ha scritto:

> Im ok with 1 then 3

+1

## Thanks.

Paolo Cavallini - www.faunalia.eu
QGIS & PostGIS courses: http://www.faunalia.eu/training.html

**Comment by rduivenvoorde** [comment]
ok, then I close this one
