### ISSUE TITLE
change FOSS4G-Seoul banner to FOSS4G-Bonn banner on qgis.org

### ISSUE THREAD

**Issue by jmckenna** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#283]
Similar to last year's addition of the FOSS4G-Seoul banner to the qgis.org site (https://github.com/qgis/QGIS-Website/pull/226), we should change that banner to the 2016 Bonn banner. Here are some links:
- 2016 banner files: https://svn.osgeo.org/osgeo/foss4g/2016/marketing/banners/
- view of several 2016 banners: http://antonpopov.de/foss4g-2016/banners/
- 2016 logos: https://svn.osgeo.org/osgeo/foss4g/2016/marketing/logo/

For last year, the 2015 Seoul committee provided a custom logo for qgis.org of the dimensions "940px × 300px and taking into consideration the black stuff on bottom of the banner on qgis.org". I assume that this is the same dimensions needed now. I will ask the 2016 designer for this and get back to you here.

**Comment by apovde** [comment]
How are you feeling about using photographs in the banner? There are photographs available by the city of Bonn that we (2016 LOC) are licensed to use:
- https://svn.osgeo.org/osgeo/foss4g/2016/documents/photographs/

Some of these are already in use by a few banners and a postcard.

I could also prepare a banner like the final #226-version using just the logo and some line art in 940x300.

Any preferences/thoughts appreciated =)

**Comment by apovde** [comment]
I created a first banner that takes the white background into account (not the dark):
- with slogan: http://antonpopov.de/foss4g-2016/banners/foss4g2016-banner-qgis_940x300-01.png
- without slogan: http://antonpopov.de/foss4g-2016/banners/foss4g2016-banner-qgis_940x300-01_noslogan.png

On the page it could like this:
- http://antonpopov.de/foss4g-2016/banners/foss4g2016-banner-qgis_940x300-01_scr.png

Tell me what you think

**Comment by jmckenna** [comment]
I do like the with-slogan option.  Let's see what @rduivenvoorde says.

**Comment by jmckenna** [comment]
@rduivenvoorde ping.  There's a marketing push now for all projects to change their FOSS4G logo to 2016.  @apovde has generated some logos custom to the QGIS homepage, can you take a look?

**Comment by jmckenna** [comment]
@rduivenvoorde i now notice that the Seoul widget has been removed on qgis.org but this new Bonn banner has not been added.  Was there a problem with adding the draft banner that @apovde created for this?

**Comment by rduivenvoorde** [comment]
@jmckenna I just changed the Seoul banner for the 2.12 released one..

haven't been able to look into this, but will do tomorrow as we do the visual changelog then, and all txt's will be pushed to transifex too

**Comment by jmckenna** [comment]
k thanks @rduivenvoorde

**Comment by rduivenvoorde** [comment]
Banner added, plz check link used. Not doing the widget for now below the QGIS/OSGEO widgets. If banner is not enough, happy to temporarily replace osgeo widget with a same size bonn widget.
closing for now

**Comment by jmckenna** [comment]
I don't see it yet on http://www.qgis.org/en/site/ but will check back later today.

**Comment by jmckenna** [comment]
Verified, it looks and works great!  Thank you @rduivenvoorde and @apovde :)
