### ISSUE TITLE
2.12 Changelog leads to 404

### ISSUE THREAD

**Issue by michaelkirk** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#286]
Front page carousel has a broken link for "Visual Changelog".

It sends you to http://qgis.org/en/site/forusers/visualchangelog212/index.html
Which redirects to http://changelog.qgis.org/qgis/version/2.12.0/index.html which is 404.

<img width="702" alt="screen shot 2015-10-26 at 12 35 45 pm" src="https://cloud.githubusercontent.com/assets/217057/10740192/1df250c2-7bde-11e5-8003-2e7c9ed80c78.png">

```
curl http://qgis.org/en/site/forusers/visualchangelog212/index.html
<!DOCTYPEHTMLPUBLIC"-//IETF//DTDHTML2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://changelog.qgis.org/qgis/version/2.12.0/index.html">here</a>.</p>
</body></html>
```

Instead, it should redirect to http://changelog.qgis.org/qgis/version/2.12.0/  (no index.html)
I'm not sure where the redirect is being handled. Maybe some server config that's not in this repo?

**Comment by rduivenvoorde** [comment]
fixed, was a wrong redirect. Now we will have the real changelog (after next build)
