### ISSUE TITLE
Merge mailing lists to community page, add content and layout

### ISSUE THREAD

**Issue by jj0hns0n** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#29]
There should be a single page that is the launching off point to many aspects of the community. This page probably requires some custom layout, but we should just make it a complete set of resource in rst initially.

**Comment by rduivenvoorde** [comment]
I think this is supposed to be the Get Involved page, see #22

**Comment by jj0hns0n** [comment]
@rduivenvoorde yeah, this should all be one single "Get Involved" Page as in #22
