### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by michaelkirk** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#291]
Hey! Love the docker scripts for building the docs, make it really easy.

Do you have a dockerfile explaining whats in the image? If not, would you accept one?

**Comment by rduivenvoorde** [comment]
This is the docker file for both html and pdf docker:

https://github.com/qgis/QGIS-Sysadmin/tree/master/docker/sphinx

we may need to renew some components...
