### ISSUE TITLE
docker-run.sh should build css from less 

### ISSUE THREAD

**Issue by michaelkirk** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#292]
That way folks don't have to worry about how to compile less.

**Comment by rduivenvoorde** [comment]
Good idea. Will do this when I create a new docker image.
We will upgrade to a python3, newer sphinx/tx versions etc for (what I think) will be the next LTR..

**Comment by DelazJ** [comment]
@rduivenvoorde is this covered now?

**Comment by mbernasocchi** [comment]
closing as stale,  If this is still relevant, please reopen
Cheers

**Comment by mbernasocchi** [comment]
@rduivenvoorde feel free to reopen if it is not fixed yet
