### ISSUE TITLE
language dropdown should be able to show utf: 中文

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#31]
The language dropdown should show the language in the language itself. So for eg:
dutch: nederlands
chinese: 中文
spanish: Español

We have to be sure that we can handle this utf-8 kind of languages, both in content and in site strings.

(question: should we or not also do the language in english? Or will the values then just be too long:
Nederlands (dutch)
Español (spanish)
中文 (chinese) etc

Maybe just start with the real strings. Later we can make it really dynamic: like if you are in dutch, show:
Nederlands (nederlands)
Español (spaans)
中文 (chinees) etc

**Comment by pcav** [comment]
I do not think we need to have really dynamic, as in your last example.
IMHO the firs option is best, I think mos multilingual sites manage it like this.

**Comment by rduivenvoorde** [comment]
Found this:

https://bitbucket.org/birkenfeld/sphinx/issue/1166/gettext-target-cant-handle-non-ascii-files

Pointing to this commit:

https://bitbucket.org/birkenfeld/sphinx/commits/357b5d198e3e

which has not been landing yet in Sphinx 1.2b1 yet, but if I apply that to my local file in my virtual env, it just works \o/
Will do and show on new.qgis.org, but leave ticket open for some time as reference
