### ISSUE TITLE
Resize screenshots

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#322]
The screenshots in http://qgis.org/fr/site/about/case_studies/canada_brunswick.html need to be resized to fit the space allocated. They are too big.

**Comment by DelazJ** [comment]
Actually there are many case studies that are concerned by oversized screenshots. What can be done to avoid this in the future: recommand a resolution (size?) to submitters? Or do we already have tools to resize these screenshots but they misbehave?
Then, what could be the best way to fix these sizes:
- iterating over the ratio tag till you find the appropriate one
- or will saving them with application like Gimp in a particular resolution solve the issue?

**Comment by rduivenvoorde** [comment]
Should be fixed in https://github.com/qgis/QGIS-Website/commit/ed6fff8fa1003ef4d58d58cfc7653200bd765c21

Let me know if you see other image artifacts ...
