### ISSUE TITLE
Book recommendations links are broken.

### ISSUE THREAD

**Issue by ghost** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#328]
On the coding standards page, all book recommendation links are broken.

Instead of navigating to the listed book, the user is redirected to http://www.informit.com/imprint/index.aspx?st=61085 which is not relevant.

**Comment by yjacolin** [comment]
Could you give me a link to the " coding standards page"?

Books are here: http://qgis.org/en/site/forusers/books/index.html and links are ok. Thanks.

**Comment by DelazJ** [comment]
@yjacolin http://qgis.org/fr/site/getinvolved/development/qgisdevelopersguide/codingstandards.html#book-recommendations

**Comment by ghost** [comment]
Sure: 

https://github.com/qgis/QGIS-Website/blob/master/source/site/getinvolved/development/qgisdevelopersguide/codingstandards.rst

http://www.qgis.org/en/site/getinvolved/development/qgisdevelopersguide/codingstandards.html

**Comment by ghost** [comment]
Sorry, the 'More effective C++' link is working, the rest aren't'

**Comment by yjacolin** [comment]
Here are two links, not sure if they are correct though.
- http://www.informit.com/store/effective-c-plus-plus-digital-collection-140-ways-to-9780133068627
- http://www.informit.com/store/effective-stl-50-specific-ways-to-improve-your-use-9780201749625

I didn't find the last one. We need to ask to the developper to be sure what we should do here. Tanks @nagytech .

**Comment by yjacolin** [comment]
ping @rduivenvoorde any idea about this book?

**Comment by rduivenvoorde** [comment]
@yjacolin this are old links, but more or less earlier c++ bibles.

Did some googling, and Effective C++ there is a new version, so maybe not add links to it, but write:
- Scott Meyers C++ books, eg the most recent: Effective Modern C++  (linking to http://shop.oreilly.com/product/0636920033707.do)
- Scott Meyers STL standard work: http://www.amazon.com/gp/product/0201749629?ie=UTF8tag=aristeia.com-20linkCode=as2camp=1789creative=9325creativeASIN=0201749629
- Design Patterns from the Gang of Four: http://www.amazon.com/Design-Patterns-Elements-Reusable-Object-Oriented/dp/0201633612

(http://www.informit.com/store/effective-c-plus-plus-digital-collection-140-ways-to-9780133068627 is actually the 'old books', but apparently still ok).
