### ISSUE TITLE
layer_property - documentation?

### ISSUE THREAD

**Issue by glomerata** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#329]
Where can I get description of the function layer_property?

**Comment by DelazJ** [comment]
layer_property is a variable and variables are not yet tackled in the Documentation.
You can however find information on variables at http://nyalldawson.net/2015/12/exploring-variables-in-qgis-2-12-part-1/ maybe will you figure out the way this one works

**Comment by DelazJ** [comment]
The exact link is the [part 3](http://nyalldawson.net/2015/12/exploring-variables-in-qgis-pt-3-layer-level-variables/) which points to layer_property function.

PS: better ask questions about documentation or anything else about QGIS in the [QGIS mailing-list ](http://qgis.org/fr/site/getinvolved/mailinglists.html#mailing-lists) and report issues about the website here and about documentation on [doc repository ](https://github.com/qgis/QGIS-Documentation/issues).
Thanks.
