### ISSUE TITLE
Download links seems dead

### ISSUE THREAD

**Issue by lawrence9811** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#331]
Download links are dead, for example:
http://qgis.org/downloads/QGIS-OSGeo4W-2.14.1-1-Setup-x86_64.exe

First try shows 403 forbidden message, now the download is 0KB.

**Comment by DelazJ** [comment]
Couldn't download it neither. Thanks for the report.
@jef-n ?

**Comment by jef-n** [comment]
Fixed.
