### ISSUE TITLE
The FAQ really needs some love

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#332]
There's a [FAQ](http://qgis.org/en/site/getinvolved/faq/index.html) which looks really empty and might need some enhancement:
- more topics. I often read people in mailing list asking about Processing broken since upgrading QGIS, Grass6/7 plugins(?) settings/broken. There might be other things. 
  I know it's not supposed to replace documentation but given that it exists and aims to report frequent questions ...
- The "how to ask a QGIS question?" section looks more like steps for a bug report than a simple questionning
- Links to compilation steps should directly reach the exact chapter according to the OS used instead of landing to the top of the page. But If the first lines of these instructions need to be read, then a single section with a generic comment on compilation, regardless OS, should be written
- there's more spacing betwen lines when reading a translated version of the FAQ than the english one

**Comment by rduivenvoorde** [comment]
Looks like this is merged, closing this one
