### ISSUE TITLE
Add QGIS 2.14 Fedora Repo (COPR)

### ISSUE THREAD

**Issue by floju** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#333]
+Alternatively you can have a look at Fedora COPR (https://copr.fedorainfracloud.org/coprs/)
+QGIS 2.14 "Essen" for Fedora 22, 23, 24 
+https://copr.fedorainfracloud.org/coprs/neteler/QGIS-2.14-Essen/

**Comment by DelazJ** [comment]
@jef-n is this a valid information to put in the website?

**Comment by m-kuhn** [comment]
looks good to me, this should replace the current information for Fedora alternative repository

**Comment by rduivenvoorde** [comment]
@floju can you maybe provide the text (or prefereably do a pull request) with the info you would want to have in the Download page?

**Comment by m-kuhn** [comment]
@rduivenvoorde can you check the .rst for errors, sorry, I'm still not fluent ;)

**Comment by rduivenvoorde** [comment]
@m-kuhn yep, fixed. Thanks for adding!
