### ISSUE TITLE
download link of the mac os x QGIS is not working 

### ISSUE THREAD

**Issue by yagojanveith** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#335]
The download link of the mac osx QGIS 2.14.1 'Essen' is not working.
First step
https://www.qgis.org/en/site/forusers/download.html

then click on "KyngChaos QGIS download"
http://www.kyngchaos.com/software/qgis

Page does never loads.

**Comment by DelazJ** [comment]
Hi,
Just tested and I can't reproduce (got the page without problem). Used Firefox. If you can give any information on browser used...

**Comment by yagojanveith** [comment]
Hi
Thank you. Yes it seems the page does work - BUT not in my region / ISP :o. 99.9% of websites where no issue in the last 2 month... I just to the link via dropbox. But IMHO something cool would be to release the installer on torrent in future...
