### ISSUE TITLE
Full TOC in sidebar not usable on small screens

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#34]
If we have a TOC with a lot of items, eg:
http://new.qgis.org/html/nl/getinvolved/development/pyqgis_developer_cookbook/index.html
You will not be able to see/use the lowest items of the toc, because the sidebar is used.

If people agree that the sidebar should scroll:

That is an easy fix, it is now fixed to the top, but if we take out the affix class from the sidebar div, it will scroll:

<div id="sidebar" class="bs-sidenav well affix" data-spy="affix">
becomes
<div id="sidebar" class="bs-sidenav well" data-spy="affix">

**Comment by pcav** [comment]
Something seems missing.
IMHO the correct behaviour is: TOC should scroll until its end, not in parallel with the main content, i.e. when reaching the end of the TOC itself, it should not go further down, leaving empty space, and making it difficult to navigate further up.

**Comment by jj0hns0n** [comment]
@pcav @rduivenvoorde this can be closed now?

**Comment by pcav** [comment]
Il 08/09/2013 05:37, Jeffrey Johnson ha scritto:

> @pcav https://github.com/pcav @rduivenvoorde 
> https://github.com/rduivenvoorde this can be closed now?
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/qgis/QGIS-Website/issues/34#issuecomment-24014410.
> 
> IMHO the implemented one is not the optimal behaviour, as described
> above (see e.g. http://new.qgis.org/html/en/about/sponsorship.html)

## 

Paolo Cavallini - Faunalia
www.faunalia.eu
Full contact details at www.faunalia.eu/pc
Nuovi corsi QGIS e PostGIS: http://www.faunalia.it/calendario

**Comment by rduivenvoorde** [comment]
@pcav, I think your wish is a very complex one to implement either in sphinx or in bootstrap. 

So I close this one as the original issue was implemented.

Please open a new one as a feature request, if it is really important to you. Maybe somebody with enough css foo can implement it then in future. 
It is rather complex because the placing of the footer is also depending on it, It should still be responsive etc

**Comment by pcav** [comment]
Maybe not so difficult, see http://www.3liz.com/formations.html
Perhaps we can ask the 3liz friends.

**Comment by rduivenvoorde** [comment]
mmm, this looks awfully good :-)

yep, please ask them to implement this in our site!

But still, closing this one. And first have a site running.
