### ISSUE TITLE
Have a schedule to push text to Transifex

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#340]
Following this non answered discussion in [mailing-list](http://osgeo-org.1560.x6.nabble.com/Qgis-community-team-How-often-are-QGIS-Website-files-pushed-to-Transifex-for-translation-td5260607.html), I wonder if it might not be a good thing to have a schedule to push website texts to transifex, so that when Transifex shows 100% translated, it's _most of the time_ really 100%.

**Comment by rduivenvoorde** [comment]
@DelazJ you are probably right... I'm a little behind. I often did that when I was busy pushing a new version of the docs (when we were still building for every release).
I also did it when there was a new QGIS release, so the visual changelog etc were translatable...

Will push within upcoming days again. And bug me if I'm too slow, if you want it to be done earlier.

**Comment by rduivenvoorde** [comment]
Just updated the website strings to transifex. Will do after the next QGIS release, OR just ask me to do this.

**Comment by DelazJ** [comment]
Yes, I see your changes. Thank you.

Wonder if this issue report shouldn't be kept open. Its purpose is to have a schedule, something formalized as we have for QGIS release. This will help to keep a really fully clean and translated website for the communities that care about and have texts  to propose to translators and keep them focused/concerned.

Of course, I'm not expecting it to be done now as you are alone on this if i'm not wrong. But maybe, as you suggested in ML, it's time for you to have a Padawan...
