### ISSUE TITLE
2.14.0 and 2.8.7 referenced in Spanish version

### ISSUE THREAD

**Issue by m-kuhn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#342]
The download links point to an outdated version on the Spanish translation

http://qgis.org/es/site/forusers/download.html

**Comment by DelazJ** [comment]
Looking at the bottom of the main page of the [site](http://www.qgis.org/es/site/index.html), it appears that the last build is from 01:09 Mar 09, 2016. Something broken in the translation...
BTW, testing other languages, it appears that it's not the only one out of date:
- Deutsch are from am 00:07 Apr 06, 2016
- finnish from 00:15 Apr 19, 2016 
- Magyar from 01:18 Mar 16, 2016 
- nederlands from 01:32 Mar 06, 2016 
- portuguese brasil from 01:36 Mar 06, 2016 
- Romania  01:40 Mar 07, 2016
- Russia 01:44 Mar 22, 2016

**Comment by rduivenvoorde** [comment]
See also:
https://lists.osgeo.org/pipermail/qgis-community-team/2016-April/004595.html
I'm hoping that translators pick this up theirselves, as it takes me some time too to find te errors in the translations, and if I fix them the translator (or at least the language coordinator) will not learn/see what kind of errors he/she should try not to make.
But I'm happy to fix it if they ask

**Comment by sorin-calinica** [comment]
Hi Richard,
I'm really sorry for the time spent on identifying translation errors... Yesterday I was able to fix (on Transifex) the error reported by you for the Romanian language, but I noticed that during the night the site wasn't rebuilt.
Are there necessary to be done additional steps (like pulling strings from Transifex) or another error has occurred again?

**Comment by rduivenvoorde** [comment]
@sorin-calinica  no worries :-)
I'll have a look at 'ro' too...

Hungary http://qgis.org/hu/site/ is now fixed, there was just one translation error left:
/site/source/site/getinvolved/governance/governance.rst:145: WARNING: inconsistent term references in translated message
(reference was removed from translation)

**Comment by rduivenvoorde** [comment]
Ok, 
ro fixed, 
ru fixed,
fi, nl, de are already ok

**Comment by rduivenvoorde** [comment]
Ok, all fixed, closing this one

**Comment by DelazJ** [comment]
Big Thank you, Richard

**Comment by m-kuhn** [comment]
Thank you Richard!

**Comment by sorin-calinica** [comment]
Thank you Richard!
