### ISSUE TITLE
plugin manager crash

### ISSUE THREAD

**Issue by hcmeyer** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#354]
I am using ver 2.14.0 from the fedora repo on fedora 24. Attempting to open the plugin manager from the menu bar produces a seg fault. Instructions ?

**Comment by yjacolin** [comment]
Please contact QGIS-user mailing list or forum: http://qgis.org/en/site/forusers/support.html

This issue tracker is for problem with QGIS Website only.
