### ISSUE TITLE
Update sponsor banner

### ISSUE THREAD

**Issue by jef-n** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#357]
Our Sponsor banner https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/static/images/sponsors.png needs an update.  QGIS Usergroup Switzerland is our new GOLD sponsor and AGH isn't sponsor anymore.

![Sponsors](https://raw.githubusercontent.com/qgis/QGIS-Website/a859a29c0ce0c299a89b0ffe1ca4f4f3f9649898/themes/qgis-theme/static/images/sponsors.png)

**Comment by rduivenvoorde** [comment]
@anitagraser @andreasneumann is this true? Should we update the image?

**Comment by anitagraser** [comment]
Well, I already did https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/static/images/sponsors.png

**Comment by rduivenvoorde** [comment]
Mmm, I see it here on my local build indeed. Thanks! 
WIll have a look into the builds...

**Comment by rduivenvoorde** [comment]
The images is updated and the good one is in the output directory.
It is in the rsync step that it was not synced, because it has the same name.

AND we do cloudflare caching which also caches. 
So I removed the old (non rsynced) images so it was synced, and then if you use: http://foo.qgis.org, you see it, but http://qgis.org still does, though I disabled Cloudflare just now. Not what ttl=automatic time is now...

Easiest solution (I think) is to (instead of my plan to just name it 'sponsors'.png' to add a time to it.. sponsors201606.png or so?

@timlinux  maybe other ideas?

**Comment by jef-n** [comment]
Hi Richard,

On Tue, 28. Jun 2016 at 00:27:55 -0700, Richard Duivenvoorde wrote:

> @anitagraser @andreasneumann is this true? Should we update the image?

See http://qgis.org/en/site/about/sponsorship.html

Jürgen

## 

Jürgen E. Fischer           norBIT GmbH             Tel. +49-4931-918175-31
Dipl.-Inf. (FH)             Rheinstraße 13          Fax. +49-4931-918175-50
Software Engineer           D-26506 Norden             http://www.norbit.de
QGIS release manager (PSC)  Germany                    IRC: jef on FreeNode

**Comment by rduivenvoorde** [comment]
@jef-n yes, don't worry, not questioning your issue ;-) Just wanted to ping the people who normally fix those (and actually did...) 

Thanks all!

**Comment by anitagraser** [comment]
@rduivenvoorde Any naming approach is fine for me. Just let me know what works.

**Comment by rduivenvoorde** [comment]
@anitagraser the naming approach will work, it is just that without it, it would be easier to update... /me hoping somebody comes up with a better solution....

**Comment by rduivenvoorde** [comment]
ok, rsync step is doing fine, the new image is already on the server for all languages... Sorry for the noise. It is apparently purely the Cloudflare cache...

**Comment by DelazJ** [comment]
The banner has changed for english language but is still the same for other languages

**Comment by DelazJ** [comment]
fixed
