### ISSUE TITLE
Plugin titles / tabs all look the same in browser tabs

### ISSUE THREAD

**Issue by jidanni** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#360]
Let's open a few tabs about plugins in our browser.

The result is as you can see.
![m](https://cloud.githubusercontent.com/assets/1230959/16439453/275791f2-3deb-11e6-9e11-dcc1a4fe16b8.jpg)
They all have the same HTML TITLE..

What they should have is their or keyword prepended:
so that both type of pages
https://plugins.qgis.org/plugins/tags/ibama/
https://plugins.qgis.org/plugins/LocatePoints/
would all have the distinguishing parts of their names near the
beginning of the TITLE so we could tell them apart in browser tabs or
in a browser History list.

**Comment by DelazJ** [comment]
@jidanni Thank you for the report but I think the best place for this issue is https://github.com/qgis/QGIS-Django/issues where plugin website is managed.
@elpaso ?

**Comment by jidanni** [comment]
OK please reassign it there for me. Thanks.

**Comment by DelazJ** [comment]
done!
