### ISSUE TITLE
Loading Template into Composer stalls

### ISSUE THREAD

**Issue by AgAssist** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#361]
When you load a template into composer in 2.14.3 the status bar indicates that it is working on loading the new template but could go on for hours and it does nothing until you cancel the task. Once you cancel the task the new template has loaded but parts of the template are missing.

**Comment by DelazJ** [comment]
@AgAssist please report this in the issue tracker (hub.qgis.org) or ask for help in one of qgis [support channels](http://qgis.org/en/site/forusers/support.html).
This repository is dedicated to QGIS Website issues.
