### ISSUE TITLE
Error: when you print a new map - slipping layers

### ISSUE THREAD

**Issue by Nikolaidis8416** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#362]
Hi, I'm a new user in Q-GIS Desktop; the problem is: when I use the impression's generator for print a new map, in the final product (PDF, PNG, etc) I can see a lot of mistakes (for example: layers in wrong possitions, the base map is slipping regarding other layers, objects with mistakes, etc), please help me ¡¡.

Thanks a lot for your attention.

**Comment by DelazJ** [comment]
@Nikolaidis8416 please ask for help in one of qgis support channels (http://qgis.org/fr/site/forusers/support.html).
This repository is dedicated to QGIS Website issues.
About your issue, you might be using OpenLayers plugin which is known to have this issue in print  composer. Try QuickMapServices plugin.
