### ISSUE TITLE
Bugreports dead link

### ISSUE THREAD

**Issue by ArtificialTruth** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#363]
I wanted to report a pretty serious bug, but your help page link on http://hub.qgis.org/projects/quantum-gis is dead.
This is the link that no longer works: http://hub.qgis.org/wiki/quantum-gis/Bugreports
So I have no clue on how to report bugs for the desktop program.

**Comment by DelazJ** [comment]
You may find the needed information at http://www.qgis.org/en/site/getinvolved/development/bugreporting.html

**Comment by ArtificialTruth** [comment]
Thanks, that's actually where I found the link to Redmine on that page - I can't seem to find the "New Issue" button in the menu bar.

**Comment by DelazJ** [comment]
Do you have an osgeo ID? you need to be connected in order to have this tab active

**Comment by ArtificialTruth** [comment]
No, I don't. Where do I register for that?

**Comment by DelazJ** [comment]
https://www.osgeo.org/cgi-bin/ldap_create_user.py The link is just under http://www.qgis.org/en/site/getinvolved/development/bugreporting.html#reports-on-applications

**Comment by ArtificialTruth** [comment]
Oh I completely skipped that. Thanks!

**Comment by DelazJ** [comment]
you are welcome

**Comment by ArtificialTruth** [comment]
Well, the issue is not fixed so no need to close this ticket yet.

**Comment by DelazJ** [comment]
Actually all the needed information are available in  http://www.qgis.org/en/site/getinvolved/development/bugreporting.html#reports-on-applications. If you read all the section above, no way you reach that wrong page.
That said, I'm not sure that link will be fixed given that there's more than a discussion to move issue report to github and some wikis in redmine are getting frozen (though I do not expect it to show as it is now).
Let reopen your issue and someone more involved in redmine wiki will statuate what has to be done.
@rduivenvoorde @dassau

**Comment by rduivenvoorde** [comment]
@ArtificialTruth I changed the dead link on: http://hub.qgis.org/projects/quantum-gis to current link about creating bug reports.

We will probably move away from hub.qgis.org in near future.

If ok, feel free to close this issue please, or let me know what else you want to be fixed

**Comment by ArtificialTruth** [comment]
Sweet, I'll close the issue.
