### ISSUE TITLE
Contact link not working (404 Not Found)

### ISSUE THREAD

**Issue by zambra** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#367]
The envelope image link is broken at the bottom of the main page (just after the Github image). The link points to [http://www.qgis.org/en/site/getinvolved/about.html](url)

**Comment by rduivenvoorde** [comment]
Mmm, thanks for noting, will have a look at it

**Comment by DelazJ** [comment]
Duplicate of #377 and fixed in #378
