### ISSUE TITLE
Planet QGIS is not updated anymore (Latest Blog Posts)

### ISSUE THREAD

**Issue by zambra** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#368]
There is no new blog post since May, 29 while there are new blog posts available ex. 
"Traveltime routing & catchment extension for the QGIS IDF router" from Anita Graser published on
2016-07-17 should be listed.

**Comment by rduivenvoorde** [comment]
Problem was a update script that was'nt runnig anymore. Should be fine now. If not, please reopen
