### ISSUE TITLE
style fill offset linear patterns

### ISSUE THREAD

**Issue by REDGIORGIO** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#369]
prejudice are george, I need help regarding the construction of filling a poly layer called cadastral representing particle owners.
many to one relationship.
I connected with mmqgis proprietari.csv (many) to particelle.shp (one) and created a new shp with svrapposti polygons for each subject represented.
eg particle 1 prop guy 100% one poliggono
.... Particle 2 prop Dick 25% + 75% trad two polygons
proprietari.csv contains a field progresProp (double) plus a TotProp field (twice).
so:
Particle 1 name = dude; progresProp = 1; TotProp = 1
particle 2 name = foo; progresProp = 1; TotProp = 2
particle 2 Name = simp; progresProp = 2; TotProp = 2

the properties of the vector is defined by style category of name
symbol fill filling linear patern distance = TotProp
lienea simple stroke = 1 offset = progresProp

aim is to achieve parallel lines of different colors for n owners.
particle 1 will be the line of the same tight red (distance = 1, width = 1 offset = 1)
particle 2 will be the line of a different color blue alternarnate (distance = 2; width = 1 offset = 1) + green (distance = 2; width = 1 offset = 2)

in fact I can not apply the offset property it 'as calculated it' value as the value preassigned

**Comment by DelazJ** [comment]
@REDGIORGIO 
Please ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)).
This repository is actually dedicated to issues related to the main website of QGIS project.
