### ISSUE TITLE
Update the who-is-who of the QGIS Project

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#372]
There might be outdated information in http://qgis.org/en/site/getinvolved/governance/governance.html, at least at http://qgis.org/en/site/getinvolved/governance/governance.html#code-maintainers (for what I know)

**Comment by rduivenvoorde** [comment]
Yep, agreed, should be updated

**Comment by DelazJ** [comment]
Maybe, wait till the new structure of the organisation is settled?

**Comment by mbernasocchi** [comment]
@DelazJ seems up to date now? can we close this?

**Comment by DelazJ** [comment]
Thanks @mbernasocchi
