### ISSUE TITLE
alldownloads page for ubuntu more instructions

### ISSUE THREAD

**Issue by rmarzocchi84** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#374]
When you say  

```
If you use one of our ubuntugis based repositories you also need to add following line:

deb     http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu *codename* main
```

in the [(https://github.com/qgis/QGIS-Website/blob/master/source/site/forusers/alldownloads.rst)] page I think can be useful also to suggest to add the key for ubuntugis unstable repository:

sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 089EBE08314DF160

**Comment by DelazJ** [comment]
Is this still valid @rmarzocchi84? The page has been reworked these last months and i could not find your references. 
Closing?
