### ISSUE TITLE
Where is libsip?

### ISSUE THREAD

**Issue by jiapei100** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#376]
Hi:

My environment:
Ubuntu 16.04.1
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
QMake: QMake version 3.0
Using Qt version 5.7.0 in /opt/Qt5.7.0/5.7/gcc_64/lib

I'm using **cmake** to configuration **qgis**:

>  CMake Error at cmake/FindSIP.cmake:54 (MESSAGE):
>    Could not find SIP
>  Call Stack (most recent call first):
>    CMakeLists.txt:731 (FIND_PACKAGE)

So, my questions is: what is SIP? How to make qgis find sip?

Cheers
Pei

**Comment by dmitrykinakh** [comment]
@jiapei100, pls take a look on a similar issue - https://github.com/Homebrew/homebrew-science/issues/14

**Comment by yjacolin** [comment]
Please, don't use QGIS Website project for QGIS build issue. You can have help from the mailing list.
