### ISSUE TITLE
QGIS 2.16: Zoom in from attribute table doesnt work anymore

### ISSUE THREAD

**Issue by HPatric** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#381]
Hello

if you open the attribute table for a layer and select a row,
try to zoom in to the map, the zoom in doesnt work anymore.
The former version 2.14 has run fine re to this functionality

Thx

**Comment by yjacolin** [comment]
Please use the QGIS bugtracker instead of the QGIS Website ;) See http://qgis.org/en/site/getinvolved/development/bugreporting.html#bugs-features-and-issues
