### ISSUE TITLE
complex kml saving (subfolder-based on field/icon size...)

### ISSUE THREAD

**Issue by barthoum** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#387]
Hello,

Kml/Kmz formats allow users to rank your data in folder and subfolder ( when y ou have a lot of data,associate with the minLOD and MaxLod settings, it's very useful).  Arcgis for exemple can do that with the attribute "FolderPath" of your folderpath. It would be great to implement that functionality.

The possibility to rank that folder alphabetically would also be great

I know a website which is capable to do that kind of thing. There is a lot of useful settings you can choose for kml . A free use is available for 200 rows, if you want to see an exemple of what i am speaking

http://www.earthpoint.us/

Implement that functionality in qgis core or an extension would be great

**Comment by DelazJ** [comment]
Hi,
This repository is dedicated to [QGIS Website](www.qgis.org) issues. Please report this in the [issue tracker](http://hub.qgis.org). More information at http://qgis.org/en/site/getinvolved/development/bugreporting.html.

May I know what makes you choose to report this issue in this repository?

**Comment by barthoum** [comment]
Simply, my stupidity and perhaps the fact that there is no easy way to register on qgis hub...

All my apologizes
