### ISSUE TITLE
Broken Link to 2.18 Visual Changelog on Homepage

### ISSUE THREAD

**Issue by CAM-Gerlach** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#389]
Sorry if this is the wrong place for this (first ever use of Github), but the link to the 2.18 visual changelog on the homepage (and possibly elsewhere?) is currently 404'ed in that no such page appears to exists (at least in a user-obvious place). The link (on [line 37 of themes/qgis-theme/index.html](https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/index.html#L3)  ) was updated three days ago in 5a58c57 by @jef-n but as of now (2016-10-24 2300 UTC) does not function as described above, possibly from the start. Looking forward to seeing it whenever its ready.

**Comment by DelazJ** [comment]
This is indeed the right place to report. Actually, the changelog is not yet ready and its link has been published earlier. No worry, it'll be released in next days. see http://osgeo-org.1560.x6.nabble.com/Broken-Link-to-2-18-Visual-Change-Log-td5292394.html

**Comment by CAM-Gerlach** [comment]
Thanks. I figured something like that might be the case. Perhaps it might help avoid to user confusion if you temporarily replaced the active, 404'ed hypertext with unlinked text like "Visual Changelog (Under Construction)" to make this clear to the user, then rollback the change once the changelog goes live? Up to you all, of course...if you think that's beneficial, we can close this as soon as it gets merged; otherwise we can close this now.

**Comment by CAM-Gerlach** [comment]
I've got a PR ready to go for the former, if you think it would be helpful.

**Comment by DelazJ** [comment]
If you have a PR that improves the situation, please propose it and it'll be reviewed

**Comment by CAM-Gerlach** [comment]
Okay, thanks!

**Comment by CAM-Gerlach** [comment]
...And the changelog is up, so we can close.
