### ISSUE TITLE
Anchors untranslated?

### ISSUE THREAD

**Issue by pcav** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#39]
AFAIK, anchors (internal links in the page) are not translated. So in translated pages, internal links will remain in English. This may or may not be a problem, it should be taken into account.

**Comment by rduivenvoorde** [comment]
we have to check otto but in the docs it is not a problem either: see russion translations
http://docs.qgis.org/2.0/html/ru/docs/user_manual/introduction/qgis_gui.html#menu-bar

but I know that it sometimes means that you need some rst-ref logic to make think work...

**Comment by m-kuhn** [comment]
Is this an issue for language specific SEO?

**Comment by DelazJ** [comment]
Still a valid issue? AFAIK, anchors are translated. Any example of untranslated anchor, @pcav ?

**Comment by DelazJ** [comment]
I'm not sure I understood the initial report but is this still valid? @pcav ?

**Comment by mbernasocchi** [comment]
closing as stale,  If this is still relevant, please reopen
Cheers

**Comment by mbernasocchi** [comment]
@pcav I leave this closed as it seems fixed according to @DelazJ
