### ISSUE TITLE
QGIS 2.18.0 non available for Mac OS X!

### ISSUE THREAD

**Issue by Crapauline** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#391]
Hi!

I try to download QGIS 2.18 for Mac OS X, but when I visit the download page, the latest version downloadable is 2.16.3 (that always crashes when I want to build maps...). Can you please put version 2.18.o for Mac OS X ?

**Comment by DelazJ** [comment]
hi,
It takes time to build QGIS for every supported platform. So no worry, 2.18 on MacOS will be available hopefully in next days.

What is strange is 2.16.3 crashing every time. I'm also on macOS and do not experiment that. This imho deserves a bug report at www.hub.qgis.org. See http://qgis.org/en/site/getinvolved/development/bugreporting.html#reporting-issues-on-qgis-applications for more explanation and needed details.

**Comment by Crapauline** [comment]
Hi DelazJ!

Thank you very much for your quick answer! 

I also don't understand for the crash, because until Tuesday, it worked well! I will report it

**Comment by DelazJ** [comment]
Closing as 2.18 is available now for Mac
