### ISSUE TITLE
Future of getinvolved/meetings section

### ISSUE THREAD

**Issue by alexbruy** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#395]
This section contains pages for almost all developer and user meetings. But most of the pages are empty, does it worth to keep them? Maybe we can have single page with links to blogposts/reportbacks?

**Comment by rduivenvoorde** [comment]
@alexbruy yes, I think that is a good idea. I think(!) one of the reasons to list all the meetings was to give some gratitude to sponsors and organisers. But you are right, we can better do that by creating one big page (untill it get's to big, and we can split up per year), with a small paragraph per meeting with links as you say.
