### ISSUE TITLE
Page menus should be switchable

### ISSUE THREAD

**Issue by pcav** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#4]
on a per page basis (short pages>no menu, long page>shoulder menu)

**Comment by jj0hns0n** [comment]
the page menu is gone for now, we can make it show up in the slideout side menu or as another submenu under the main one. @pcav what is your preference?

**Comment by rduivenvoorde** [comment]
I think this should not be done per page basis (remember we want to reuse this also for the much bigger documentation site).
I prefer to do this based on the information structure:
- website pages (that is no real content) NO bar
- content pages (mostly from rst)  BAR

**Comment by pcav** [comment]
IMHO the bar is unnecessary for short pages - if website has only short pages, I think it's fine

**Comment by jj0hns0n** [comment]
@rduivenvoorde @pcav I think we get the sidebar/TOC there to be optionally shown/included and just turn it off for the very custom pages.

**Comment by pcav** [comment]
This is easy:

html_sidebars = {'download': ['localtoc.html'], 'other': ['localtoc.html']} 

IMHO this can be closed

**Comment by rduivenvoorde** [comment]
yep, we are using this already.
