### ISSUE TITLE
Calling plugin from standalone script has a bug because the use of progress bar

### ISSUE THREAD

**Issue by juanmafont** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#400]
I have a standalone script that call:

general.runalg("qgis:linestopolygons",inFile,outFile)

and only the first feature is write to outputfile.

I discover that if I comment out the line that says:  "progress.setPercentage(int(current * total))"  into the file /usr/share/qgis/python/plugins/processing/algs/qgis/LinesToPolygons.py then all features are write to output file.

  Tested in Linux Qgis 2.18.1

**Comment by DelazJ** [comment]
Hi,
Please report this in the [issue tracker](http://hub.qgis.org) or ask for help in one of qgis [support channels](http://qgis.org/en/site/forusers/support.html).
This repository is dedicated to issues you may find when browsing [QGIS Website](http://qgis.org/).
Thanks.
Closing
