### ISSUE TITLE
 "save to"  full layer recorded in order, but selection of features not in same order ?

### ISSUE THREAD

**Issue by juanmafont** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#401]
Qgis desktop  (Linux Qgis 2.18.1) 

I noticed that when I "save to" a full layer to a file, all features are save in the same order than original, but when save only a selection of features the order is diferent .  Will be possible saving in same order when is a selection of features ?   Thanks.

**Comment by DelazJ** [comment]
Hi,
Please report this in the [issue tracker](http://hub.qgis.org) or ask for help in one of qgis [support channels](http://qgis.org/en/site/forusers/support.html).
This repository is dedicated to issues you may find when browsing [QGIS Website](http://qgis.org/).
Thanks.
Closing

**Comment by juanmafont** [comment]
Sorry, jeje, I will do it so...
