### ISSUE TITLE
 Ayuda por favor me aparece este error en la nueva versión "No se pudo cargar el complemento MetaSearch"

### ISSUE THREAD

**Issue by maarochaz** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#404]
Error de Python: No se pudo cargar el complemento MetaSearch debido a un error al llamar a su método classFactory() Vea el registro de mensajes (Error de Python) para más detalles.

No se pudo cargar el complemento MetaSearch debido a un error al llamar a su método classFactory() 

ImportError: No module named pyproj 
Traceback (most recent call last):
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/MARIO/.qgis2/python/plugins\MetaSearch\__init__.py", line 34, in classFactory
    from MetaSearch.plugin import MetaSearchPlugin
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MARIO/.qgis2/python/plugins\MetaSearch\plugin.py", line 32, in 
    from MetaSearch.dialogs.maindialog import MetaSearchDialog
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MARIO/.qgis2/python/plugins\MetaSearch\dialogs\maindialog.py", line 48, in 
    from owslib.wfs import WebFeatureService
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\owslib\wfs.py", line 18, in 
    from .feature import wfs100, wfs110, wfs200
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\owslib\feature\wfs100.py", line 27, in 
    import pyproj
  File "C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named pyproj

Versión de Python: 2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)] 
Versión de QGIS: 2.18.1 Las Palmas, 3e73840 

Ruta de Python:
C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python
C:/Users/MARIO/.qgis2/python
C:/Users/MARIO/.qgis2/python/plugins
C:/PROGRA~2/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win32.egg
C:\PROGRA~2\QGIS2~1.18\bin\python27.zip
C:\PROGRA~2\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~2\QGIS2~1.18\bin
C:\PROGRA~2\QGIS2~1.18\apps\Python27
c:\progra~2\qgis2~1.18\apps\python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
c:\progra~2\qgis2~1.18\apps\python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg
c:\progra~2\qgis2~1.18\apps\python27\lib\site-packages\python_dateutil-2.2-py2.7.egg
c:\progra~2\qgis2~1.18\apps\python27\lib\site-packages\pytz-2014.2-py2.7.egg
c:\progra~2\qgis2~1.18\apps\python27\lib\site-packages\shapely-1.2.18-py2.7-win32.egg
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\PIL
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:/Users/MARIO/.qgis2//python
C:\Users\MARIO\.qgis2\python\plugins\MetaSearch\ext-libs
C:\Users\MARIO\.qgis2\python\plugins\mmqgis/forms

**Comment by DelazJ** [comment]
Hi, 
Please ask for help in qgis-user list (see [support channels](http://qgis.org/es/site/forusers/support.html)).
This repository is actually dedicated to issues related to the [main website](http://qgis.org/) of QGIS project.
