### ISSUE TITLE
Toggling Full Screen broken

### ISSUE THREAD

**Issue by MtnBiker** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#411]
The Toggling Fullscreen is largely broken: 

View > Enter Full Screen works, but then there is no Exit Full Screen (still says Enter Full Screen). 

And there is an item View > Toggle Full Screen [F11], but it only toggles on, not off.

This seems to be long standing as Stackoverflow has numerous reports with both Windows and macOS.

My setup is macOS Sierra and QGIS via http://www.kyngchaos.com/software/qgis:
    
    QGIS version
    2.18.2
    QGIS code branch
    Release 2.18
    Compiled against Qt
    4.8.6
    Running against Qt
    4.8.6
    Compiled against GDAL/OGR
    2.1.2
    Running against GDAL/OGR
    2.1.2
    Compiled against GEOS
    3.5.1-CAPI-1.9.1
    Running against GEOS
    3.5.1-CAPI-1.9.1 r4246
    PostgreSQL Client Version
    9.4.9
    SpatiaLite Version
    4.3.0a
    QWT Version
    6.1.3
    PROJ.4 Version
    492
    QScintilla2 Version
    2.9.1

**Comment by DelazJ** [comment]
HI,
Please do not report application issues in this repository. This one is dedicated to [QGIS website](http://qgis.org/) issues. Report either in the application [issue report ](http://hub.qgis.org) (preferably) or in the qgis-developer [mailing list](http://qgis.org/en/site/getinvolved/mailinglists.html#qgis-mailinglists).

Thanks

**Comment by MtnBiker** [comment]
Sorry, wasn't paying enough attention. The first link you gave isn't relevant as far as I can tell. But I'll try the second.

**Comment by DelazJ** [comment]
No worries. You mean this link http://hub.qgis.org? IT IS the place to report application issues. See http://hub.qgis.org/projects/quantum-gis/issues
