### ISSUE TITLE
Can't download any QGIS installer

### ISSUE THREAD

**Issue by bbonczek** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#413]
Hello, 

I think, there might be something wrong with download section on your website. Afted going to [downloads on your website](http://qgis.org/en/site/forusers/download.html) and clicking any of the links to installer. New tab opens and I'm being redirected to about:blank on Chrome and Firefox, and to http://qgis.org/downloads/QGIS-OSGeo4W-2.14.11-1-Setup-x86_64.exe on IE. Only thing visible is white color.

Checked that on Chrome 55, IE11 and Mozilla Firefox 40.0.3.

**Comment by andreasneumann** [comment]
Hi,

Just checked. Works fine for me. Tested with both 2.14 and 2.18 64bit in Chrome on Windows.

Andreas

**Comment by DelazJ** [comment]
Also works fine (including windows related links) in Firefox on os x

**Comment by bbonczek** [comment]
Yup, it works now, I guess it was some temporary problem. I'm closing issue then. Thanks ;)
