### ISSUE TITLE
Custom raster provider

### ISSUE THREAD

**Issue by Vando141** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#422]
Hi,

Is it possible to make attributes of QgsRasterLayer protected to be able to customize provider creation.

It can be usefull to create a custom class, which inherit QgsRasterDataProvider and implement data access in it. 
This will allowed to create custom provider without plugins.

Thanks,
Clément

**Comment by yjacolin** [comment]
Please could you ask such question to the developer mailing list: http://qgis.org/en/site/getinvolved/mailinglists.html#qgis-mailinglists and http://qgis.org/en/site/getinvolved/faq/index.html#how-to-ask-a-qgis-question

Thanks,
