### ISSUE TITLE
QGIS 2.18.5 freezes activate/deactivate e refreshing layers in a projects

### ISSUE THREAD

**Issue by Antoviscomi** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#423]
In QGIS 2.18.4/2.14.3 and 2.18.5/2.14.4  on Windows 7 and Debian8 x64 (i7 4790 @ 4.00+4.00GHz an 16GB ram) activation or deactivation of one of layer loaded in a view causes a freeze or soft crash:
- QGIS spends about of 15-20 seconds to make the canvas refreshing (independently from the amount of records in the shapefiles (42 or 15000)  );
- sometimes canvas refreshing causes QGIS do not responds for about 30-40 seconds.
- when trying to clic or move the canvas refreshing blocks for about 10-20 seconds. 

 p.s. the projects I've tried  do not contain raster layers.

**Comment by yjacolin** [comment]
Thanks for the report, unfortunately it is not the right place to do it, this is the QGIS Website repository. Could you have a look here to post in the current repository: http://qgis.org/en/site/getinvolved/development/bugreporting.html#bugs-features-and-issues (http://hub.qgis.org/projects/quantum-gis/issues).

Thanks,

Y.
