### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by MichelBohms** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#427]
http://www.qgis.org/nl/site/forusers/download.html

Gegevenssets and voorbeeld-gegevensset beschikbaar are dead links:

ex: 
![image](https://cloud.githubusercontent.com/assets/22189872/24927313/ead33204-1efe-11e7-9da5-a36c3e4d13a5.png)

**Comment by DelazJ** [comment]
To fix this, I think we need a fallback system that ensures that when the last released application (eg 3.0) does not yet have a documentation, we show the english testing page instead.

**Comment by DelazJ** [comment]
Should be fixed now: unexisting language fall back to english
