### ISSUE TITLE
web site open problem

### ISSUE THREAD

**Issue by stzdzyhs** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#428]
Hello, 
First I would very appreciated that create this great software!

In recently days, when I access the Qgis home: http://www.qgis.org or http://doc.qgis.org/, the page shows:

One more step
Please complete the security check to access docs.qgis.org
and need to input a CAPTCHA.

and the text on the bottom of the page is:

Cloudflare Ray ID: 34f28e0867c0332b • Your IP: 183.240.20.* • Performance & security by Cloudflare

However, for some reason, the captcha image can not be displayed.

Could you help to have a check ?

Thank you very much !

**Comment by rduivenvoorde** [comment]
@stzdzyhs mmm, strange.

Never seen that. But I will ask support of cloudflare and point to this issue. Please do not close it yet

**Comment by stzdzyhs** [comment]
@rduivenvoorde
Thanks! 
I search the cloundflare web site , but can not find their troubleshoot email, 
however, one of their support pages, 
https://support.cloudflare.com/hc/en-us/articles/200171816-Why-do-I-see-an-Access-Restricted-CloudFlare-Challenge-Page-from-anti-virus-cloudflare-com-

It seems that the qgis.org blocked my ip, but I really did not do any bad thing :(

**Comment by DelazJ** [comment]
@stzdzyhs maybe the captcha issue is related to their note 
> Note: You must have cookies enabled to pass the captcha

**Comment by stzdzyhs** [comment]
@DelazJ 
I always did not disable any cookie, I am using Ubuntu firefox, and I think in default, it enable cookie.
In 3-4 days before, I still can access qorg.org, but can not after that....
for ensure, I also tried another computer with Windows Chrome browser, also showed 
"One more step" page
Thanks.

**Comment by stzdzyhs** [comment]
more info on "One more step" page is:

Why do I have to complete a CAPTCHA?
Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.

What can I do to prevent this in the future?
If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.
If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.

I can not gurantee that 100% without a virus, but just looks like my ip is blocked...

**Comment by stzdzyhs** [comment]
At last, I found a workaround for this:
set the User-Agent of the browser
I am not sure why this is related to User-Agent, however, after set User-Agent to "iphone3":
"Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16"
I can acess qgis.org again, and no more "One more step" page !
Thanks.

**Comment by stzdzyhs** [comment]
oops, setting User-Agent just work for awhile, still often encounter the annoying "One more step"...

**Comment by DelazJ** [comment]
What's the status of this report? Fixed? To be closed?

**Comment by rduivenvoorde** [comment]
I don't know @stzdzyhs  is the only one who has this, never seen this elsewhere. 
@stzdzyhs where are you located? Is it possible that that is a cloudflare problem?
One solution for the website is to use: nocache.qgis.org as that one is set up to NOT be cached by cloudflare.
For docs there is not such a solution though as that is a different subdomain.
