### ISSUE TITLE
Not able to override sphinx css file import

### ISSUE THREAD

**Issue by yulka** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#43]
Sphinx theme includes one css file that I'd like to drop and not use at all. I am able to import custom css files, but I can't override the existing ones. Basically, how can I do the following: do not include this css file.

**Comment by jj0hns0n** [comment]
@yulka we can close this now right?

**Comment by rduivenvoorde** [comment]
I would like to keep this open.

We did some tricks to make things work. One of them is a full copy of bootstrap into the theme dir. 

This should not be nessecary, same with this problems. If we want different includes then the bootstrap-theme we must fix that in in sphinx way.

Maybe @yulka can make this problem a little more precise, then I can have a look into it. I bed we have to override a part of one of the boostrap theme htmls

**Comment by rduivenvoorde** [comment]
@yulka can you please provide some extra information which file(s) exactly you want to override (which is just include after the original one isn't it?).

I can look into this, and if succesfull, we can remove the inclusion of our own copy of bootstrap which we now have in our theme...

**Comment by yulka** [comment]
The default sphinx css file includes styles for wide screens (responsive-1200px-min.less). I did not want to include this stylesheet to have more control over the layout and things like a slideshow. However, if you think we should include these styles, we can close this ticket. In case this is not clear, please let me know and I'll include some more details.

**Comment by yulka** [comment]
I wonder if there is an option to use less instead of css in sphinx. In qgis-styles.less I am importing mixins and variables:

@import "bootstrap-2.3.2/less/variables.less";
@import "bootstrap-2.3.2/less/mixins.less";

Ideally these files would be in the sphinx theme static folder, so we don't keep a copy in the theme dir. If this is not possible, we should add documentation that when we update the sphinx theme, we should also update bootstrap less files, so that the versions don't go out of sync.
