### ISSUE TITLE
qgis 2.18.7 problem with the natural neighbor algorithm

### ISSUE THREAD

**Issue by wodphoenix** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#432]
I'm trying to run an algorithm to build a raster by points. I get this error
`Запуск алгоритма Natural neighbour...
grid_gridding "Natural Neighbour" -TARGET_DEFINITION 0 -SHAPES "C:\Users\empir\AppData\Local\Temp\processingfd929b3124d0434198628c2e6046d67c\1495019291.762.shp" -FIELD "BR" -SIBSON true -TARGET_USER_XMIN 21767.58 -TARGET_USER_XMAX 29609.01 -TARGET_USER_YMIN 36510.05 -TARGET_USER_YMAX 45564.78 -TARGET_USER_SIZE 10 -TARGET_USER_FITS 1 -TARGET_OUT_GRID "C:\Users\empir\AppData\Local\Temp\processingfd929b3124d0434198628c2e6046d67c\ec18e3db7b0b4a35b9f80bc28b78731c\TARGETOUTGRID.sdat"

D:\Program Files\QGIS 2.18\bin>set SAGA=D:\Program Files\QGIS 2.18\apps\saga-ltr

D:\Program Files\QGIS 2.18\bin>set SAGA_MLB=D:\Program Files\QGIS 2.18\apps\saga-ltr\modules

D:\Program Files\QGIS 2.18\bin>PATH=D:\Program Files\QGIS 2.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg\shapely\DLLs;D:\Program Files\QGIS 2.18\apps\Python27\DLLs;D:\Program Files\QGIS 2.18\apps\Python27\lib\site-packages\numpy\core;D:\Program Files\QGIS 2.18\apps\qgis\bin;D:\Program Files\QGIS 2.18\apps\grass\grass-7.2.0\lib;D:\Program Files\QGIS 2.18\apps\grass\grass-7.2.0\bin;D:\Program Files\QGIS 2.18\apps\Python27\Scripts;D:\Program Files\QGIS 2.18\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\WBem;D:\Program Files\QGIS 2.18\apps\saga-ltr;D:\Program Files\QGIS 2.18\apps\saga-ltr\modules

D:\Program Files\QGIS 2.18\bin>saga_cmd grid_gridding "Natural Neighbour" -TARGET_DEFINITION 0 -SHAPES "C:\Users\empir\AppData\Local\Temp\processingfd929b3124d0434198628c2e6046d67c\1495019291.762.shp" -FIELD "BR" -SIBSON true -TARGET_USER_XMIN 21767.58 -TARGET_USER_XMAX 29609.01 -TARGET_USER_YMIN 36510.05 -TARGET_USER_YMAX 45564.78 -TARGET_USER_SIZE 10 -TARGET_USER_FITS 1 -TARGET_OUT_GRID "C:\Users\empir\AppData\Local\Temp\processingfd929b3124d0434198628c2e6046d67c\ec18e3db7b0b4a35b9f80bc28b78731c\TARGETOUTGRID.sdat"
Unknown option 'SIBSON'
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 2.3.2 (64 bit)

____________________________
library path: D:\Program Files\QGIS 2.18\apps\saga-ltr\modules\
library name: grid_gridding
library : Gridding
tool : Natural Neighbour
author : O.Conrad (c) 2008
processors : 8 [8]
____________________________

Usage: saga_cmd grid_gridding 3 [-SHAPES ] [-FIELD ] [-TARGET_DEFINITION ] [-TARGET_USER_SIZE ] [-TARGET_USER_XMIN ] [-TARGET_USER_XMAX ] [-TARGET_USER_YMIN ] [-TARGET_USER_YMAX ] [-TARGET_USER_FITS ] [-TARGET_TEMPLATE ] [-TARGET_OUT_GRID ] [-METHOD ] [-WEIGHT ]
-SHAPES: Points
Shapes (input)
-FIELD: Attribute
Table field
-TARGET_DEFINITION: Target Grid System
Choice
Available Choices:
[0] user defined
[1] grid or grid system
Default: 0
-TARGET_USER_SIZE: Cellsize
Floating point
Minimum: 0.000000
Default: 1.000000
-TARGET_USER_XMIN: Left
Floating point
Default: 0.000000
-TARGET_USER_XMAX: Right
Floating point
Default: 100.000000
-TARGET_USER_YMIN: Bottom
Floating point
Default: 0.000000
-TARGET_USER_YMAX: Top
Floating point
Default: 100.000000
-TARGET_USER_FITS: Fit
Choice
Available Choices:
[0] nodes
[1] cells
Default: 0
-TARGET_TEMPLATE: Target System
Grid (optional input)
-TARGET_OUT_GRID: Target Grid
Grid (output)
-METHOD: Method
Choice
Available Choices:
[0] Linear
[1] Sibson
[2] Non-Sibsonian
Default: 1
-WEIGHT: Minimum Weight
Floating point
Maximum: 0.000000
Default: 0.000000

D:\Program Files\QGIS 2.18\bin>exit
Converting outputs
Загрузить результирующие слои

The following layers were not correctly generated.
Grid
You can check the log messages to find more information about the execution of the algorithm`

SIBSON - It seems that this parameter is not needed

**Comment by DelazJ** [comment]
@wodphoenix This repository is actually dedicated to issues you encounter while browsing the main website of QGIS project.

If you have issue with the application, please ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)) or report in the Desktop application bug tracker as stated in the [bug report page](http://qgis.org/en/site/getinvolved/development/bugreporting.html#bugs-features-and-issues).

Regards...
