### ISSUE TITLE
QGIS download not working

### ISSUE THREAD

**Issue by shekk** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#436]
I have tried several times now from different locations and over several days. I am unable to download the latest QGIS installer for Windows. The download always fails after about 30-50MB.

I'm using this link from the website:
http://qgis.org/downloads/QGIS-OSGeo4W-2.18.7-1-Setup-x86_64.exe

This is the following download:
QGIS Standalone Installer Version 2.18 (64 bit) (Windows)

Is there a mirror or some different source to download the installer from? And yes, I'm on broadband and I get a speed of about 0.5 - 1MB/s with this download.

I'd appreciate any help.

Cheers

**Comment by pcav** [comment]
Il 22 maggio 2017 02:06:46 CEST, shekk <notifications@github.com> ha scritto:
>I have tried several times now from different locations and over
>several days. I am unable to download the latest QGIS installer for
>Windows. The download always fails after about 30-50MB.
>
>I'm using this link from the website:
>http://qgis.org/downloads/QGIS-OSGeo4W-2.18.7-1-Setup-x86_64.exe
>
>This is the following download:
>QGIS Standalone Installer Version 2.18 (64 bit) (Windows)
>
>Is there a mirror or some different source to download the installer
>from? And yes, I'm on broadband and I get a speed of about 0.5 - 1MB/s
>with this download.
>
>I'd appreciate any help.
>
>Cheers
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/qgis/QGIS-Website/issues/436

Have you checked your antivirus?
Cheers.
-- 
Sent from mobile. Sorry for being short

**Comment by shekk** [comment]
Thanks, I've downloaded the installer from a different computer. It must have been something along the lines of Antivirus or similar. Thanks for the hint. Problem solved.
