### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by rmarkRCS** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#439]
QGIS was working, but now crashes on launch. Reinstallation did not fix the problem.
Mac OS 10.12.5, QGIS 2.18.7.
![screen shot 2017-05-26 at 6 15 50 am](https://cloud.githubusercontent.com/assets/12863758/26496188/55509c80-41db-11e7-9aae-d7c7492b7c89.jpg)

**Comment by DelazJ** [comment]
@rmarkRCS This repository is actually dedicated to issues you encounter while browsing the main website of QGIS project.

If you have issue with the application, please ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html) or report in the Desktop application bug tracker as stated in the [bug report page](http://qgis.org/en/site/getinvolved/development/bugreporting.html#bugs-features-and-issues)).
Thanks...
