### ISSUE TITLE
Detect platform and show appropriate download link by default

### ISSUE THREAD

**Issue by jj0hns0n** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#44]
The download page should auto-detect your platform from the UserAgent string and present the best download option most prominently.

Google does a very good job of this in my experience.

**Comment by m-kuhn** [comment]
I tried to research how to also detect the linux distribution (which is afaik not included in the UA string) but haven't found any solution for that so far...

**Comment by m-kuhn** [comment]
This can be closed.

Solved in a javascript manner it seems.
Thanks
