### ISSUE TITLE
Download Links for Mac Version gone?

### ISSUE THREAD

**Issue by ghost** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#446]
There is no download link for the Mac Version shown:

![image](https://user-images.githubusercontent.com/26527349/27305161-d89488b8-5540-11e7-9d2b-a0968948a9ee.png)

**Comment by DelazJ** [comment]
Seems to work perfectly here. Clicking the message in blue leads me to http://www.kyngchaos.com/software/qgis
Could you check again please?

**Comment by ghost** [comment]
Never mind. I was confused by the wording "dependency framework" and thought KyngChaos was just linking to some required framework.
