### ISSUE TITLE
Style with rule-based crash

### ISSUE THREAD

**Issue by ghost** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#448]
Hello everybody,

Since the last release 2.18.10, QGIS freeze by using rule-based style for layer.

Some tech info : 

QGIS version
2.18.10
QGIS code revision
59e0f78
Compiled against Qt
4.8.7
Running against Qt
4.8.7
Compiled against GDAL/OGR
1.11.3
Running against GDAL/OGR
1.11.3
Compiled against GEOS
3.5.0-CAPI-1.9.0
Running against GEOS
3.5.0-CAPI-1.9.0 r4084
PostgreSQL Client Version
9.5.2
SpatiaLite Version
4.3.0a
QWT Version
5.2.3
PROJ.4 Version
492
QScintilla2 Version
2.9.1

Thank for helping
Didier

**Comment by DelazJ** [comment]
Please do not report application issues in this issue tracker. This one is dedicated to [QGIS website](http://qgis.org/) matters. Report either in the application issue tracker or in the user/developer mailing list. More information at http://qgis.org/en/site/getinvolved/development/bugreporting.html#reporting-issues-on-qgis-applications or http://qgis.org/en/site/forusers/support.html.

Thanks.
