### ISSUE TITLE
QGIS

### ISSUE THREAD

**Issue by ffierm** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#449]
Dear All,

QGIS version | 2.18.9 | QGIS code revision | 3a16a4e

when I'm using: "Layer Properties", "Style", "Categorized", "Expression Dialog":
------------------------------
CASE
WHEN "field" = 'aaa' then  color_rgb( 10,20,30)
WHEN "field" = 'bbb' then  color_rgb( 100,200,222)
WHEN "field" = 'ccc' then  color_rgb( 25,50,75)
END
------------------------------
this code produced random colours insted the (wanted) RGB. What goes wrong?

Can You help me, pease?
 
Best regards,
ffier

**Comment by DelazJ** [comment]
This repository is actually dedicated to issues related to the [main website](http://qgis.org) of QGIS project.
So please ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)) with more details on what you did and what you expected or give a look to [QGIS documentation](http://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/vector_properties.html#categorized-renderer).

Regards,
DelazJ
