### ISSUE TITLE
rotate font problem

### ISSUE THREAD

**Issue by combo110** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#454]
Hello:
In "print composer", i need a rotate text then use "Rotation">90 to implement some effect.
In my pc, other software can load "@fonename" to write a rotate text,but QGIS can not load @ prefix fonts. Can you give me some advise? Thanks~!

**Comment by DelazJ** [comment]
With some delay, Please ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)).
This repository is actually dedicated to issues related to the [main website](https://qgis.org) of QGIS project.
