### ISSUE TITLE
Paypal donation page not linked

### ISSUE THREAD

**Issue by jtamuc** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#456]
On the donation page there does not appear to be a link or method to donate via credit card or paypal.

**Comment by andreasneumann** [comment]
Hi @jtamuc 

Can you please be more specific? What URL are you referring to?

http://www.qgis.org/en/site/getinvolved/donations.html seems to contain proper information and URLs.

Are you looking at another language? Or some other page?

Thanks,
Andreas

**Comment by jtamuc** [comment]
Looks like I was just on a slow internet connection and the paypal button
did not come up. Sorry for opening an issue. All is good.

Kind regards,

Jack
