### ISSUE TITLE
Multiple includes of bootstrap-2.3.2.js in header

### ISSUE THREAD

**Issue by eshon** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#46]
Multiple includes of bootstrap-2.3.2.js in header right now, causes a console error

view-source:http://new.qgis.org/html/en/site/index.html

**Comment by mach0** [comment]
I cannot find such an error 
@rduivenvoorde can this be closed?

**Comment by rduivenvoorde** [comment]
the actual problem is that we were not able to include the right bootstrap in the right way in the boostrap theme.

it is in now with a little hack. Actually I'm not convinced anymore that we should use the sphinx-bootstrap theme. 

Maybe we can remove it. Please let this one open.

**Comment by eshon** [comment]
After producing some more documentation websites using sphinx I agree, I think we can just include bootstrap separately in the headers and use regular sphinx in the future.
