### ISSUE TITLE
when i  open personal geodatabase is false in chinese ,but success in english.what is wrong with it?

### ISSUE THREAD

**Issue by z954134** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#461]
## Description

Include sentences with details describing the issue you have encountered (e.g., actual behavior, expected behavior, steps to reproduce).

## Checklist
> This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage.
If it's related to QGIS application or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [ ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
Please ask the question in the QGIS user list (see https://qgis.org/en/site/getinvolved/mailinglists.html#qgis-mailinglists). This is not a QGIS website issue
