### ISSUE TITLE
OpenTopoMap in Tile Server

### ISSUE THREAD

**Issue by LuGeomedios** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#469]
## Description

I´trying to insert OpenTopoMap in QGIS with the new Tile Server (XYZ) function.
When I do it for OpenStreetMap (as in the sample of "What is new in QGIS 2.18") with http://c.tile.openstreetmap.org/{z}/{x}/{y}.png everyting works, but when I change it to http://c.tile.opentopomap.org/{z}/{x}/{y}.png everything seems to go right at first moment but quicly everything starts to fail. 
The atacched image is a sample of the problem. The raster appears in the borders of the working area, or dissapears... the system does unpredictable things...

Any suggestion?
  Thanks in advance

## Checklist
> This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage.
If it's related to QGIS application or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [ ] I have added a link to the page concerned by the issue
![opentopomap_failure](https://user-images.githubusercontent.com/32068697/30548674-207e6baa-9c93-11e7-98c9-333307632041.jpg)

**Comment by DelazJ** [comment]
@LuGeomedios This doesn't seem to be a [qgis.org](http://qgis.org) issue, object of this bug tracker. If you are looking for help please refer to the qgis [support channels](http://qgis.org/en/site/forusers/support.html) mentioned above, in the issue report template.
Thank you for understanding.
