### ISSUE TITLE
We need to convey the fact that QGIS has Desktop, Server and Web Client offerings

### ISSUE THREAD

**Issue by timlinux** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#47]
# Problem

The front page does not convey the fact that you can also use QGIS as a map server and a web client.
# Proposed solution
- [ ] Replace download button with three boxes
- [ ] In the first box a picture of QGIS Desktop with a link to download underneath it
- [ ] In the second box, a graphic representing QGIS server with a link to installation procedure beneath it
- [ ] In the third box a picture of QGIS Web Client with a link beneath it to download
# Expected outcome

A person arriving at the QGIS home page should understand that QGIS can be used in these three contexts and have starting points to using each

**Comment by rduivenvoorde** [comment]
But maybe hard to make that a clean/clear message. What about adding just one image or button (in the gray area?) which should make it clear that there is more in the QGIS world then only desktop GIS. This button/image then should point to: 
http://new.qgis.org/html/en/site/about/features.html

**Comment by rduivenvoorde** [comment]
though not fully implemented, I think we changed enough on the frontpage, and need to beef up this page maybe:

http://new.qgis.org/html/en/site/about/features.html
