### ISSUE TITLE
QGIS crashes when adding/selecting raster layers and base maps

### ISSUE THREAD

**Issue by nayelica** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#471]
I recently installed the Openlayer plugging and suddenly QGIS started crashing when clicking on the Google hybrid basemap layer. I deleted and re-installed the plug and QGIS but the issue persisted. I thought he issue was the Open Layer plug in but it also  crashes with Quick map satellite base map but not with the street map. I also noticed that QGIS is crashing when adding any other type of raster layer/aerial photographs. Below is the error message:

Process:               QGIS [9322]
Path:                  /Applications/QGIS.app/Contents/MacOS/QGIS
Identifier:            org.qgis.qgis2
Version:               2.18.9 (2.18.9 [exported])
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           QGIS [9322]
User ID:               501

Date/Time:             2017-09-19 20:47:16.892 -0700
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        CC3B8B75-E1B7-3E88-12E3-99F67D310FD9

Sleep/Wake UUID:       85BEE627-C150-40E9-A6D0-6E080E79F83C

Time Awake Since Boot: 230000 seconds
Time Since Wake:       1200 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000190
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0x190:
--> 
    __TEXT                 000000010e50e000-000000010e9ec000 [ 4984K] r-x/rwx SM=COW  /Applications/QGIS.app/Contents/MacOS/QGIS

**Comment by yjacolin** [comment]
This issues forms is for QGIS WebSite. Please report to the QGIS application bug report: http://hub.qgis.org/
