### ISSUE TITLE
This is an documentation error, please report back to QGIS devs.

### ISSUE THREAD

**Issue by m-kuhn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#472]
Today after clicking the link on Google

![screen shot 2017-09-22 at 11 39 09](https://user-images.githubusercontent.com/588407/30738551-b9d33c64-9f8a-11e7-88e4-056f85ff017c.png)

**Comment by DelazJ** [comment]
Also got this while trying to view a documentation page (btw in a language other than en - happens with nl, fr, de at least). But I can't consistently reproduce it.

**Comment by m-kuhn** [comment]
I think one should grep the docs for this error and just disable it. It provides no pointers towards where the error happened and just spreads confusion.

**Comment by DelazJ** [comment]
see https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/languageswitch.html#L57

**Comment by rduivenvoorde** [comment]
@DelazJ @m-kuhn still have this? I do not.
This is some magic to retrieve the language and page and put people on a translated page after using the language drop down.
At that time had some troubles getting it to work for all different kind of possible links, and wanted people to let me know when still something goes wrong. Easy debuggable in the webbrowser by the way.

**Comment by m-kuhn** [comment]
I think it only happened to me once, I don't know how I would reproduce. I just followed the instructions and reported to the QGIS devs :stuck_out_tongue:

**Comment by noerw** [comment]
This is really bad UX, this should not be exposed with an alert (which doesn't even provide helpful information).

I can reproduce it by visiting https://qgis.org/en/site/forusers/download.
Appending `.html` to the URL resolves the issue.

**Comment by DelazJ** [comment]
Hi @noerw how did you arrive to that page without ending `html`?

**Comment by noerw** [comment]
This was in the QGIS 3.0 anouncement carousel element, before the link was fixed.
