### ISSUE TITLE
doc - Debian/Ubuntu install: minor typo issue

### ISSUE THREAD

**Issue by Yvan-Masson** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#477]
Hi,

I am not a native English speaker, but I think the following sentence (found in [1]) is incorrect (I think that "be" should be removed):

> ... which happens every month and will be include the updated dependencies,

Best regards,
Yvan

1. https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

**Comment by yjacolin** [comment]
Thanks!
