### ISSUE TITLE
Download: qgis_sample_data.tar.gz is not a gzip, but only a POSIX tar archive

### ISSUE THREAD

**Issue by a17r** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#478]
Apart from the wrong file suffix this makes the download needlessly big, so should be fixed.

https://qgis.org/downloads/data/qgis_sample_data.tar.gz

**Comment by rduivenvoorde** [comment]
@a17r I've created the tar file (and in my memory I used -z too...)... but you are right, the tar(.gz?) is 39Mb while the zip version (https://qgis.org/downloads/data/qgis_sample_data.zip next to it) is 22Mb.

Gzipped it now... Thanks for pointing out

**Comment by a17r** [comment]
Thanks for the quick fix!
