### ISSUE TITLE
QGIS Core Text

### ISSUE THREAD

**Issue by m-kuhn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#48]
On this page: http://new.qgis.org/html/en/site/getinvolved/index.html

The paragraph about QGIS Core talks only about core plugins, but core development is to a big part not related to core plugins but to the core libraries and application.

**Comment by rduivenvoorde** [comment]
hi matthias,

is this still the case in your view?
and if so, can you please provide better text (/me to so good in texts)

**Comment by m-kuhn** [comment]
Nope, that was solved in Nottingham. Maybe the terms _offered_ and _offering_ appear too close to each other. Replacing the second term by _presenting_ (or similar) would be good. The best would be to have a native speaker check this.
