### ISSUE TITLE
Debian repositories down?

### ISSUE THREAD

**Issue by ghost** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#484]
Not sure if this is the best place for this report, but all the Debian repositories are 404:
http://qgis.org/debian
http://qgis.org/ubuntugis
http://qgis.org/debian-nightly-release
http://qgis.org/ubuntugis-nightly-release
etc.

**Comment by DelazJ** [comment]
@ThatDan, this is the right place for a report. Thanks. Looks like some of the links are already fixed (the nightlies are still broken - @rduivenvoorde, is it normal?). 
Fyi, stuff are being moved to another server https://lists.osgeo.org/pipermail/qgis-user/2017-December/041166.html

**Comment by ghost** [comment]
I see. Things are back up now. Thanks!
