### ISSUE TITLE
Can not download for Windows

### ISSUE THREAD

**Issue by cjohnst5** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#485]
## Description

When I try to download any 4 of the QGIS installers for Windows found on this webpage, http://www.qgis.org/en/site/forusers/download.html#, I get an error. I'm taken to a webpage that says "Not Found The requested URL /downloads/QGIS-OSGeo4W-2.18.14-1-Setup-x86_64.exe was not found on this server." I downloaded the Windows 64-bit latest released installer a few days ago on my work computer, no problem. Now at home I'm unable to do so. 

- [x ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage.
- [ x] I have added a link to the page concerned by the issue

**Comment by ableymcabley** [comment]
I was having the same problem yesterday, and it's still happening today.

**Comment by cjohnst5** [comment]
I just tried to download it and it looks like it's working!

**Comment by DelazJ** [comment]
Ok, thanks.

**Comment by yjacolin** [comment]
There was an infrastructure upgrade yesterday :)
