### ISSUE TITLE
QGIS Help pages not accessible

### ISSUE THREAD

**Issue by ableymcabley** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#486]
I have installed QGIS Desktop, but when I click Help to go to the documentation on the website I get a "file not found" error.

The URL it is trying to link to is:
https://docs.qgis.org/2.18/en/docs/user_manual/

This is a screenshot of the error:
![error](https://user-images.githubusercontent.com/34205986/33631161-973d1786-da01-11e7-8535-636fb9d36a56.jpg)

**Comment by DelazJ** [comment]
@ableymcabley It should work now. Thanks for reporting.

**Comment by rduivenvoorde** [comment]
@DelazJ wow you are fast :-)

**Comment by DelazJ** [comment]
I had this page opened when your confirmation of fix arrived :-)
