### ISSUE TITLE
startup at stale path fails to load utils/python

### ISSUE THREAD

**Issue by Marwe** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#498]
[qgis_err_.txt](https://github.com/qgis/QGIS-Website/files/1701154/qgis_err_.txt)
## Description

I started qgis from a bash shell on a stale path (unmounted device), and QGIS fails to load QGIS-Utils and lacks python support.

Steps to reproduce:
* mount a device (e.g. usb key)
* cd /media/$USER/$label/
* remove the usbkey (without unmounting properly -> bash still on stale path)
* start qgis from that shell
* fails to start with Utils/python, error message as found on console/in window in attachment (German)
    * interesting and relevant is: test.test_support import *<br>&nbsp; File "/usr/lib/python2.7/test/test_support.py", line 669 SAVEDCWD = os.getcwd()<br>OSError: [Errno 2] file not found
* --noplugins does not help

Minor bug, only affecting special edge case.
* I guess, it could be fixed by try-excepting the os.getcwd() call properly

> Traceback (most recent call last):
>   File "", line 1, in
>   File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 21, in
>     standard_library.install_aliases()
>   File "/usr/lib/python2.7/dist-packages/future/standard_library/__init__.py",
> line 487, in install_aliases
>     from future.moves.test import support
>   File "/usr/lib/python2.7/dist-packages/future/moves/test/support.py", line
> 10, in
>     from test.test_support import *
>   File "/usr/lib/python2.7/test/test_support.py", line 669, in
>     SAVEDCWD = os.getcwd()
> OSError: [Errno 2] Datei oder Verzeichnis nicht gefunden

**Comment by andreasneumann** [comment]
Dear @Marwe,

This repo is about the QGIS website, not about QGIS software. For issues around QGIS, please use the issue tracker https://issues.qgis.org/ or any of the support channels available from https://www.qgis.org/en/site/forusers/support.html or https://www.qgis.org/en/site/forusers/commercial_support.html

I am closing this issue, because it is at the wrong repo. Please re-submit at issues.qgis.org
