### ISSUE TITLE
Windows 64 Installation package 2.18.16.1 contains version 2.18.10

### ISSUE THREAD

**Issue by Langlaeufer** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#499]
## Description

Wrong files in standalone installation Package
## Checklist

- [x ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [x ] I have added a link to the page concerned by the issue
https://www.qgis.org/de/site/forusers/download.html

**Comment by DelazJ** [comment]
@Langlaeufer I'm unable to confirm: i just download and install the 64 bits standalone version available at https://qgis.org and through all the process of installation, i've never seen mention of 2.18.10. Also the Help --> About menu shows 2.18.16 (code revision d473c3071a - as indicated at https://github.com/qgis/QGIS/releases)
Where did you get the 2.18.10 information?

**Comment by Langlaeufer** [comment]
I was updating from 2.18.14 or 15.  After updating i have progam menue entries with 2.18.16 but the running QGIS Programs shows 2.18.10 in headline and offers me update to 2.18.16 in status bar.

I tried it on a second computer with a new download without problems.
http://qgis.org/downloads/QGIS-OSGeo4W-2.18.16-1-Setup-x86_64.exe
I have to check again on the first computer after complete deinstallation.

**Comment by Langlaeufer** [comment]
Seems to be a problem with incomplete deinstallation

**Comment by DelazJ** [comment]
Thanks for the feedback
