### ISSUE TITLE
Top menu should be on a row

### ISSUE THREAD

**Issue by pcav** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#5]

**Comment by jj0hns0n** [comment]
@pcav can we close this one now? the top navbar will get the full css treatment shortly, but it has the minimum things for now, no submenus or slideout yet (see #12)

**Comment by pcav** [comment]
Still a suboptimal solution IMHO - better implement it upstream

**Comment by jj0hns0n** [comment]
@pcav current layout is suboptimal? or current implementation is suboptimal? I think the implementation is fine, but the layout is certainly not correct right now. I dont plan on futzing with it until the designer has taken a crack at the css herself.

**Comment by pcav** [comment]
I see a number of (rather minor, but significant) issues: e.g. search is on another block, so resizing the window puts it on a separate line.

My point however was that it is worth to put this as an option on the base theme, upstream.

**Comment by rduivenvoorde** [comment]
@pcav as @jj0hns0n explains, currently it is only flat html, to be make and behave better by doing css/bootstrap magic.

If we want to have something like this upstream, I reckon that we have to create a real pull request to them. But there are some problems to be solved before that I think. Also to make it more general usable, before they will be willing to pull our solution in.

**Comment by pcav** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Il 01/09/2013 09:21, Richard Duivenvoorde ha scritto:

> @pcav https://github.com/pcav as @jj0hns0n https://github.com/jj0hns0n explains,
> currently it is only flat html, to be make and behave better by doing css/bootstrap
> magic.
> 
> If we want to have something like this upstream, I reckon that we have to create a
> real pull request to them. But there are some problems to be solved before that I
> think. Also to make it more general usable, before they will be willing to pull our
> solution in.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/qgis/QGIS-Website/issues/5#issuecomment-23620217.
> 
> Yes, agreed.

---

Paolo Cavallini - Faunalia
www.faunalia.eu
Full contact details at www.faunalia.eu/pc
Nuovi corsi QGIS e PostGIS: http://www.faunalia.it/calendario
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.14 (GNU/Linux)
Comment: Using GnuPG with Icedove - http://www.enigmail.net/

iEYEARECAAYFAlIi9IcACgkQ/NedwLUzIr7zwgCglXp3ZEhpxFvU5lbzsVAWVm0u
QGAAoKPNpsnR/GPdn9Xe5YUqLgJ/hcSZ
=JwKw
-----END PGP SIGNATURE-----
