### ISSUE TITLE
Empty response when attempting to download any of the Windows QGIS installation files

### ISSUE THREAD

**Issue by A-Krull** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#503]
So the title pretty much says it all.

When attempting to download the Windows installations files nothing happens - instead I am informed by my browser that download.osgeo.org did not send any data. ERR_EMPTY_RESPONSE.

- cheers

**Comment by rduivenvoorde** [comment]
Yep. We know. Is just too busy. Too many people want QGIS3 NOW.

We have 3 servers.. all are eaten now...

Please try later
