### ISSUE TITLE
Standalone Windows Installer V 3.00

### ISSUE THREAD

**Issue by Warren735** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#504]
Am I alone in having trouble with the Standalone Windows Installer for V3,00?
I have tried on 2 computer, both running Win10Home

In each case the install progresses up until making Windows directory start\...
The installer hangs and will not complete task.
Thanks

**Comment by rduivenvoorde** [comment]
@Warren735 this is the issue/bug tracker for the QGIS Website. On issues.qgis.org you find the one for the application, but... I just tested the installer and for me it installs flawlessly. Though that is Win10 Pro.
Better to first ask this on the QGIS-User mailing list: https://qgis.org/en/site/getinvolved/mailinglists.html#qgis-mailinglists

Closing this one as not about Website
