### ISSUE TITLE
Qgis 3.0 Import DXF/DWG

### ISSUE THREAD

**Issue by tiZeus** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#508]
## Description

Through the PROJECT / IMPORT DXF-DWG path, Qgis3.0 provides the user with only the ability to import Geopackeg only.
The functionality of the mask or its title should probably be reviewed.

## Checklist
![2018-03-24 17_11_20-qgis](https://user-images.githubusercontent.com/37745272/37866134-a9c398e6-2f86-11e8-8cdc-a7a8d7b027aa.png)

![cattura](https://user-images.githubusercontent.com/37745272/37866100-14ec402e-2f86-11e8-89dc-dc226c7de413.PNG)

![1](https://user-images.githubusercontent.com/37745272/37866136-ad957ffc-2f86-11e8-9fe3-bb497f15244c.PNG)

**Comment by DelazJ** [comment]
Dear @tiZeus,
Thanks for your report but this issue tracker is for QGIS website (ie anything you find when browsing https://qgis.org), not for the application. Please report your issue in the [application issue tracker] (https://issues.qgis.org).
I'm then closing the report.
Thanks for your understanding.
