### ISSUE TITLE
Installation repositories 3.x for Ubuntu 

### ISSUE THREAD

**Issue by AxxL** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#509]
## Description

The [Repository list](https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu) for Ubuntu is a bit hard to understand. You write that 3.0.x is available at https://qgis.org/debian and it seems like it is not an will not be due to GDAL requierements (see footnote 5 on that page: "3.0 and above only available with ubuntugis (plain xenial lacks GDAL2)").

Therefore 3.0.x isn't available at https://qgis.org/debian. Maybe it is for everything newer than xenial, maybe not.

A bit down below you have the "Supported distribution versions" which makes not clear that there is a difference between Ubuntu 16.04 (LTS) and QGIS 3. It is for QGIS 2. I could use Ubuntu 16.04 and update GDAL for myself, but - well - therefore are the packages on UbuntuGIS repository.

## Advice

Make a matrix and list the possibilities.

```
| Operating System / QGIS Version | 3.x.x | 2.x.x | 2.99 master | Remarks                                                     |
|---------------------------------+-------+-------+-------------+-------------------------------------------------------------|
| http://qgis.org/debian          |       |       |             |                                                             |
| Ubuntu 16.04 LTS                | no[1] | yes   | no[1]       | Doesn't provide GDAL2 in its repository, so no V3 available |
| Ubuntu 18.04 LTS                | yes   | yes   | yes         |                                                             |
| Debian 6                        |       |       |             |                                                             |
| Debian 7                        |       |       |             |                                                             |
| Debian 8                        |       |       |             |                                                             |
|---------------------------------+-------+-------+-------------+-------------------------------------------------------------|
| http://qgis.org/debian-ltr      | no    | yes   | no          |                                                             |
| Ubuntu 12.04 LTS                | no    | no    | no          | We don't recommend this anymore                             |
| Ubuntu 16.04 LTS                | no[1] | yes   | no[1]       | Doesn't provide GDAL2 in its repository, so no V3 available |
| Ubuntu 18.04 LTS                | yes   | yes   | yes         |                                                             |
| Debian 6                        |       |       |             |                                                             |
| Debian 7                        |       |       |             |                                                             |
| Debian 8                        |       |       |             |                                                             |
|---------------------------------+-------+-------+-------------+-------------------------------------------------------------|
| http://qgis.org/ubuntugis       |       |       |             |                                                             |
| Ubuntu 16.04 LTS                | yes   | yes   | yes         |                                                             |
| Ubuntu 18.04 LTS                | yes   | yes   | yes         |                                                             |
| Debian 6                        |       |       |             |                                                             |
| Debian 7                        |       |       |             |                                                             |
| Debian 8                        |       |       |             |                                                             |
| http://qgis.org/ubuntugis-ltr   |       |       |             |                                                             |
| Ubuntu 16.04 LTS                | yes   | yes   | yes         |                                                             |
| Ubuntu 18.04 LTS                | yes   | yes   | yes         |                                                             |
| Debian 6                        |       |       |             |                                                             |
| Debian 7                        |       |       |             |                                                             |
| Debian 8                        |       |       |             |                                                             |
```

I'm not exactly sure if this matrix is correct and what is right for the Debian versions. You could tranform it also to show which QGIS Versions are suppported in which repository.

Right now it's not very clear which repository supports which version for which Operating System. But since the repositories are the nice concept of Ubuntu it is obvious to differ what's part of them.

I use Ubuntu 16.04 right now and will switch to Ubuntugis repository.

Page connected to this issue: Repository list: https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

**Comment by nickbearman** [comment]
Yes, I agree I think this could be clarified. Thanks to @AxxL for raising this. For example, I add the 'https://qgis.org/ubuntugis' repository and installed QGIS, expecting version 3.x and got version 2.x! Although reading the table above, I would have done the same thing (I think). 

I suspect many of this problems are related to people not getting their head around Ubuntu repositories (myself included!) so if anyone knows of a good explanation, we could also link to it from this page. 

I will happy write some updates to this, if someone can point me to some useful resources.

**Comment by Andre-J** [comment]
QGIS nightly should be 3.1.x master by now. Instead of providing a matrix that users will not understand either, I suggest to put that into the QGIS installer, read the ubuntu/debian version from the OS and compare it with the sources list. Check the QGIS/ubuntugis keys also in advance. In case of mismatch, quit the installer with an appropriate note saying what the user can get for his OS, and what repo, ppa and key he needs to add for that.

It should be added that you can obtain older versions without qgis.org too, either from the ubuntu or debian repo, or from ubuntugis stable or unstable.

**Comment by jef-n** [comment]
> The Repository list for Ubuntu is a bit hard to understand. You write that 3.0.x is available at https://qgis.org/debian and it seems like it is not an will not be due to GDAL requierements (see footnote 5 on that page: "3.0 and above only available with ubuntugis (plain xenial lacks GDAL2)").
> 
> Therefore 3.0.x isn't available at https://qgis.org/debian. Maybe it is for everything newer than xenial, maybe not.

Footnote 5 is referenced in the xenial row.  So it applies only to xenial.

> A bit down below you have the "Supported distribution versions" which makes not clear that there is a difference between Ubuntu 16.04 (LTS) and QGIS 3. It is for QGIS 2.

Why not?   That line has the reference to footnote 5 and tells you that 3.x is available for xenial, but only with ubuntugis.   So the information is there.

> I could use Ubuntu 16.04 and update GDAL for myself, but - well - therefore are the packages on UbuntuGIS repository.

How is that relevant?  If you update GDAL from source yourself you'll still have to run you own builds  as the available packages will likely still not work.

**Comment by reginaldc** [comment]
Would it be hard to make a distinction between debian and ubuntu?
As a user I go to the qgis downloadpage to find a qgis version (2.18.18 or 3.01 or whatever version) for my ubuntu version. It would be handy if there was a heading for the latest version of ubuntu with all the working versions of qgis to choose from.
It would also be great to install qgis 3.01 next to an existing install of a qgis 2 version. One could then call qgis 3.01 in the console by entering qgis3 (like you call python3).

Regards,

**Comment by nickbearman** [comment]
On a slight tangent, I have written some clearer / simpler instructions for new users to Ubuntu in PR #542 . Comments very welcome.

**Comment by nickbearman** [comment]
@reginaldc I've tried to clarify a few things in my PR - please have a look #542 
Debian and Ubuntu are more-or-less the same OS (from our point of view). I've swapped them around so Ubuntu is first in the list!
As I understand it, you can't install two versions of QGIS on Ubuntu unless you want to compile one of them from source (which I do not!). One work around would be to use VirtualBox and have a virtual machine running Ubuntu and install the other version on there.

**Comment by DelazJ** [comment]
Is this issue still valid?

**Comment by reginaldc** [comment]
Hi,

I was just thinking of something in the line:

Ubuntu Disco:
 - QGIS 3 ltr:
   -Do this .....
- QGIS 3 dev
   -Do this .....
- QGIS 2
  - Do this ....

Older version of Ubuntu:
- use synaptic

Debian Buster:
 - QGIS 3 ltr:
  -Do this ....

Regards,

**Comment by nickbearman** [comment]
Yes I think we still need clearer Ubuntu instructions. 
By original PR (https://github.com/qgis/QGIS-Website/pull/542) on this got reverted:
https://github.com/qgis/QGIS-Website/commit/3a20447191663bb938fd49ea0afc0cccf20fea71#commitcomment-34281331

And I wasn't clear on what the problem was. 
I haven't had time/energy/inclination to go back to this yet.

**Comment by AxxL** [comment]
> Is this issue still valid?

For me it's ok like it is. Confusion came up with older Ubuntu repositories, which lacked some libraries. And at that time with QGIS 2 and QGIS 3 two QGIS releases were available and that documentation wasn't clear about this.

I don't know if another one has complained about installation in Ubuntu/Debian.

**Comment by DelazJ** [comment]
Going through the discussion, I'm unsure of what it's about today, whether they are still relevant (that page has changed a lot meanwhile) and I'd suggest we close this.
If there still are valid issues or suggestions of improvement, please reopen a new one with details. Thanks.

**Comment by nickbearman** [comment]
Thanks @DelazJ , the quickstart looks much better and clearer. Happy for this to be closed.
