### ISSUE TITLE
Qgis crash by saving vector. What can I do?

### ISSUE THREAD

**Issue by natuurvwa** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#513]
## Description

Include sentences with details describing the issue you have encountered (e.g., actual behavior, expected behavior, steps to reproduce).

## Checklist
This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [ ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
Hi @natuurvwa 
> Qgis crash by saving vector. What can I do?

Report it at https://issues.qgis.org (check if it's not yet reported) with more details (steps, file format, qgis version, crash message...) and/or data to reproduce.

This repository is for issues with the QGIS website. Thanks.
