### ISSUE TITLE
download for mac not working

### ISSUE THREAD

**Issue by aerialpunkin** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#518]
Hi,
just tried to download QGIS to use on a mac but I keep ending up o the '404 not found' page with this message "The requested URL /downloads/macOS/QGIS-macOS-3.0.2-1.dmg was not found on this server."

Is there something really obvious that I'm just not getting?

**Comment by rduivenvoorde** [comment]
@aerialpunkin there has been a new point release this weekend, meaning the 'automatic' release numbers for linux and debian packages are highered, but macOS installer did not have a newer version at the same time.

 @kyngchaos I've created a symbolic link from QGIS-macOS-3.0.1-1.dmg to QGIS-macOS-3.0.2-1.dmg for now, so the download link works, but probably better to have another var in the website for macOS versions?

**Comment by kyngchaos** [comment]
separate version number variables for point and binary added in 9ee92f7ee7e0 for mac .

**Comment by kyngchaos** [comment]
um, I rushed that change.  Forgot that schedule.py is set by spreadsheet, so yeah, I should just hardwire the mac versions in conf.py.  I try to avoid the google stuff (I'm registered at my job, but never logged in).  And yes, I thought the process looked a bit convoluted.

**Comment by aerialpunkin** [comment]
thanks @kyngchaos and @rduivenvoorde not sure if this means it's good to download now or should I wait for the latest release, you guys speak a language that I only know the basics in 😀
