### ISSUE TITLE
OSX Download Link broken

### ISSUE THREAD

**Issue by rustychris** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#519]
## Description

On trying to download the dmg to install QGIS 3.0.2 on a mac from here:

  https://qgis.org/en/site/forusers/download.html#

the link was broken.  Seems that the link expects 

  http://qgis.org/downloads/macOS/QGIS-macOS-3.0.2-1.dmg

while the download directory (https://qgis.org/downloads/macOS/) switched naming schemes to 

  https://qgis.org/downloads/macOS/QGIS-3.0.2-1.dmg

**Comment by rduivenvoorde** [comment]
Fixed, thanks for letting us know!
