### ISSUE TITLE
menu doesn't work with github banner on mobile

### ISSUE THREAD

**Issue by jj0hns0n** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#52]
Can't click on menu on mobile (iPhone) because github ribbon is in the way.

**Comment by pcav** [comment]
Confirmed. It can also be an issue with PCs sometimes. I suggest removing the ribbon entirely. We don't want to do advertisement for GH, do we?

**Comment by jj0hns0n** [comment]
This is a pretty common banner to direct people to the GitHub site to fork the code. Can be removed as its also in the footer, but Im ok to leave it in if we can find a way to make it work with the menu.
