### ISSUE TITLE
QGIS craches when I try to import PyQT4 from Pyqgis console

### ISSUE THREAD

**Issue by dragonxtek** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#523]
## Description
After QGIS run (without loading layers or any other thing) I try to import PyQt4.QtGui from PyQGIS console, and when I press Enter, QGIS crashes!
I got the following message in linux terminal:

> QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
> process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
> again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
> ptrace: Operation not permitted.
> No thread selected
> No stack.
> gdb returned 0
> [1]    9672 abort (core dumped)  qgis

I modified /etc/sysctl.d/10-ptrace.conf value to 0 (just in case) but it doesn't works.

If I try to run QGIS with root privileges, QGIS crashes again, but it gives me other output:

> QGIS died on signal 11[New LWP 30512]
> [New LWP 30545]
> [New LWP 30546]
> [New LWP 30561]
> [New LWP 30562]
> [New LWP 30563]
> [New LWP 30564]
> [New LWP 30565]
> [New LWP 30566]
> [New LWP 30567]
> [New LWP 30568]
> [New LWP 30569]
> [New LWP 30617]
> 
> warning: the debug information found in "/lib64/ld-2.23.so" does not match "/lib64/ld-linux-x86-64.so.2" (CRC mismatch).
> 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> 0x00007f1364d850cb in __GI___waitpid (pid=31351, stat_loc=0x7ffd65f48324, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
> 29	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.

I installed gnulib (contains waitpid.c) but it crashes again.

My software versions are:
Ubuntu 16.04
QGIS 3.0.2
Python 3.5

**Comment by DelazJ** [comment]
Hi @dragonxtek
Please report this in the [issue tracker] (https://issues.qgis.org) or ask for help in one of qgis [support channels](https://qgis.org/en/site/forusers/support.html).
This repository is dedicated to [QGIS Website](https://qgis.org) issues.

Fyi, QGIS 3 is not compatible with qt4, pyqt4 nor python2. This is a major change of this release; it instead uses qt5, pyqt5 and python3. Try your call accordingly. 

I'm closing the report. Thanks for understanding.
