### ISSUE TITLE
It's very slow to close dialog

### ISSUE THREAD

**Issue by bruce6135** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#524]
## Description

I'm using ubuntu18.04 LTS, and qgis 3.0.2-Girona. Everything is ok, except when I close any dialog, is usually takes about 3 seconds to close the dialog. For example, open attributes table of a layer, it will take 3 seconds to close it.

## Checklist
This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [ ] I have added a link to the page concerned by the issue

**Comment by jef-n** [comment]
How is this a website issue?   Please file application issues on https://issues.qgis.org
