### ISSUE TITLE
QGIS 3.0 Doesn´t print in A3 format

### ISSUE THREAD

**Issue by fciges** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#527]
I have gone from version 2.18 to version 3.0. In the Las Palmas version I had no problem with printing.
I usually work in A3 format and as I said in version 2.18 I did not have any problems with printing from the "designer manager", but in version 3.0, from the "Show Layout" I printed the rotated drawing occupying only a part of A3 paper. Paper comes out horizontally and printing makes it vertical. It is not a problem to configure the printer or the preferences because with version 2.18 I do exactly the same and print well.

Thanks

**Comment by DelazJ** [comment]
Dear @fciges,
This repository is to manage the [QGIS website](https://qgis.org) and related issues. Your report does not concern the website and should be reported in the [application issue tracker](https://issues.qgis.org). Please check the repo before any report as I think there are already reports about printing failures. 
Closing...
