### ISSUE TITLE
Exporting projects to .dxf for older versions

### ISSUE THREAD

**Issue by Drentem** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#528]
Exporting projects to .dxf for older versions of autocad results in

Internal error: !dblayoti.cpp@97: ePermanentlyErased

With "Unknown object type VISUALSTYLE ignored" for multiple objects.

![error](https://user-images.githubusercontent.com/38956113/39925179-9d12eab0-54f8-11e8-95d3-6b6df677ea17.PNG)

**Comment by DelazJ** [comment]
@Drentem 
Please take the time to read the issue report template before erasing it. It clearly states that this is the place to report qgis website issues and not the ones when using the application. Please report your issue at https://issues.qgis.org.
Thanks.
