### ISSUE TITLE
GDAL command output: /bin/sh: 1: gdal_merge.py: not found

### ISSUE THREAD

**Issue by sergiomelo37** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#530]
## Description

GDAL command output:
/bin/sh: 1: gdal_merge.py: not found

## Checklist
196/5000
When I tried to merge the raster layers. The error message "GDAL command output: / bin / sh: 1: gdal_merge.py: not found" is displayed.
I'm using the Ubuntu operating system 18.04 and QGIS 3.0.
====
![captura de tela de 2018-05-20 16-35-33](https://user-images.githubusercontent.com/38961653/40283516-4921d590-5c4d-11e8-8f30-47fc3bca7495.png)

**Comment by rduivenvoorde** [comment]
Sorry, this is the issue tracker for the website, NOT for QGIS related questions. 
This looks like an install problem. Did you install the gdal-python bindings?
Please sent this to either the QGIS-User mailing list
Closing
