### ISSUE TITLE
Download for macOS Still Linked to 3.0.2

### ISSUE THREAD

**Issue by davidafuller01** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#533]
## Description

The application and the website are indicating: "The current version is QGIS 3.0.3 'Girona' and was released on 18.05.2018.", however 3.0.2 is still linked to:

- https://www.qgis.org/en/site/forusers/download.html

and 3.0.3 is not yet posted to:

- https://qgis.org/downloads/macOS/

**Comment by kyngchaos** [comment]
that is correct.  I am building now.
