### ISSUE TITLE
Duplicate items in Stripe amounts combobox

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#539]
In https://www.qgis.org/en/site/getinvolved/donations.html#qgis-donations expanding the list of amounts in the Stripe section shows double items
![capture d ecran 2018-06-21 a 10 55 46](https://user-images.githubusercontent.com/7983394/41708908-2d309502-7542-11e8-9b40-22795eb4bb08.png)

**Comment by andreasneumann** [comment]
There are two different currencies: € and US $

@rduivenvoorde - is there are a reason for the US $ version - or can we just use Euros?

**Comment by DelazJ** [comment]
Indeed. I overlooked. Sorry for the noise.

**Comment by rduivenvoorde** [comment]
Well, my idea was actually to add even more currencies. My idea is that somebody from Japan does really not know how much 100 euro is (well, I do not even know the chinese/japanese currency rate).
And I think it is better for users to see in their own currency.
We can change the setup in 2 dropdowns? 
One with amount (10 - 1000 or so?)
One with all currencies.

I think somebody will earn money from moving it from one currency to the other. If an Aussie donates dollars, his bank will fee him to move from ausie dollar to us dollar/euro...  Else Stripe does it (I think?)
Mmmm, maybe you are right... maybe first the bank is doing it from aus to us, and then Stripe does it from us to eur....??

Who knows about this?

**Comment by andreasneumann** [comment]
For QGIS as the project, we would prefer payments in €, because there we don't have to pay conversion fees.

Perhaps we can include a link to a currency conversion service online, so that users can see how mach x € means in their local currency?

In that case we can restrict it to €. It would be my personal preference.

**Comment by andreasneumann** [comment]
One such conversion service would be https://www.xe.com/currencyconverter/
or Google has something similar.

**Comment by andreasneumann** [comment]
Here is an example URL where on can submit amount and currencies in the URL:
https://www.xe.com/currencyconverter/convert/?Amount=10&From=EUR&To=USD

**Comment by mbernasocchi** [comment]
can we close this? it has ben running well for over a year and I think people can find out easily how much 100€ is?

**Comment by andreasneumann** [comment]
Closing this because it seems to work ok.

@DelazJ - please reopen if you have good reasons to further improve this.
