### ISSUE TITLE
issues about the selected

### ISSUE THREAD

**Issue by wanghai1988** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#541]
## Description
When using Qgis for secondary development, when I started editing, I added some features and selected them, then perform the rollback operation and found that vlayer->selectedFeaturesIds() still got the featureids I just selected. Is it that I still need to perform the removeSelection operation? thanks

## Checklist
This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [ ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
@wanghai1988 Please use the links in your message to either ask help to the community or report an application bug, depending on your intention. You'll likely get more chance of reply on this topic than here; this repository is to manage the [QGIS website](https://qgis.org) issues and improvements.
Thanks for your understanding. Closing.
