### ISSUE TITLE
Installation 3.2 on Windows

### ISSUE THREAD

**Issue by mcm-jyl** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#543]
## Description
I had a 3.0.X installation, using a OSGeo4W Network Installer (64 bit).
As advised by QGIS I tried to update to 3.2.

Looking for the latest version on Windows 64-bit I came to:
https://qgis.org/en/site/forusers/download.html

But http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe links to a 3.0.x installation, not (yet) to a 3.2

Only the full local installer
https://qgis.org/downloads/QGIS-OSGeo4W-3.2.0-1-Setup-x86_64.exe is up-to-date.

Maybe a warning on the website would help (of course having the network setup offering 3.2 would be better).

**Comment by rduivenvoorde** [comment]
![selection_004](https://user-images.githubusercontent.com/731673/42102826-6d79857a-7bc7-11e8-9863-036883f55a6e.png)

As you see, both 3.2.0 and 3.3.0 (dev version) are available.
I'm using norbit mirror, but others should show the same

Closing this here, as this is the issue tracker for the Website qgis.org
