### ISSUE TITLE
Bonn splash image 1.8Mb

### ISSUE THREAD

**Issue by dquinton** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#545]
Hi, thought I should mention that the splash image for 3.2 Bonn is 1.8 Mb in size - a bit heavy for a web page!
(page is https://qgis.org/en/site/forusers/visualchangelog32/)

**Comment by rduivenvoorde** [comment]
@dquinton ah, thanks. Me bad.... During release I boldly created a temporary page getting the splashscreen from the then fresh 3.2 branch... 
I will move the changelog from the projecta app this week, and will remove this image then.
I'll close this one, and if it is still there next week, ping me :-)
