### ISSUE TITLE
searchbox error and looking different in several browsers

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#55]
In Firefox the searchbox (select) also shows the native dropdown arrows.

Besides this the box looks different in all browsers, not sure what is the preferred look.
![chromium](https://f.cloud.github.com/assets/731673/1143264/e20ad54a-1d2d-11e3-91a8-1f22e9c85013.png)
![firefox](https://f.cloud.github.com/assets/731673/1143265/e20afde0-1d2d-11e3-852c-580511acd0ee.png)
![webkitbrowser](https://f.cloud.github.com/assets/731673/1143266/e22c9fa4-1d2d-11e3-912d-7a9d4a49926c.png)

**Comment by rduivenvoorde** [comment]
some info found here:
http://blog.artlogic.com/2013/02/26/oh-drop-downs-you-cheeky-little-things-2/

**Comment by DelazJ** [comment]
@rduivenvoorde Still an issue?

**Comment by mbernasocchi** [comment]
Fixed in modern FF
