### ISSUE TITLE
Android - the download link is dead?

### ISSUE THREAD

**Issue by MGGfN** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#552]
## Description

Include sentences with details describing the issue you have encountered (e.g., actual behavior, expected behavior, steps to reproduce).

## Checklist
This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [x] I have added a link to the page concerned by the issue

**Comment by MGGfN** [comment]
https://www.qgis.org/en/site/forusers/download.html#

**Comment by rduivenvoorde** [comment]
@m-kuhn @mbernasocchi this was a link to the play store, which is now a dead link. 
Do we still have a QGIS android build in the playstore?

**Comment by m-kuhn** [comment]
Apparently it has been deleted by Google.
We are investigating the details and will provide more information as soon as we have it.

**Comment by m-kuhn** [comment]
Answer from @mbernasocchi 

> Hi all, sorry the mail llanded in junk. I fixed it now. It says it will take some hours to be reenabled.
Cheers and thanks
Marco

**Comment by mbernasocchi** [comment]
Works now again
