### ISSUE TITLE
grid-gridding tools missing in SAGA form QGIS

### ISSUE THREAD

**Issue by ArnaudGuede** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#557]
Hi 

i have a problem. all grid-gridding tools missing in SAGA form QGIS. How to resolve please

Thanks

Arnaud
arnaud.guede@gmail.com

**Comment by ArnaudGuede** [comment]
I used QGIS 2.18.22

**Comment by yjacolin** [comment]
Please could use the mailing list to get help from other user or developper? This page is to fill an issue for QGIS **Website**. Thanks.
