### ISSUE TITLE
[3.2.2] problem on CRS TRASFORMATION

### ISSUE THREAD

**Issue by nicco17** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#558]
problema su CRS TRASFORMATION

Il software richiede GRASS-7.4.0 nella cartella qgis\apps\grass. Ma QGIS 3.2.2 ha installato GRASS-7.4.1. Il sistema va in crash. Io ho risolto copiando la cartella qgis\apps\grass\GRASS-7.4.1 e rinominadola GRASS-7.4.0

I apologize and forgive if I wrote badly and maybe in the wrong place, but I'm not used to the FAQ
![grass error](https://user-images.githubusercontent.com/42679241/44596894-1a3b5e00-a7ce-11e8-94b6-96f9781d6092.jpg)

**Comment by yjacolin** [comment]
> problem on CRS TRASFORMATION
> 
> The software requires GRASS-7.4.0 in the qgis \ apps \ grass folder. But QGIS 3.2.2 installed GRASS-7.4.1. The system crashes. I solved by copying the folder qgis \ apps \ grass \ GRASS-7.4.1 and renaming it to GRASS-7.4.0
> 
> I apologize and forgive if I wrote badly and maybe I'm not used to the FAQ

**Comment by yjacolin** [comment]
This bug tracker is for QGIS Website. Please note that you should write in english your bug report. See https://issues.qgis.org/projects/qgis/issues/ for the QGIS bug report.
