### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by krjjang** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#559]
I think pictures are better than any comments.
I'm Korean.
QGIS 2.x had no this issue, But QGIS 3.x have not support Korean (maybe other languages except English also have same issue) in QGIS Python Console Editor.
Refer below images.

![image](https://user-images.githubusercontent.com/18134810/44652231-5cf77300-aa26-11e8-8f7d-97426195593a.png)

![image](https://user-images.githubusercontent.com/18134810/44652242-64b71780-aa26-11e8-8964-8a85da0dae80.png)

![image](https://user-images.githubusercontent.com/18134810/44652255-6bde2580-aa26-11e8-8eb2-45f1ae288b48.png)

![image](https://user-images.githubusercontent.com/18134810/44652268-726c9d00-aa26-11e8-9588-eaf4c5abc3a1.png)

![image](https://user-images.githubusercontent.com/18134810/44652275-78627e00-aa26-11e8-919f-f5236c218e85.png)

![image](https://user-images.githubusercontent.com/18134810/44652291-83b5a980-aa26-11e8-94cd-7c98693886c2.png)

**Comment by yjacolin** [comment]
Hello,

Thanks for  the bug report. Could you please use this one instead (http://hub.qgis.org/). You used the QGIS Website report :)

Thanks,

Y.

**Comment by rduivenvoorde** [comment]
@yjacolin just for reference, we do not use 'hub' as issues anymore (though it works because we redirect to issues), better to point to https://issues.qgis org :-)
