### ISSUE TITLE
USER GUIDE/MANUAL

### ISSUE THREAD

**Issue by Lexfhebry** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#560]
Hi

I find a mistake on the spanish translation in the USER GUIDE/MANUAL (QGIS 2.18) options, from up to down next to "Administrar el origen de datos" you write "Trabajar con catos vectoriales" and next to that "Trabajar con catos raster" is DATOS intead of "CATOS".   

Thanks for your time and work

**Comment by yjacolin** [comment]
You can made the change yourself on transifex and ask to join the spanish team: https://www.transifex.com/qgis/.
Futhermore, this issue tracking is for QGIS Website, not QGIS documentation.

**Comment by yjacolin** [comment]
Please see my comment here: https://github.com/qgis/QGIS-Documentation/issues/2953
