### ISSUE TITLE
Error on "digitizing" plugin

### ISSUE THREAD

**Issue by ghost** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#563]
Hi qgis developer,

I have an error when installing digitizing plugin on QGIS 3.2.2.
Well, this is the error:
*Crash ID*: 6933423091dcc964a654c82afc643b7e1aa13140

*Stack Trace*
<pre>
QObject::connect :
PyInit_QtCore :
PyFrame_New :
PyObject_Call :
PyInit_sip :
PyInit__gui :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyUnicode_AsUTF8AndSize :
PyFrame_New :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyUnicode_AsUTF8AndSize :
PyFrame_New :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgsPluginRegistry::loadPythonPlugin :
QgsLayoutLocatorFilter::triggerResult :
QgsLayoutLocatorFilter::triggerResult :
QMetaObject::activate :
QStandardItemModel::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::dataChanged :
QStandardItemModel::itemChanged :
QStandardItem::setData :
QStandardItemModel::setData :
QSortFilterProxyModel::setData :
QStyledItemDelegate::editorEvent :
QAbstractItemView::selectionModel :
QAbstractItemView::edit :
QAbstractItemView::mouseReleaseEvent :
QListView::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit__gui :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyEval_EvalCode :
PyArena_Free :
PyRun_StringFlags :
instance :
instance :
QgisApp::rotatePointSymbols :
QgsPythonRunner::run :
QgisApp::showPluginManager :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.2.3-Bonn
QGIS code revision: commit:9b176802e5
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by rduivenvoorde** [comment]
@fauzi-pandya thanks for noting, but this issue tracker is only for our QGIS website related things.
If you can reproduce this preferably on different machines, please create an account at issues.qgis.org and report there.
Thanks (closing now to keep this issue tracker clean)

**Comment by DelazJ** [comment]
Actually, no. This one is related to the Digitizing Tools plugin, which is a third-party plugin, hence not managed by the QGIS project. You can find its bug repository in its description in the Plugin Manager and should report there (not at issues.qgis. org)

**Comment by DelazJ** [comment]
Unless you reproduce it with the other plugins
