### ISSUE TITLE
Map browser issue in MacOS

### ISSUE THREAD

**Issue by TroyPudney** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#564]
Not sure if this is just me or a wider issue. After updating to version 3.2.1 and now 3.2.2 the map browser has become small. Application also crashes.
<img width="1680" alt="screen shot 2018-09-16 at 17 08 42" src="https://user-images.githubusercontent.com/43311205/45594135-a78c5f80-b9d4-11e8-8291-befb592d02d3.png">

**Comment by rduivenvoorde** [comment]
Hi @TroyPudney this issue tracker is only of the QGIS website, if you can reproduce this preferably on different macs and different projects, please create an account at issues.qgis.org and report there.
Thanks (closing now to keep this issue tracker clean)

**Comment by DelazJ** [comment]
Already reported I think. See eg https://issues.qgis.org/issues/19524
