### ISSUE TITLE
Not able to view raster attribute table 

### ISSUE THREAD

**Issue by GISConsortium** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#565]
I am having .tiff with its corresponding .dbf file, I can view the raster attribute table in Arcmap but Ican't see it in QGIS.

**Comment by yjacolin** [comment]
Hello,

This tracker is for QGIS Website, not for QGIS application. If you need some help, a QGIS-user mailing list is used for discussion of QGIS in general, as well as specific questions regarding its installation and use. You can subscribe to the qgis-users mailing list by visiting the following URL: http://lists.osgeo.org/mailman/listinfo/qgis-user

Y.

**Comment by GISConsortium** [comment]
Thank you.
