### ISSUE TITLE
plugins site down

### ISSUE THREAD

**Issue by Arronclark2** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#568]
## Description

Cannot add plugins, site is down at http://plugins.qgis.org
![image](https://user-images.githubusercontent.com/43525814/45933566-b7fc8700-bf4c-11e8-8a36-f775493d6367.png)

**Comment by rduivenvoorde** [comment]
Not anymore, so apparently fixed?
( thanks for noting though :-) )
