### ISSUE TITLE
Missing targets for 3.0 changelog screenshots

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#571]
In https://qgis.org/en/site/forusers/visualchangelog30/index.html when the mouse is over a screenshot or a gif, it allows you to click the image, and I guess enlarge it.
Issue is that none (afaics) of these images has a target link (well !) set, leading you either to the top of the page (for static jpg) or to a Not Found page (for gifs).

**Comment by rduivenvoorde** [comment]
This rst's are automatically generated. During this time the quality was not so good, so needed a lot of hand-editing. So I missed this.
Removed the empty targets from the rst...

**Comment by DelazJ** [comment]
Thanks @rduivenvoorde
