### ISSUE TITLE
Download version 3.4 for OSX

### ISSUE THREAD

**Issue by paologroppo** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#576]
On download page https://qgis.org/en/site/forusers/download.html link to version 3.4 for OSX actually download version 3.2.3.

**Comment by kyngchaos** [comment]
an unfortunate side effect of the major version change - the page text comes from a global variable, the link comes from Mac-specific variables (so I can have time to package and not have this problem at every minor release).  It's coming, be patient.

**Comment by rduivenvoorde** [comment]
@kyngchaos no panic please: take your time :-)

@paologroppo the link was generated using a global version variable, I just fixed this, so upon the next rebuild of the website (soon), you will see the real text there.

@all macusers: please buy @kyngchaos a beer if you see him, this is all volunteering work! ;-)
