### ISSUE TITLE
Issue with Long term release repository for china

### ISSUE THREAD

**Issue by wanghai1988** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#580]
now for other website the new long term release is 3.4.0,but for china is 3.0.3.  [ https://www.qgis.org/zh-Hans/site/index.html](https://www.qgis.org/zh-Hans/site/index.html)

**Comment by jef-n** [comment]
Fixed redirects.

**Comment by rduivenvoorde** [comment]
Ah, cool. Thanks Juergen, I just wanted to look into this because I thought it was a build problem...

**Comment by wanghai1988** [comment]
yeah! The new long term release Version now fixed,but the language select control now Incorrect display when I select “簡体中文” or "正體中文"。the language disappeared


。
