### ISSUE TITLE
Fail Export

### ISSUE THREAD

**Issue by mabundagv** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#581]
## Description

QGIS fails to export the maps to jpeg and crushes when trying to export to pdf.

## Checklist
This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [ ] I have added a link to the page concerned by the issue

**Comment by mabundagv** [comment]
![image](https://user-images.githubusercontent.com/44633362/47772206-9aaa9d80-dcee-11e8-9dcd-94034d256498.png)

**Comment by rduivenvoorde** [comment]
Hi, See the text below your text (the 'Check list' :-)

Please create an issue at https://issues.qgis.org

**Comment by mabundagv** [comment]
I tried, I'm struggling to do it

**Comment by rduivenvoorde** [comment]
Is it with one special layout (maybe created with an older QGIS)?
OR is it with also with a fresh layout?

Is it also if you create a png from it? 
Or a pdf?

**Comment by mabundagv** [comment]
Thank you, I managed to submit a new issue.

Even when I create a new layout it still has the same outcome. For all
other export formats it shows the success dialog but when you try to locate
it or open directly from QGIS, it shows nothing. For PDF it just crashes

Kind Regards
