### ISSUE TITLE
How to Enable the QGIS Official Plugin Repository in the 3.4.1 Version?

### ISSUE THREAD

**Issue by nitzanmatan** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#585]
I am using QGIS version 3.4.1.
Recently, I cannot install new plugins. I have looked in the plugin setting. It seems that the link is blocked. The address is "https://plugins.qgis.org/plugins/plugins.xml" and it is directed to the [QGIS Python Plugins](https://plugins.qgis.org/plugins/plugins.xml) website.

In the log Messages I have this warning "WARNING: Failed to load C:/PROGRA~1/QGIS3~1.4/apps/qgis/plugins/grassplugin7.dll (Reason: Cannot load library C".

I have a proxy from my university, disabling the automatic configuration script did not solve the problem.

**Comment by DelazJ** [comment]
I'm not sure that the two parts of your report are related, i mean I don't think that the grass plugin is provided through the plugin repository.
For the first part of your report, here's what my settings look like (needed nothing particular to do) and it works:
![image](https://user-images.githubusercontent.com/7983394/48971316-1a8b0580-f018-11e8-96a6-74e28b7bc5fc.png)
Anyway, may be better to raise your issue(s) in the qgis-user list or the [qgis bug tracker](https://issues.qgis.org). This repository concerns issues about [QGIS website](https://qgis.org).

**Comment by nitzanmatan** [comment]
Thanks
ניצן מתן
0547879411
