### ISSUE TITLE
QGIS 3.4 for Debian jessie is out of date.

### ISSUE THREAD

**Issue by JohnLiannon** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#589]
## Description

When trying to get and install qgis 3.4 in Debian jessie from QGIS repository "3.4.x Madeira (new LTR) : https://qgis.org/debian/dists/jessie/" it always get and install 2.18 version.

**Comment by jef-n** [comment]
Whic is what the jessie footnote on https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu says.

**Comment by JohnLiannon** [comment]
Is the QGIS 3.4 version going to be available for Debian jessie? When?
