### ISSUE TITLE
download page: not very clear that this is an accordeon

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#59]
We use an accordeon on the download box, but for some people it is not clear that the other options can be openend also. There is no visual cue for that.

If you look at the jquery accordeon there are this little icons indicating open/closed:

http://jqueryui.com/accordion/

Maybe do something like this also??

![accordeon](https://f.cloud.github.com/assets/731673/1144804/c58744a6-1dcf-11e3-8a73-cb8767ea182c.png)

**Comment by rduivenvoorde** [comment]
see #93 and #85

**Comment by eshon** [comment]
Am committing in a minute...sorry

**Comment by rduivenvoorde** [comment]
ah cool, thanks :-)
