### ISSUE TITLE
3D Visualization - Buildings Floating

### ISSUE THREAD

**Issue by vincentsimon** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#593]
Hello, 

I'm using the 3D visualization map tool and can't seem to make it so that my buildings touch the ground. Has anyone had this issue before?

I'm attaching what I'm seeing and my settings. 

Cheers,
Vincent
![qgis issue - 2](https://user-images.githubusercontent.com/47003479/51690096-033fa880-1fc6-11e9-905c-91c9bbf3581f.PNG)
![qgis issue - 1](https://user-images.githubusercontent.com/47003479/51690098-033fa880-1fc6-11e9-8398-dc7ffc423d4d.PNG)
![qgis issue - 3](https://user-images.githubusercontent.com/47003479/51690099-033fa880-1fc6-11e9-8fbf-5ae34bbb0fe8.PNG)

**Comment by andreasneumann** [comment]
Hi @vincentsimon  - these are issues about the QGIS Website. Not about QGIS itself.

If you want to report issues in QGIS, please use https://issues.qgis.org/

However, in your case, it is not a bug - it is just that you need to learn about how to use QGIS3D and its peculiarities. In your case, the buildings are not floating - they are already on the ground. But what you see is the 2D representation at elevation "zero". You need to switch off the 2D representation.

But please discuss this at the normal QGIS support channels, described at https://www.qgis.org/en/site/forusers/support.html

**Comment by andreasneumann** [comment]
Closing this, at this is not a support forum.
