### ISSUE TITLE
QGIS Training Manual>12.2 Lesson: Serving WMS demo link

### ISSUE THREAD

**Issue by gisn8** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#594]
## Description
Re: https://docs.qgis.org/testing/en/docs/training_manual/qgis_server/wms.html
The link to **demo data** is broken. It currently points to https://github.com/qgis/QGIS-Training-Data/archive/QGIS-Training-Data-v2.0.zip
My best guess for a workaround is instruct downloading the files found at https://github.com/qgis/QGIS-Training-Data/tree/master/exercise_data/qgis-server-tutorial-data

## Checklist
This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [x ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
Thanks for the report. The targeted branch no longer existed so fixed now.
