### ISSUE TITLE
Add MIEUNE.Inc logo to Gold/Silver Sponsors Image 

### ISSUE THREAD

**Issue by waigania13** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#595]
Please add MIERUNE.Inc logo to  Gold/Silver Sponsors Image.
http://changelog.kartoza.com/en/qgis/sponsorshipperiod/dmtywa/
https://qgis.org/en/_static/images/sponsors.png

And, We would like to reflect the organization change from LLC to Inc.

**Comment by andreasneumann** [comment]
Closing. Already done.
