### ISSUE TITLE
Broken "sample data set" link on download page

### ISSUE THREAD

**Issue by jakimowb** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#600]
Page https://www.qgis.org/en/site/forusers/download.html

Last paragraph. `sample dataset is available` refers to a broken url `http://docs.qgis.org/3.6/en/docs/user_manual/introduction/getting_started.html#sample-data`

**Comment by rduivenvoorde** [comment]
Thanks for letting us know.
Should be fixed now.
Closing.
