### ISSUE TITLE
Crash ID: 73fb706c26fa9924bc0ce9bf57376088b50ce7db  

### ISSUE THREAD

**Issue by ferroramiro** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#622]
## Description
Crash ID: 73fb706c26fa9924bc0ce9bf57376088b50ce7db
version QGIS 3.4
Include sentences with details describing the issue you have encountered (e.g., actual behavior, expected behavior, steps to reproduce).

## Checklist
This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [ ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
There's nothing we can do with this report @ferroramiro.
If you get the crash again, please report in the [issue tracker](https://issues.qgis.org) with more details on what you did and the stacktrace.
This repository is dedicated to QGIS Website issues, hence I'm closing.
Thanks.
