### ISSUE TITLE
Shapefile output option unavailable in batch process reproject

### ISSUE THREAD

**Issue by amwaterh** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#623]
## Description
Shapefile output is unavailable in a reproject tool.  Only xml, dbf options are really available.

**Comment by DelazJ** [comment]
Hi @amwaterh 
Please report this in the [issue tracker](https://issues.qgis.org) with more details on what you did or ask for help in one of qgis [support channels](https://qgis.org/en/site/forusers/support.html).
This repository is dedicated to QGIS Website issues, hence I'm closing.
Thanks.
