### ISSUE TITLE
tried to register on redmine, but didn't get activation email

### ISSUE THREAD

**Issue by mitchell2090** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#627]
## Description
I am trying to register on the Redmine page to report an issue with QGIS, but I never received the email to activate the registration, although the web page claimed it was sent.
I have checked my junk mail, and it's not there.

I gave the user name 'mitchell2090'  and the email 'mitchell2090@bellsouth.net.

## Checklist
This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ x] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [ ] I have added a link to the page concerned by the issue

**Comment by jef-n** [comment]
Check with abuse_rbl@abuse-att.net please:
``
mitchell2090@bellsouth.net R=dnslookup T=remote_smtp: SMTP error from remote mail server after MAIL FROM:<redmine@issues.qgis.org>: host ff-ip4-mx-vip1.prodigy.net [144.160.159.21]: 553 5.3.0 flpd585 DNSBL:ATTRBL 521< 138.201.194.207 >_is_blocked.For assistance forward this email to abuse_rbl@abuse-att.net
``

**Comment by DelazJ** [comment]
@mitchell2090 finally fixed?

**Comment by mitchell2090** [comment]
I ended up regist  ering with a different username and my university email instead of att.  I don’t know if att imail frs still blocking from the site.

- Bill Mitchell

**Comment by DelazJ** [comment]
Thanks for the feedback. Does not seem to be something we can fix on QGIS side, right? In which case, maybe we should close the report.... @jef-n ?

**Comment by jef-n** [comment]
@DelazJ I don't think so - AT&T blocks redmine@issues.qgis.org for some reason.

**Comment by DelazJ** [comment]
@jef-n since QGIS issues are no longer on redmine, does this issue still concern QGIS? should we keep this open here?
