### ISSUE TITLE
The links on the download page don't work

### ISSUE THREAD

**Issue by dlmh1128r8** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#630]
## Description

I was at this page: https://qgis.org/en/site/forusers/download.html . When I click on the QGIS Standalone installer for the 64 bit version, I get an error message.

![image](https://user-images.githubusercontent.com/11276494/56514908-8c527700-6504-11e9-892a-7cec44c5ef4a.png)
![QGIS_ErrorMessage_Software_Downloads_20190422](https://user-images.githubusercontent.com/11276494/56515250-742f2780-6505-11e9-82d2-78584adaeeab.JPG)

When I go to the page of all the versions of the software under 64 bit, I don't see the version that corresponds to the link on the page above. A little confusing.

Could you let me know where the latest, stable version is?

Thank you.

Lucinda M. Hall

**Comment by soble** [comment]
link points to -2
uploaded file is -1 
https://qgis.org/downloads/QGIS-OSGeo4W-3.4.7-1-Setup-x86_64.exe

**Comment by DelazJ** [comment]
Thanks for the pointer, @soble 
@dlmh1128r8 we are on it. In the meantime, you can go to https://qgis.org/downloads/ and pick the expected version

**Comment by rduivenvoorde** [comment]
It is working now again. Sorry for the fuzz
