### ISSUE TITLE
Plugin has disable caused by crash

### ISSUE THREAD

**Issue by syfrbella** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#636]

**Comment by rduivenvoorde** [comment]
Sorry, this is the issue tracker for the website only.

If you have an issue for QGIS, please open is issue here:

https://issues.qgis.org/projects/qgis/issues/

BUT: please provide more info, based on what you provide here, there is nothing anybody can do or know... What OS, QGIS version, plugin etc are we talking about?
