### ISSUE TITLE
QGIS CRASHED DESKTOP

### ISSUE THREAD

**Issue by andressamuraro** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#637]
Crash ID: 0d7105539dbada6ab8a473af3049ea1c0bbdecfe

Stack Trace

memcpy :
VSICreateCachedFile :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_Terragen :
GDALRegister_GTiff :
GDALRasterBand::GetLockedBlockRef :
GDALRasterBand::IRasterIO :
GDALRegister_GTiff :
GDALRasterBand::RasterIO :
dataCapabilities :
QgsSingleBandGrayRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPart :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsArchive::zip :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.5-Madeira
QGIS code revision: 89ee6f6e23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by DelazJ** [comment]
Hi @andressamuraro ,

This is a QGIS application issue, hence should be raised in the [application issue tracker](https://github.com/qgis/QGIS) with more details on what you did.
This repository is dedicated to QGIS Website issues, hence I'm closing.
Thanks.
