### ISSUE TITLE
Download links to “latest” are outdated.

### ISSUE THREAD

**Issue by buzo-ffm** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#639]
## Description
All four sym-links https://qgis.org/downloads/qgis-latest-* are outdated.

Page URL:
https://qgis.org/downloads/

**Comment by buzo-ffm** [comment]
Apparently has been fixed with version 3.4.9.

**Comment by DelazJ** [comment]
Thanks for the feedback
