### ISSUE TITLE
the website has no page to introduce a newbie to SQL

### ISSUE THREAD

**Issue by pboulerie** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#641]
## Description

Hello,

When I type the keyword :  SQL

I have 13 results, none of them is a short introduction of what SQL can bring to QGis users and to the SQL Query builder...

-------------------------

Page URL :
https://qgis.org/fr/search.html?q=SQL&check_keywords=yes&area=default

**Comment by andreasneumann** [comment]
Hi @pboulerie 

I am not sure if it is the responsibility of QGIS to teach SQL. There are literally thousands of websites out there that teach SQL.

Besides: which SQL dialect should QGIS teach? We support PostgreSQL, SQLite, Oracle, SQLServer and more.

It is my opinion that people should turn to the respective websites of the aforementioned SQL DB projects or products to learn these SQL dialects.
