### ISSUE TITLE
1 minor typo in the French documentation ("Contructeur")

### ISSUE THREAD

**Issue by pboulerie** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#642]
## Description

As reported in https://georezo.net/forum/viewtopic.php?pid=322175#p322175
Page URL : https://docs.qgis.org/3.4/pdf/fr/QGIS-3.4-UserGuide-fr.pdf
talks about a typographic error, a missing "s" in
> Contructeur
on page 167

On the next line, an apostrophe is also missing :

> Filtre d entité
Filtre d'entité

**Comment by DelazJ** [comment]
Fixed in transifex. Thanks for the report.
