### ISSUE TITLE
QGIS 3.6.3 crash - grassdata setup

### ISSUE THREAD

**Issue by hlorent** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#643]
QGIS 3.6.3 crashes when I try to set up a dataset
![qgis_crash](https://user-images.githubusercontent.com/52005274/59778816-7a4c4500-92b7-11e9-82f2-05bb766238fd.png)

**Comment by DelazJ** [comment]
Hi @hlorent  ,

This is a QGIS application issue, hence should be raised in the [application issue tracker](https://github.com/qgis/QGIS) with more details on what you did (you'll have a template to fill).
This repository is dedicated to the [QGIS web site](https://qgis.org) issues, hence I'm closing.
Thanks.
