### ISSUE TITLE
r.sun error when trying to save batch file - 3.4.8-Madeira and latest 3.6.3

### ISSUE THREAD

**Issue by faustoarch** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#645]

**Comment by faustoarch** [comment]
2019-06-21T18:32:11     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins\processing\gui\BatchPanel.py", line 224, in save
              widget = wrapper.wrappedWidget()
             AttributeError: 'NoneType' object has no attribute 'wrappedWidget'

**Comment by DelazJ** [comment]
Hi @faustoarch ,

This is a QGIS application issue, hence should be raised in the [application issue tracker](https://github.com/qgis/QGIS) with more details on what you did.
This repository is dedicated to QGIS Website issues, hence I'm closing.
Thanks.
