### ISSUE TITLE
URL Link compromised/hacked 

### ISSUE THREAD

**Issue by markhylas** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#651]
## 

Page URL: http://fundyfootpath.info/

**Comment by markhylas** [comment]
This link leads to a pornographic site.  The site may be hacked?

**Comment by jef-n** [comment]
> This link leads to a pornographic site. The site may be hacked?

No, looks like the domain was meanwhile given up and reassigned (on 2019-05-18).
