### ISSUE TITLE
https://qgis.org/downloads/QGIS-OSGeo4W-3.8.1-1-Setup-x86.exe is 27 MB NOT whole exe!

### ISSUE THREAD

**Issue by aetor** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#658]
When I try to download 3.8.1.1 I get a download with 28 MB, not the whole download!

**Comment by jef-n** [comment]
not reproducable.

**Comment by aetor** [comment]
today the download works fine... so case closed!
