### ISSUE TITLE
no detailed page documenting about an Overlaps function

### ISSUE THREAD

**Issue by pboulerie** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#675]
Re : no detailed page documenting about an Overlaps function

Hello,

There is no specific page to detail how to compute an Overlaps map.

Yours sincerely,

----------------------------

A keyword search provides only Changelogs information, no documentation ...
https://qgis.org/en/search.html?q=overlaps&check_keywords=yes&area=default

**Comment by DelazJ** [comment]
@pboulerie  This is the repository of QGIS website which is not intended to provide documentation on features. Please refer to https://docs.qgis.org for anything related to features documentation and if not documented check whether an issue is not already available for the feature at https://github.com/qgis/QGIS-Documentation/issues. Thanks.
Closing.
