### ISSUE TITLE
remove output better before build 

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#68]
It appears that (for the docs site) when a rst file was removed, the hml build is somehow still available.

We should cleanup the output directory maybe better.

We should be carefull with this, because when the output is cleared before the build (and the build takes some time) there is actually NO website.

So we should try remove after the reading and just before the writing of it

**Comment by pcav** [comment]
I think for serious use a staging website will be necessary:
make html
check the results (visually or otherwise)
publish (cp -r build or similar)

**Comment by rduivenvoorde** [comment]
try: f5e634940d92641148760fc700001033b4d9abce
