### ISSUE TITLE
Two updated sentences in the download page are not available in transifex

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#695]
## Description
The sentences "QGIS is available on Windows, macOS, Linux and Android." and "Download for macOS", in the download page are not available in transifex for translation.
Those sentences have been updated with commit 0386422dea173a80c73369c5be82644c07dd6c4c (#686).

Page URL: https://www.qgis.org/it/site/forusers/download.html

**Comment by rduivenvoorde** [comment]
Thanks for noting. Should be fixed, when I upload the strings of the website to transifex because of Visual Changelog 3.10 today (it is not automated, so need manual uploads, which are done if somebody asks me, or when I do the changelogs for every release).

**Comment by agiudiceandrea** [comment]
Hi @rduivenvoorde, there are now other strings of the QGIS Web site not updated in transifex.
For example:
- "New release: 3.24!" in the home page
- "Upgrades of old setups from OSGeo4W v1 using this repository are not supported. You need to do a fresh install or use a different directory." and "32 bit binaries are not produced anymore. Also Windows 7 no longer works as we are now using Python 3.9, which dropped support for it." in the download page.

**Comment by rduivenvoorde** [comment]
Just updated tx strings. please try again :-)
