### ISSUE TITLE
Replace Quantum GIS with QGIS

### ISSUE THREAD

**Issue by pcav** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#7]

**Comment by jj0hns0n** [comment]
In the header?

**Comment by pcav** [comment]
Jeffrey Johnson notifications@github.com ha scritto:

> In the header?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/qgis/QGIS-Website/issues/7#issuecomment-23584166

## Yes, and every where else

http://faunalia.it/pc
Sent from mobile, sorry for being short

**Comment by jj0hns0n** [comment]
Closed with 5fe1eeebcde248843d52624e6d3f6489a881786e @pcav can you verify?
