### ISSUE TITLE
merge two pages about sponsorship

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#70]
We have two sponsorship pages apparently:

http://new.qgis.org/html/en/site/about/sponsorship.html

http://new.qgis.org/html/en/site/getinvolved/governance/sponsorship/sponsorship.html

In Github:

https://github.com/qgis/QGIS-Website/blob/master/source/site/about/sponsorship.rst

https://github.com/qgis/QGIS-Website/blob/master/source/site/getinvolved/governance/sponsorship/sponsorship.rst

Content should be merged

**Comment by rduivenvoorde** [comment]
Via development mailinglist:

G.A.I.A. mbH, which are silver sponsors since 6.2013

please (readd) them again

**Comment by anitagraser** [comment]
Please someone copy gaia.png from the old website and add it here

**Comment by rduivenvoorde** [comment]
Ok, will do (I see that you removed a lot of the double content)

**Comment by mach0** [comment]
Is the sponsorship page already done yet? Can this be closed?
If not can somebody tell me what is missing? I'd do it this week than..

**Comment by anitagraser** [comment]
I think the separation into two pages: one explaining how to sponsor QGIS, the other listing how sponsors QGIS; is fine now. Not sure if anything is missing but this issue could be closed imho.
