### ISSUE TITLE
close

### ISSUE THREAD

**Issue by sirkobe55** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#700]
Crash ID: 00db230d8a450928c9281dff8eedacd67298091e

Stack Trace

QList::empty :
QUndoStack::canRedo :
QgsUndoWidget::indexChanged :
QMetaObject::activate :
QUndoStack::clear :
QUndoStack::~QUndoStack :

QGIS Info
QGIS Version: 3.10.0-A Coruña
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by DelazJ** [comment]
@sirkobe55 This is the place for QGIS website issues. Please report application issues at https://github.com/qgis/QGIS/issues and provide more information about what you were doing when it crashes. Thanks
