### ISSUE TITLE
sample dataset unavailable

### ISSUE THREAD

**Issue by e-crins** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#703]
Hi,
In trying QGIS i Wanted to download the sample dataset from the site:
https://docs.qgis.org/3.10/en/docs/user_manual/introduction/getting_started.html
It gives a 404 error.
Broken link?

**Comment by DelazJ** [comment]
@e-crins Try this link https://docs.qgis.org/3.4/en/docs/user_manual/introduction/getting_started.html

@rduivenvoorde, @jef-n or any sys admin, until we release 3.10 docs, can you add redirection of 3.10 and 3.11 (and higher?) to testing doc, please? Currently help buttons in 3.10 and master lead to 404. Thanks!

**Comment by rduivenvoorde** [comment]
@DelazJ Ok, I tried:
There was:
`RedirectMatch ^/3\.[5-9]/(.*) /testing/$1`
I changed it to:
`RedirectMatch ^/3\.([5-9]|10|11|12|13)/(.*) /testing/$2`

Seems to work with me here, but not sure if the regexp can made better (@jef-n ?).

Please test.

**Comment by DelazJ** [comment]
I confirm links to 3.10 work here
