### ISSUE TITLE
Crash ID: dc9a648b1a049de7814e79655e6403bc001c2be8

### ISSUE THREAD

**Issue by Nicko05** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#705]
Hello,
The problem occurs while editing vector layer. In some point, something went wrong with softwere and it manifests when I toggle edit mode on any vector layer, and after edits it is not possible to save edits. When I close the edit mode of that vector layer and try to edit some other vetor layer, QGIS unexpectedly crashes. 
Sometimes Qgis is not crashing while that no saving option problem appers, then I am force to close project, restart Qgis or any other means to start function normally. Usually I have to make another project and import all databases.

Stack Trace

QObjectPrivate::addConnection :
QObjectPrivate::connectImpl :
QObject::connectImpl :
QObject::connect qobject.h:255
QgsVertexTool::cachedGeometry qgsvertextool.cpp:1266
QgsVertexTool::cachedGeometryForVertex qgsvertextool.cpp:1284
QgsVertexTool::moveVertex qgsvertextool.cpp:1973
QgsVertexTool::cadCanvasReleaseEvent qgsvertextool.cpp:585

QGIS Info
QGIS Version: 3.10.0-A CoruA�a
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by kannes** [comment]
Hey @Nicko05 , thank you so much for reporting this issue. This repository however is for the QGIS *website*, not the software. Could you post the issue at https://github.com/qgis/QGIS/issues ? That would be great!

**Comment by DelazJ** [comment]
Thanks
