### ISSUE TITLE
QGIS Crashing frequently 

### ISSUE THREAD

**Issue by mmafioleti** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#707]
My QGIS is crashing every few minutes. 

Crash ID: c7b4febf15a05dca2656ad55ecb4bb9571fca337

Stack Trace

osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRGeomFieldDefn::~OGRGeomFieldDefn :
SHPWriteObject :
OGRFeatureDefn::~OGRFeatureDefn :
OGRFeatureDefn::~OGRFeatureDefn :
SHPWriteObject :
DBFWriteTuple :
OGREditableLayer::Translate :
CPLStringList::FindString :
selectWidget :
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :

QGIS Info
QGIS Version: 3.4.13-Madeira
QGIS code revision: 567300ccf1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by DelazJ** [comment]
Hi @mmafioleti,
Please report this in the [application issue tracker](https://github.com/qgis/QGIS/issues) with more details on what you were doing before crashes. Also, try running QGIS with [a clean profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)
This repository is dedicated to [QGIS Website](https://qgis.org) issues, hence I'm closing.
Thanks.

**Comment by mmafioleti** [comment]
Every time I try open one file the QGIS is not responding and after few minutes it unexpectedly ended.

**Comment by DelazJ** [comment]
Then try with a new profile as suggested above and if it's still failing, report in the app issue tracker with the file you try to open and how you proceed.
