### ISSUE TITLE
qgis-site.js is not up to date

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#718]
## Description

The file qgis-site.js at https://docs.qgis.org/testing/en/_static/qgis-site.js or https://docs.qgis.org/3.4/en/_static/qgis-site.js is not up to date with the current master version at https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/static/qgis-site.js

Specifically, the commit 06d668abc57c56a92582308642d7e3984b2b7b44 (PR #579) does not appear to have been applied.

In fact, the current master version of qgis-site.js at line 70
https://github.com/qgis/QGIS-Website/blob/7ccc8c6bbf549fbd32816b5a9035adf1f182b2d1/themes/qgis-theme/static/qgis-site.js#L70
differs from the same line of qgis-site.js at docs.qgis.org
`    $(window).load(function () {`

Response headers for https://docs.qgis.org/testing/en/_static/qgis-site.js
```
HTTP/1.1 200 OK
Date: Sat, 25 Jan 2020 09:46:56 GMT
Content-Type: application/javascript
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=df6668f44208c88c204c2f9bf1f9a49611579945616; expires=Mon, 24-Feb-20 09:46:56 GMT; path=/; domain=.qgis.org; HttpOnly; SameSite=Lax
Last-Modified: Fri, 15 Nov 2019 18:33:18 GMT
ETag: W/"6d6bf7-11ef-59766d4f23e3c"
Vary: Accept-Encoding
Cache-Control: max-age=28800
CF-Cache-Status: HIT
Age: 390
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 55a952a9ea74cdcb-CDG
```

Response headers for https://docs.qgis.org/3.4/en/_static/qgis-site.js
```
HTTP/1.1 200 OK
Date: Sat, 25 Jan 2020 09:47:11 GMT
Content-Type: application/javascript
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=db16d314100807fce9a5dcd4fcd4d58991579945631; expires=Mon, 24-Feb-20 09:47:11 GMT; path=/; domain=.qgis.org; HttpOnly; SameSite=Lax
Last-Modified: Fri, 01 Dec 2017 20:30:57 GMT
ETag: W/"456a9e-11ef-55f4d3efa7be4"
Vary: Accept-Encoding
Cache-Control: max-age=28800
CF-Cache-Status: HIT
Age: 6541
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 55a95303b802a84f-CDG
```

**Comment by agiudiceandrea** [comment]
Sorry for the noise... The bug affects https://github.com/qgis/QGIS-Documentation/ repository.

**Comment by DelazJ** [comment]
@agiudiceandrea we are working on upgrading our dependencies and according to the plans should drop our custom settings as far as possible. I'll try to open a PR for completion and feedback during the next week

**Comment by agiudiceandrea** [comment]
@DelazJ, I've just submitted a PR: https://github.com/qgis/QGIS-Documentation/pull/4825
