### ISSUE TITLE
Outdated documentation, still showing 3.4

### ISSUE THREAD

**Issue by roya0045** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#722]
## Description
Hey @DelazJ 

Was the release changelog and doc update on the site dropped?

I can only see 3.4 as the latest doc and it makes it hard to look up the changelog.

Page URL: https://www.qgis.org/en/docs/index.html

Thanks for all your work!

**Comment by rduivenvoorde** [comment]
The (exported) changelogs are here
https://qgis.org/en/site/forusers/visualchangelogs.html

The content is being made here:
https://changelog.qgis.org/en/qgis/version/3.12/

Latest stable docs are indeed 3.4

The idea is to realase a 3.10 of the docs in near future.

**Comment by DelazJ** [comment]
Hi @roya0045 
This page never displayed the changelog. It's only for the released documentation (only LTR are done btw). Changelogs are instead available at https://www.qgis.org/en/site/forusers/visualchangelogs.html and 3.12 might be in the pipes

**Comment by roya0045** [comment]
Thanks @rduivenvoorde and @DelazJ, would it be possible to place the changelog somewhere more prominent on the site? 

Featuring the newest changes and feature would be a great thing to have to compare version in the landing or download pages. I assume that those were at least in the documentation area. :/

**Comment by rduivenvoorde** [comment]
https://docs.qgis.org/3.10/en/docs/ now available!

Will close this one.
