### ISSUE TITLE
Plugin processing disabled in QGIS 3.4

### ISSUE THREAD

**Issue by CristoFacundoP** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#723]
Dear community,
I am repeatedly experiencing a warning message in which Processing tool seems to be crashing in my laptop. I already uninstalled the QGIS 3.4 version and updated version 3.10 but still, I am unable to set the plugin. Whenever I click on it the software closes. Have any of you experienced something similar? or have an idea how to approach it?

Here below a picture of the warning message 

![image](https://user-images.githubusercontent.com/41880180/75357927-1fc0ab00-5880-11ea-970c-a4c2e7cf62be.png)

**Comment by DelazJ** [comment]
Hi @CristoFacundoP 

Please report this in the [application issue tracker](https://github.com/qgis/QGIS/issues) with more details on what you were doing before crashes. Also, try running QGIS with [a clean profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles) before.
This repository is dedicated to [QGIS Website](https://qgis.org) issues, hence I'm closing.
Thanks.
