### ISSUE TITLE
QGIS Website (italian) translation not updated

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#738]
## Description

It seems some strings which translation in italian language was changed some months ago are not yet displayed on QGIS Website.

For example:
In the main page footer: " - Last updated on"
https://www.transifex.com/qgis/qgis-website/translate/#it/sphinx/22062780

is currently displayed as "- Ultimi aggiornamenti su", but in Transifex it results translated as "- Ultimo aggiornamento il" since October 2019.

Moreover,
some udated strings in english are not yet updated in Transifex, so it's impossible to properly translate them.

**Comment by rduivenvoorde** [comment]
Hi, Thanks for letting us now!
Last week I changed my transifex password... so this week probably all tx pulls did not work :-(
I had a look and not sure why but I cleaned up all .po files and did a rebuild and now at least the 'Last updated' string looks good:

![Screenshot-20200325100359-381x169](https://user-images.githubusercontent.com/731673/77519692-39094700-6e80-11ea-95ed-b4a2ea074a77.png)

Feel free to do some further checking! For example try to make a translation and see if it will be there next rebuild tomorrow.
Or check other pages. 
Let me know if you find other non translations!
Will leave this open untill you close it when you are confident that all is working as it should.

**Comment by agiudiceandrea** [comment]
Thank you @rduivenvoorde.
Will the strings in Transifex be updated later? It seems there are new or modified strings in website source not yet updated in Transifex in the last about 12 days.

**Comment by rduivenvoorde** [comment]
@agiudiceandrea  I have to do this 'by hand'. This was not automated, and needs some care. So I normally do this only after some bigger updates, like adding of a visual changelog.
OR if there is something you really need. Then let me know and I will do it.
The website content is not so much in flux...

**Comment by agiudiceandrea** [comment]
I thought it was an automatic or semi-automatic procedure...

Anyway, surveying the main pages (index, about, forusers, getinvolved, docs), the following strings are not updated in transifex or not translatable:

1)
```
for your Operating System and read the
changelog.
```
https://github.com/qgis/QGIS-Website/blob/9b492b1c2d4add454dbe655e71f753a219165c01/themes/qgis-theme/index.html#L37-L38

2)
```
We are still updating (not translating yet) the documentation for releases newer than QGIS 3.10. We call this version 'QGIS testing' and the documentation can be found here:
```
https://github.com/qgis/QGIS-Website/blob/9b492b1c2d4add454dbe655e71f753a219165c01/themes/qgis-theme/docs_index.html#L91
(in this case I suggest to put the QGIS version number outside the string to translate, so there is no need to translate the string every time the version number changes)

3) "Make some strings localizable" https://github.com/qgis/QGIS-Website/pull/739

**Comment by agiudiceandrea** [comment]
This is another string with source not update on transifex:

> In case of a broken function, you may give a look at `QGIS issue tracker <https://issues.qgis.org/projects/qgis/issues>`_ before mailing to the list. More information at :ref:`QGIS-bugreporting`.

https://www.transifex.com/qgis/qgis-website/translate/#it/$/142960541
https://github.com/qgis/QGIS-Website/blame/master/source/site/getinvolved/faq/index.rst#L41-L43

**Comment by agiudiceandrea** [comment]
See also https://lists.osgeo.org/pipermail/qgis-tr/2020-May/001079.html

**Comment by rduivenvoorde** [comment]
@agiudiceandrea feel free to ping me if you think a transifex update is nessecry (richard@duif.net). Will do now...

**Comment by rduivenvoorde** [comment]
Done :-)

**Comment by agiudiceandrea** [comment]
Thank you!
