### ISSUE TITLE
QuickMapService plugin isn't working on my QGIS 3.12 desktop application.

### ISSUE THREAD

**Issue by shobhitpipil25** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#743]
![image](https://user-images.githubusercontent.com/43374568/78458525-034b3600-76aa-11ea-8218-fae77f77c434.png)

**Comment by jef-n** [comment]
Not a website issue - not even a QGIS issue - apparently it's not even a general QMS issue that should be filed in the plugin's issue tracker as it works fine on 3.12 for me.
