### ISSUE TITLE
Crash in Graduated Symbols renderer

### ISSUE THREAD

**Issue by FedericaPalmieri** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#749]
## Report Details

**Crash ID**: [784a55bb3a0dedb5f8d7e22c6dbb1d6ad84b3eee]('https://github.com/qgis/QGIS/search?q=784a55bb3a0dedb5f8d7e22c6dbb1d6ad84b3eee&type=Issues')

**Stack Trace**
<pre>
QgsGraduatedSymbolRendererWidget::QgsGraduatedSymbolRendererWidget qgsgraduatedsymbolrendererwidget.cpp:510
QgsGraduatedSymbolRendererWidget::create qgsgraduatedsymbolrendererwidget.cpp:411
QgsRendererPropertiesDialog::rendererChanged qgsrendererpropertiesdialog.cpp:251
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QComboBoxPrivateContainer::eventFilter :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties qgisapp.cpp:14341
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent qgslayertreeview.cpp:152
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by rduivenvoorde** [comment]
Hi, this is not the issue tracker for QGIS desktop, but for our website.
Please create an issue there: https://github.com/qgis/qgis/issues
Also please provide more information, for example data which creates this crash
Closing here.

**Comment by FedericaPalmieri** [comment]
I hope I created the issue in the right place. let me know. Thanks
________________________________
Da: Richard Duivenvoorde <notifications@github.com>
Inviato: giovedì 23 aprile 2020 07:14
A: qgis/QGIS-Website <QGIS-Website@noreply.github.com>
Cc: FedericaPalmieri <federicapalmieri@hotmail.com>; Manual <manual@noreply.github.com>
Oggetto: Re: [qgis/QGIS-Website] Crash in Graduated Symbols renderer (#749)


Closed #749<https://github.com/qgis/QGIS-Website/issues/749>.
