### ISSUE TITLE
Updating plugin on https://plugins.qgis.org/plugins/

### ISSUE THREAD

**Issue by romariocarvalhoneto** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#751]
## Description
When click in the "Owners" drop-down list (a droplist box, very big by the way), if you don't have the name you search for, or somehow, you just clicked inside of it, there is no way to "unclick" it, and some random person will be classified as Owner of your plugin. Down here is my plugin URL, but could be anyone's. 
![problema](https://user-images.githubusercontent.com/52353524/81013344-5c38f600-8e31-11ea-84ff-db8f1f88d76c.jpg)

Page URL: https://plugins.qgis.org/plugins/bhcgeoqgis/update/

**Comment by romariocarvalhoneto** [comment]
I uploaded my plugin 2 years ago and already had many downloads, but I accidentally DELETED it. THE PROBLEM HAPPENED when I was updating it and I clicked in the "Owners" looking to find my name, and it was not there. But somehow, when you just click inside of it to search yourself (to type some name), there is no way to "unclick" it, and some random person was classified as Owner. So after I saved it (I did't now this would be a problem), there was no way to change it. I tested to click in the name of that random person and under his "repository" there was my plugin as if he was Owner under his name. There, there was the possibility of me deleting "his" plugin. So I did it, not knowing that would delete under me too. So now my plugin has been deleted and I hope it may be replaced just as my old one was, with the number of downloads, stars and everything, and still in the GitHub.

**Comment by rduivenvoorde** [comment]
@romariocarvalhoneto please let me know what your (new?) username is for plugins.qgis.org

I had a look at the server, but the only bhcgeoqgis.zip I can find is very recent (2020), ALSO in a backup of 2018 and older... But at least I can revive the recent one for you if you sent me an username.
The others you apparently really deleted?
Or did you use another name for the zip? I searched for `*bhc*`

**Comment by romariocarvalhoneto** [comment]
My username still the same: romariocarvalho. The name of the zip is
bhcgeoqgis. I did not change the name of the zip and the one I uploaded is
the same as the old one. He still at the GitHub (
https://github.com/romariocarvalhoneto/BHCgeo).
Will it be revived with the number of downloads and star I previously had?
Its very important to me.

Em ter., 5 de mai. de 2020 às 05:34, Richard Duivenvoorde <
notifications@github.com> escreveu:

**Comment by rduivenvoorde** [comment]
For what I know you start from scratch yes, unless we are going to 'fix' the database by hand. If it is THAT important, please sent an email to PSC, but it is extra work for us, we have never done that, and I prefer to not do this kind of things. So I would just add it as a new plugin.
(if I search for bhc now I see 6x None.. I think you cleaned up to thorough...)

**Comment by romariocarvalhoneto** [comment]
OK. I did send an email to PSC. By the way, the name of the plugin is BHCgeo but the name of the zip folder is bhcgeoqgis. I would thank you if my "new" old plugin may be available to download. Its better than nothing. Another question just came now: When we add a new version of the plugin, the number of downloads restart counting or just keep up?

**Comment by mbernasocchi** [comment]
@elpaso would there be a way at all to recover those number?

**Comment by timlinux** [comment]
# Restore download count

@romariocarvalhoneto so I looked in a backup of the database from a few days ago:

```
plugins.qgis.org=# select * from plugins_pluginversion where plugin_id =1753;
  id  | plugin_id |          created_on           | downloads | created_by_id | min_qg_version |     version     | changelog |           package            | experimental | approved | max_qg_version | external_deps 
------+-----------+-------------------------------+-----------+---------------+----------------+-----------------+-----------+------------------------------+--------------+----------+----------------+---------------
 8873 |      1753 | 2019-07-03 02:40:18.274651+01 |       425 |          3830 | 003.000.000    | 000.001.###.### |           | packages/2019/bhcgeoqgis.zip | t            | t        | 003.099.000    | 
(1 row)
```

From that we can see you had 425 downloads.

Then I updated the production database:

```
qgis_plugins=# select * from plugins_plugin where name like '%BHC%';  
  id  |          created_on           |         modified_on          | created_by_id |                   homepage                    | package_name |  name  |                     description                     |           icon           | downloads | featured |                  repository                   |                       tracker                        | deprecated |                                author                                |            email            | rating_votes | rating_score |                                                                                                                                                                                                                                                                                                                                                                                                                                         about                                                                                                                                                                                                                                                                                                                                                                                                                                         | server 
------+-------------------------------+------------------------------+---------------+-----------------------------------------------+--------------+--------+-----------------------------------------------------+--------------------------+-----------+----------+-----------------------------------------------+------------------------------------------------------+------------+----------------------------------------------------------------------+-----------------------------+--------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------
 2051 | 2020-05-04 19:40:13.725081+00 | 2020-05-05 21:01:47.84633+00 |          3830 | https://github.com/romariocarvalhoneto/BHCgeo | bhcgeoqgis   | BHCgeo | Calculates the Climatic Water Balance in each pixel | packages/2020/figBHC.png |         2 | f        | https://github.com/romariocarvalhoneto/BHCgeo | https://github.com/romariocarvalhoneto/BHCgeo/issues | f          | Carvalho Neto, R.M. - UFSM; Cruz, J.C. - UFSM; Cruz, R.C. - UNIPAMPA | romariocarvalho@hotmail.com |            0 |            0 | The Climatic Water Balance (CWB or BHC in portuguese) of Thornthwaite and Mather (1955) is a soil water monitoring method that considers the soil as an active ingredient in its calculation as a reservoir that hinders the exit of water as it dries. In periods where the total Precipitation (P) is less than the Potential Evapotranspiration (PET), the retained water becomes a function of this potential demand (P-PET < 0) and of the Available Water Capacity (AWC) used in the calculations. If there is a sequence of periods in this condition, the water retained in the soil will be a sequential function of the accumulated negative values of P - PET, that is, the accumulated potential loss. Therefore, this Plugin needs as input, 12 rasters of P, 12 rasters of ETP and one raster of the AWC, being these 12 rasters one raster for each month of the year. | f
(1 row)
```

Then I used the id of the plugin to verify the version:

```
qgis_plugins=# select id, plugin_id, downloads from plugins_pluginversion where plugin_id=2051;
  id   | plugin_id | downloads 
-------+-----------+-----------
 10240 |      2051 |         2
(1 row)
```

Finally, I updated it to match the download count +2 from the new uploaded release:

```
qgis_plugins=# update plugins_pluginversion set downloads=427 where id=10240;
UPDATE 1
```

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/178003/81224056-fe4a1100-8fde-11ea-868b-2888784dc655.png">

# Restore download count

On my restored backup:

```
plugins.qgis.org=# select rating_votes, rating_score from plugins_plugin where name like '%BHCgeo%';
 rating_votes | rating_score 
--------------+--------------
            1 |            5
(1 row)
```

On production:

```
qgis_plugins=# select rating_votes, rating_score from plugins_plugin where name like '%BHCgeo%';
 rating_votes | rating_score 
--------------+--------------
            0 |            0
(1 row)


```

Reinstating on the production:

```
qgis_plugins=# update plugins_plugin set rating_votes=1, rating_score=5 where id= 2051;
UPDATE 1
qgis_plugins=# select rating_votes, rating_score from plugins_plugin where name like '%BHCgeo%';
 rating_votes | rating_score 
--------------+--------------
            1 |            5
(1 row)
```

<img width="364" alt="image" src="https://user-images.githubusercontent.com/178003/81224861-4289e100-8fe0-11ea-8f26-a518134ea5a3.png">


<img width="1252" alt="image" src="https://user-images.githubusercontent.com/178003/81224806-3140d480-8fe0-11ea-89cc-0da6b3a9c992.png">




Everything should be back like it was. Please click with caution going forward!

**Comment by mbernasocchi** [comment]
thx @timlinux

**Comment by romariocarvalhoneto** [comment]
![problemaContinua](https://user-images.githubusercontent.com/52353524/81226846-dc8e6100-8fc1-11ea-9062-91587a7163ed.jpg)
![problemaContinuaManager](https://user-images.githubusercontent.com/52353524/81226875-e6b05f80-8fc1-11ea-95de-1112fb03ea16.jpg)

It still not showing the downloads.

**Comment by timlinux** [comment]
one more thing to get the total downloads updated:

```sql
qgis_plugins=# update plugins_plugin set downloads=430 where id=2051;
UPDATE 1
qgis_plugins=# select id, downloads from plugins_plugin where name like '%BHCgeo%';
  id  | downloads 
------+-----------
 2051 |       430
(1 row)
```

@romariocarvalhoneto please wait again for the cache to update

**Comment by romariocarvalhoneto** [comment]
@timlinux Thank you so much. It's solved now.
