### ISSUE TITLE
 Algorithm 'Polygonize (raster to vector)

### ISSUE THREAD

**Issue by ZbigniewE** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#757]
**Hello, I have a problem with a QGIS tool**

When I try to convert a raster file to vector with the (Algorithm "Polygonize" (raster to vector) tool, it finally says that the resulting layer were not generated correctly.
I don't know what to do.
It is a raster tif.
 with the slope of a study area.

I hope you help me, thanks.

**Comment by ZbigniewE** [comment]
*QGIS3.4 Madeira

**Comment by DelazJ** [comment]
@ZbigniewE Please ask for help in qgis-user list (see [support channels](https://qgis.org/en/site/forusers/support.html)). You'll have more chance there, with some more details (data type, size, parameters...).
This repository is actually dedicated to issues related to the main [website of QGIS project](https://www.qgis.org).
Closing. Thanks for your understanding.
