### ISSUE TITLE
'QGIS standalone installatiepakket Versie 3.12' URL not found

### ISSUE THREAD

**Issue by Aarsr1** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#759]
De downloadlink van 'QGIS standalone installatiepakket Versie 3.12 (64 bit)' werkt niet.
https://ftp.osuosl.org/pub/osgeo/download/qgis/windows/QGIS-OSGeo4W-3.12.3-2-Setup-x86_64.exe
Not Found
The requested URL /~jef/QGIS-OSGeo4W-3.12.3-2-Setup-x86_64.exe was not found on this server.

**Comment by DelazJ** [comment]
can you check it's still the case?

**Comment by mbernasocchi** [comment]
@DelazJ I just checked and it works for me but my url is very differen (https://qgis.org/downloads/QGIS-OSGeo4W-3.12.2-2-Setup-x86_64.exe).
@Aarsr1 on which page did you try?

**Comment by Aarsr1** [comment]
Hello,

It is fixed.
Thank you very much!

Kind regards,
Rosann Aarsen

Van: Harrissou Sant-anna <notifications@github.com>
Verzonden: vrijdag 15 mei 2020 15:29
Aan: qgis/QGIS-Website <QGIS-Website@noreply.github.com>
CC: Rosann Aarsen <R.Aarsen@heerhugowaard.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [qgis/QGIS-Website] 'QGIS standalone installatiepakket Versie 3.12' URL not found (#759)


can you check it's still the case?
