### ISSUE TITLE
redirect charter page

### ISSUE THREAD

**Issue by mbernasocchi** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#762]
## Description
https://qgis.org/en/site/getinvolved/governance/charter.html
gives 404 since it was moved to 
https://qgis.org/en/site/getinvolved/governance/charter/index.html

**Comment by mbernasocchi** [comment]
@rduivenvoorde or @DelazJ is there a way to do redirects in our sphinx? thanks

**Comment by DelazJ** [comment]
@mbernasocchi from within the website? In which case you can use the internal link, ie
```
:ref:`charter of QGIS <psc>`
```
instead of the url (psc is the anchor of the chapter when in edit mode)

**Comment by mbernasocchi** [comment]
> @mbernasocchi from within the website? In which case you can use the internal link, ie
> 
> ```
> :ref:`charter of QGIS <psc>`
> ```
> 
> instead of the url (psc is the anchor of the chapter when in edit mode)

that creates a link no? i meant an automatic redirect

**Comment by rduivenvoorde** [comment]
@mbernasocchi not that I know, we would end up with such redirects in the apache config, which is possible, we have already a lot of them (old ones from years ago...)
Another option I googled:
https://github.com/sphinx-contrib/redirects
Not sure what the best way is...

**Comment by rduivenvoorde** [comment]
Mmm, tried:

```
Redirect 301 /(.*)/site/getinvolved/governance/charter.html  /$1/site/getinvolved/governance/charter/index.html
```

Seems not to work.

An advantage of using the javascript contrib module above is that everybody can do this in github... So maybe try that out?

**Comment by DelazJ** [comment]
Oups!
I was quite surprised by the question. I should have read it correctly; **redirect** was THE word. Sorry for the noise.
> An advantage of using the javascript contrib module above is that everybody can do this in github... So maybe try that out?

Agreed! A solution that everyone can maintain would be good, indeed.

**Comment by rduivenvoorde** [comment]
Ok tried the above mentioned contrib, but I think it is not working:
- it is old and unmaintained (written for python2)
- I made it working but all it does is write out the template to another dir, so not really a redirect...

Maybe some other redirect guru can try to make this work in our http conf? @jef-n maybe you can have a look?

I also tried to create a charter.rst with some raw::html with a line of javascript, but then you end up with Sphinx really willing to put that page in an index ...

**Comment by DelazJ** [comment]
Funnily, I also tried the Sphinx extension yesterday with no success. I even tried it's forks 😁 because this is something we could need for the docs, too.
>  also tried to create a charter.rst with some raw::html with a line of javascript, but then you end up with Sphinx really willing to put that page in an index ...

Even if you add the :orphan: role to the file?

**Comment by rduivenvoorde** [comment]
@DelazJ Thanks, I did not know the :orphan: role... Adding that one works: 

https://qgis.org/en/site/getinvolved/governance/charter.html

(did not build all languages yet...)

So this  should be some temporary fix?

**Comment by rduivenvoorde** [comment]
@mbernasocchi maybe we should be a little careful to reshuffle paths in the website (as there are still only 2 files in the charter dir currently. On hindsight it probably would have been easier to leave it as is and add charter-old.rst there :-) )

**Comment by mbernasocchi** [comment]
@rduivenvoorde you're absolutely right. when I first did it I thought about having one rst page per statute but it does not make sense and I didnt think about SEO.
I think having an easy solution to redirect is still a nice thing. thanks for trying!

**Comment by mbernasocchi** [comment]
@rduivenvoorde do you think I should revert the move?

**Comment by rduivenvoorde** [comment]
Mwa, maybe. Then we do not have some 'orphan', but if you think there will be another 'chapter' I would leave it as is.

**Comment by mbernasocchi** [comment]
@rduivenvoorde I did a check on google, bing, ecosia, duckduckgo, yahoo and all already picked up the new structure. so I'm closing this and leaving as is.
