### ISSUE TITLE
Download server down - 3.12

### ISSUE THREAD

**Issue by Tarry-M** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#764]

**Comment by agiudiceandrea** [comment]
Fixed in 4651e951d13d104ff5324c944cf5d1acc71d9b78

**Comment by mbernasocchi** [comment]
@agiudiceandrea can we close this?

**Comment by agiudiceandrea** [comment]
Hi @mbernasocchi, I think this bug report can be closed even without positive feedback from the author, but I'm sorry, I cannot do it.
