### ISSUE TITLE
Api Docs of 3.4 miss main-nav bar: unable to use now

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#773]
I know 3.4 is old, so not sure it is still build...
But current online version: https://qgis.org/api/3.4/ is unusable because it lacks the div 'main-nav' with which you can navigate into classes etc en search for something: 

![Screenshot-20200528095336-990x255](https://user-images.githubusercontent.com/731673/83114317-1cc89700-a0c9-11ea-928b-f5d183a0d621.png)

For 3.12 for example it looks like:

![Screenshot-20200528095258-950x265](https://user-images.githubusercontent.com/731673/83114235-0589a980-a0c9-11ea-8f46-8a4b51c43e4e.png)

@jef-n Not sure if it is still possible to build/fix this?

**Comment by agiudiceandrea** [comment]
I see the top nav bar for both 3.4 and 3.12 api docs:
![image](https://user-images.githubusercontent.com/16253859/83359882-82dd4480-a37d-11ea-9865-7a62945c5ef9.png)
![image](https://user-images.githubusercontent.com/16253859/83359889-97b9d800-a37d-11ea-8ddd-ef2914e575c5.png)

The docs result generated respectively on Jan 19 2020 and on Mar 21 2020.

**Comment by rduivenvoorde** [comment]
Ah, sorry, yes. @jef-n fixed this within a couple of minutes. I forgot to close this one. Thanks for reminding.
