### ISSUE TITLE
plugins disabled

### ISSUE THREAD

**Issue by caseyjacobs199** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#775]

**Comment by rduivenvoorde** [comment]
I do not have a clue what you mean with this two words.
This is the webSITE issue tracker, not the one for QGIS desktop application.
Closing for now, please reopen to provide more information if you issue is about the website.
If about QGIS itself, go https://github.com/qgis/QGIS/issues but use more words :-)
