### ISSUE TITLE
English Download Page 'current version is QGIS 2.0.0'

### ISSUE THREAD

**Issue by znseaman** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#78]
On the English [Download](http://qgis.org/html/en/site/forusers/download.html) page, the sentence starting with 'The current version is QGIS 2.0.0' should be changed to 2.0.1.

**Comment by rduivenvoorde** [comment]
fixed in 9a73147b7e8cd8c217e6d375076d4b3c6c1a7901
