### ISSUE TITLE
Broken link to slackware packages

### ISSUE THREAD

**Issue by openstrike** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#783]
## Description

The link to download Slackware packages goes to http://qgis.gotslack.org/ but that FQDN does not exist. The link should ideally be updated to wherever the Slackware packages currently reside.

Page URL: https://www.qgis.org/en/site/forusers/alldownloads.html#slackware

**Comment by rduivenvoorde** [comment]
@openstrike not being an Slackware user myself I tried to google where they have packages.
One thing I see is searching here for 'qgis':
https://packages.slackware.com/
does not reveal packages...

Most 'news' links are 2016 or 2017, is Slackware still alive? Or should we just remove it from the Distro list untill somebody comes with the right place?

**Comment by openstrike** [comment]
Yes, Slackware is very much still alive (see eg. the [current changelogs](http://www.slackware.com/changelog/current.php?cpu=x86_64)). We are using it which is why I was looking at the link in the first place.

The only semi-official reference to qgis I could find is the slackbuild entries such as https://slackbuilds.org/repository/14.2/gis/qgis/?search=qgis so perhaps that's the most appropriate link for now? It is probably what I would use to install it.

**Comment by rduivenvoorde** [comment]
@openstrike are you able to do a PR for this?

**Comment by openstrike** [comment]
Sure - leave it with me.

**Comment by DelazJ** [comment]
Fixed in #784
