### ISSUE TITLE
parentheses and self-assembly options

### ISSUE THREAD

**Issue by Edwrom** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#789]
This happens in Qgis 3.14.0, Windows 10 version
1 - Parentheses
New layer of shapefile polygons.
Adding a new field in the text attributes table (40 long) automatically adds parentheses in this new column.

2- self-assembly 
Shapefile polygon cape
A main polygon (AOI) was drawn at the beginning.
Within this polygon other polygons are digitized. With the self-assembly and topology editing options, the goal is for polygons to properly fit their neighboring polygons and share nodes. There is no problem with snapping, the problem is that when the new polygon is closed, it does not take the shape of neighboring polygons.

**Comment by DelazJ** [comment]
Hi @Edwrom 
Issues with the software should be reported at https://github.com/qgis/QGIS/issues.
This repository is for issues with [QGIS web site](https://qgis.org). I'm then closing; please report there, with screenshots if possible and as separate issues.
Thanks

**Comment by Edwrom** [comment]
thank's
