### ISSUE TITLE
The reference to RHEL/Centos are outdated... should I use the fedora install?

### ISSUE THREAD

**Issue by jringoot** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#791]
On [the downloadpage](https://www.qgis.org/en/site/forusers/alldownloads.html) a reference is made to 
[The ELGIS repository](http://elgis.argeo.org/) for RHEL, CentOS, Scientific Linux
It is marked as "Legacy".

I wonder if it is safe to install the fedora packages instead.

**Comment by DelazJ** [comment]
>I wonder if it is safe to install the fedora packages instead.

@jringoot if you not yet got your answer, you better ask on qgis user mailing list (see [support channels](http://qgis.org/en/site/forusers/support.html)).
This repository is actually dedicated to issues related to the main website of QGIS project.

**Comment by agiudiceandrea** [comment]
I think this could be closed now.

**Comment by DelazJ** [comment]
Indeed, no more rhel there. Thanks @agiudiceandrea
