### ISSUE TITLE
QGIS 3.14 missing from ubuntu xenial repository

### ISSUE THREAD

**Issue by Thra11** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#793]
## Description
Following these instruction: https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntus suggests QGIS 3.14 should be installed. However, the ubuntu xenial repository only has 2.18 (See here: https://qgis.org/ubuntu/dists/xenial/main/binary-amd64/Packages)

Can't tell if this is an intentional decision to keep xenial on an older version, a build failure with 3.14 on xenial which hasn't been resolved yet, or just an oversight.

Page URL: https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

**Comment by DelazJ** [comment]
Hi @Thra11 
I don't remember the last supported version on Ubuntu Xenial but Recent versions of QGIS have dependencies (versions) that are not available on Ubuntu Xenial, so we can not provide packages. Supported distro for the active versions of QGIS are listed at https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu-advanced

**Comment by DelazJ** [comment]
I think we can close this one (xenial eol, 3.14 eoled)
