### ISSUE TITLE
Bug Nuclei

### ISSUE THREAD

**Issue by DenisArch88** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#795]
Crash ID: 4b9e7975f5393e789e4dc3ec4d91edc848953dcc

Stack Trace

QgsLayout::reportContext qgslayout.cpp:369
QgsLayoutDesignerDialog::exportReportToPdf qgslayoutdesignerdialog.cpp:3664
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by DelazJ** [comment]
Hi @DenisArch88 
This is the repository of the website of QGIS, aka https://qgis.org. For issues in application, you should report at https://github.com/qgis/QGIS/issues (with details on version, platform, what you were doing...) Thanks.
