### ISSUE TITLE
Web version downloader

### ISSUE THREAD

**Issue by LonelySquid** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#799]
## Remote downloading QGIS version

Dear QGIS,

I was trying to build a webscraper to get the version of QGIS and to download the latest version, using pythons BeautifulSoup module. But I found out that the website has a protection against it. O.O That is not a problem of course! But.. it made me wonder, does QGIS offer a way to remotely check and download\update the QGIS version without having to visit the website every time? If so, could someone explain me how or point me in the right direction? Much appriciated! 

Yours Sincerely,
Aqua

Page URL: https://qgis.org/nl/site/forusers/download.html

**Comment by jef-n** [comment]
QGIS notifies you (from https://qgis.org/version.txt or https://qgis.org/version-ltr.txt).
apt and the OSGeo4W-Installer will just upgrade if there's something new.
You could also check https://github.com/qgis/QGIS-Website/blob/master/source/schedule.py if you're after the windows standalone installer.  That used to fill the links in https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/forusers_download.html#L63
