### ISSUE TITLE
QGIS 3.8.3 crushing at closure

### ISSUE THREAD

**Issue by pilipr** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#800]
QGIS 3.8.3 crushing at closure report is as follows Crash ID: f4475de87e6a815390b3363a83d3fb7ae10fc9c9

Stack Trace

proj_lpz_dist :
proj_lpz_dist :
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

QGIS Bug report should not be reported here.
Check https://qgis.org/en/site/getinvolved/development/bugreporting.html for the proper repository.

Tickets created here will be closed.

**Comment by DelazJ** [comment]
Hi @pilipr 
As stated in the template of the issue report:
> QGIS Bug report should not be reported here.
Check https://qgis.org/en/site/getinvolved/development/bugreporting.html for the proper repository.
>Tickets created here will be closed

Issues with the software should be reported at https://github.com/qgis/QGIS/issues.
In your case, 3.8 development is finished almost a year ago so you need to upgrade to active version (currently 3.10 LTR and 3.14) and check whether you still have the bug before any report.
Thanks
