### ISSUE TITLE
QGIS CRASHED WHEN I COMPOSED A MAP OF 8D0 SIZE

### ISSUE THREAD

**Issue by TWRIS** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#804]
## User Feedback

IT CRASHED WHEN I COMPOSED A MAP OF 8D0 SIZE

## Report Details

*Crash ID*: 280187b942403ac875975fcbc8a9c1c2625fe983

*Stack Trace*
<pre>
memcpy :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::penChanged :
QPolygonF::united :
QPolygonF::united :
QPolygonF::united :
QRasterPaintEngine::fill :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QgsFillSymbolLayer::_renderPolygon :
QgsSimpleFillSymbolLayer::renderPolygon :
QgsFillSymbol::renderPolygonUsingLayer :
QgsFillSymbol::renderPolygon :
QgsLayoutItemPage::draw :
QgsLayoutItem::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion :
QgsLayoutExporter::renderRegionToImage :
QgsLayoutExporter::renderPageToImage :
QgsLayoutExporter::createImage :
QgsLayoutExporter::exportToImage :
QgsVertexEditorModel::flags :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

QGIS Bug report should not be reported here.
Check https://qgis.org/en/site/getinvolved/development/bugreporting.html for the proper repository.

Tickets created here will be closed.
-->

**Comment by DelazJ** [comment]
Hi @TWRIS 
This is the repository of QGIS website, not the application's.
3.8 is no longer maintained so update to either 3.10 or 3.14 and if the bug is still there, report at https://github.com/qgis/QGIS/issues.
Thanks.
