### ISSUE TITLE
QSWAT+ import files for version 3.14 is overridden every time

### ISSUE THREAD

**Issue by soroush721375** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#806]
hello . I'm working for a project by QSWAT+ .Every time I'm going to import a file like .SHPs it throw an error and override the process .what can I do?

**Comment by DelazJ** [comment]
Hi @soroush721375 
This repository is to report issues encountered when browsing the QGIS website at https://qgis.org, not to report application issues. Furthermore, I'd say this is probably more a question/issue to the QSWAT project than QGIS itself. Report there with detailed steps and error message.
I'm closing. Thanks for your understanding.
