### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Aly2k17** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#812]
Plugin was disabled do to crashing  QGIS during last startup on my MacBook Air 2018. Plugin needs to be re-enabled and this issue needs to be solved.

**Comment by DelazJ** [comment]
Hi @Aly2k17 
This repository is dedicated to [QGIS Website](https://qgis.org) issues. Not for the application's.
Try running QGIS with [a clean profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles). Probably some plugin you are running is faulty and you should report in the plugin bug tracker. If QGIS is the faulty, then report in the [application issue tracker](https://github.com/qgis/QGIS/issues) with more details on what you were doing before crashes, version, crash report....
I'm closing.
Thanks.
