### ISSUE TITLE
Instalation Problem QGIS 3.14 linux debian testing

### ISSUE THREAD

**Issue by rudineyspereira** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#818]
Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 78, in 
    import qgis.gui
  File "/usr/lib/python3/dist-packages/qgis/gui/__init__.py", line 25, in 
    from qgis._gui import *
ValueError: PyCapsule_GetPointer called with incorrect name

Versão do Python:
3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]

QGIS versão:
3.14.16-Pi 'Pi', a235a149f0

Caminho para o Python:
['/usr/share/qgis/python', '/home/rudiney/.local/share/QGIS/QGIS3/profiles/default/python', '/home/rudiney/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']

**Comment by rduivenvoorde** [comment]
This is the bugtracker of the qgis website, please create an issue here: https://github.com/qgis/QGIS/issues
