### ISSUE TITLE
Blog link on website is outdated/wrong

### ISSUE THREAD

**Issue by jctull** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#819]
The website has a ling for "Blog" that points to http://planet.qgis.org, but the url seems to have been updated. The link should be changed to http://plugins.qgis.org/planet to point to the aggregated QGIS blog page.

**Comment by rduivenvoorde** [comment]
Thanks, I updated them now, will be available tomorrow or after next build
