### ISSUE TITLE
installer URL is dead

### ISSUE THREAD

**Issue by l-fujiwara** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#826]
## Description

Page URL: https://ftp.osuosl.org/pub/osgeo/download/qgis/windows/QGIS-OSGeo4W-3.10.11-2-Setup-x86_64.exe

**Comment by rduivenvoorde** [comment]
We updated links, see (english website) other language sites are building: 
https://qgis.org/downloads/QGIS-OSGeo4W-3.10.11-2-Setup-x86_64.exe

**Comment by l-fujiwara** [comment]
I checked it! Thanks!
