### ISSUE TITLE
Download link werkt niet> error 404 

### ISSUE THREAD

**Issue by Bqurius** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#827]
## Download link werkt niet

Page URL: https://www.norbit.de/~jef/QGIS-OSGeo4W-3.16.0-2-Setup-x86_64.exe

**Comment by rduivenvoorde** [comment]
Wrong link, please see english website, others will follow, good link is:
https://qgis.org/downloads/QGIS-OSGeo4W-3.16.0-1-Setup-x86_64.exe
