### ISSUE TITLE
Problem rasterizing the defined field in ''rasterize SAGA'' tool

### ISSUE THREAD

**Issue by kalliopikout** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#842]
Hello,

I am trying to rasterize a point vector which I import as scv file into QGIS. It contains the X,Y coordinates and a third field which is the transmissivity value per point. I want to create a raster where each pixel contains the value of this third field.
But while I am using the SAGA tool for rasterization( I choose as attribute value this third field), the produced raster stores per pixel the X value...

I am using the latest QGIS Desktop version 3.16 Hannover.

Thank you in advance,
Kalliopi

**Comment by kikislater** [comment]
Your issue is not related to qgis website but user usage.
Nobody will answer you as you are requesting a problem on qgis website whereas you use qgis desktop ...

**Comment by kalliopikout** [comment]
> Your issue is not related to qgis website but user usage.
> Nobody will answer you as you are requesting a problem on qgis website whereas you use qgis desktop ...

Oh yes, that's right. I just noticed,  thanks!

**Comment by DelazJ** [comment]
Indeed better use the [user mailing list](https://qgis.org/en/site/getinvolved/mailinglists.html#qgis-mailinglists).
I'm then closing.
