### ISSUE TITLE
QGIS Crash During Loading Shapefiles written by geopandas.

### ISSUE THREAD

**Issue by DataGeoranger** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#843]
ArcGIS and Global Mapper Can both load this shapefile no issues, only QGIS crashes. Thanks for looking into it.

Crash ID: 7f7770fea3ba8c6e5bbb45c77b5f27e2aab94ad0

Stack Trace

geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
GEOSEquals_r :
OGRToOGCGeomType :
OGRLayer::FilterGeometry :
SHPPartTypeName :
QgsSQLiteExpressionCompiler::operator= :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsMapRendererParallelJob::cancelWithoutBlocking :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by rduivenvoorde** [comment]
hi @DataGeoranger, this is the issue tracker for the QGIS Website. 
Please move this issue to: https://github.com/qgis/QGIS/issues
AND provide a minimal example of a shapefile (created by geopanda's) which triggers the crash in QGIS.

I close this one here.
