### ISSUE TITLE
Missing image on QGIS donation page

### ISSUE THREAD

**Issue by Trigonatus** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#844]
On this page:
https://www.qgis.org/en/site/getinvolved/donations.html
There is a missing image (QGIS logo) in the Stripe section.

**Comment by rduivenvoorde** [comment]
Mmm, that is funny. I'm 100% sure I fixed that last week...
Thanks for letting us know. But we have to update the stripe stuff anyway in upcoming weeks so probably I leave as is.

**Comment by Trigonatus** [comment]
It may be a trivial issue but it did make me pause for thought before donating.

**Comment by rduivenvoorde** [comment]
Yeah, you are probably right. Ok fixed again then :-)
Thanks.
