### ISSUE TITLE
Download of "Latest release (richest on features)" for Mac OS X downloads 3.16.1 instead of 3.16.2

### ISSUE THREAD

**Issue by fgfletcher** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#848]
## Description
Page URL:https://qgis.org/en/site/forusers/download.html
states that "QGIS 3.16.2  'Hannover' and was released on 21.12.2020"
however downloading "Latest release (richest on features)" for Mac OS X downloads 3.16.1 from November...

**Comment by rduivenvoorde** [comment]
Because different volunteers/individuals package QGIS for the different Operating Systems or distro's, some can be a little later then the 'official' (which we do not have) date. When the largest user-groups (Windows/Debian) are done we change the text on the download site. So please be patient...
