### ISSUE TITLE
download page issues

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#85]
via mailinglist: http://lists.osgeo.org/pipermail/qgis-user/2013-September/023993.html

This page:
http://www.qgis.org/en/site/forusers/download.html

a) Clicking on the "download for" doesn't work if JavaScript is off. Could you make them default to open and then hide them with JavaScript.

b) There's a link to: http://www.qgis.org/en/site/forusers/alldownloads.html
That page in turn has a "double click installer" which is actually for 1.8.

**Comment by rduivenvoorde** [comment]
also see #93 and #59

**Comment by eshon** [comment]
I cannot find the link that is incorrect for task b) on the alldownloads.html page.

Tasks a) has been fixed.

**Comment by rduivenvoorde** [comment]
this link has been fixed earlier. It now just contains to the windows part of the download page.

You closed #59, but I do not see a commit referring to it? Is it fixed already?
