### ISSUE TITLE
'Could not create print device' QGIS 3.14

### ISSUE THREAD

**Issue by ggjosephine** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#856]
Created a geospatial PDF earlier today. Went to make another then got error message 'could not create print device'. Every step of creation was exactly the same.

**Comment by DelazJ** [comment]
Hi @ggjosephine 
Wrong place to report application issues. This is for our website. Please report at https://github.com/qgis/QGIS/issues and remember to add details on your working environment and on what you meant by `every step of creation`.
Closing.
