### ISSUE TITLE
Website could guide people downloading QGIS more consistently

### ISSUE THREAD

**Issue by AlisterH** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#858]
## Description

Page URL: https://qgis.org/en/site/forusers/alldownloads.html
1. This page says "For new [windows] users we recommend the standalone installers."
But the [main installers page](https://www.qgis.org/en/site/forusers/download.html) has the OSGeo4W installers above the standalone installers.  So if users get there without reading the alldownloads page they are most likely to download the OSGeo4W installer as it is the first option they see.
If the recommendation on the alldownloads page is right, the main installers page should provide the standalone installers above the OSGeo4W installers.  Otherwise the recommendation should be amended.

2. The Windows section has a "Note the warning" link at the bottom, but it seems to have lost its context.  There is also a "(note the warning)" link in the main "QGIS installers" section and the Linux section, but these are in context (they are each at the end of a sentence about installing testing builds).  To give it some context, should the "Note the warning" text in the Windows section be expanded (e.g. "Before installing any of the nightly builds note the warning"), or perhaps made into another footnote of the table above it?

**Comment by rduivenvoorde** [comment]
@AlisterH I agree on both of you points. Can you do a PR yourself? Or should I just do it.
About point 2, maybe make the 'note the warning' part of the 'versions table just above it' in the lines about development version?

**Comment by jef-n** [comment]
I'd recommend the OSGeo4W installer for regular users.

**Comment by rduivenvoorde** [comment]
@jef-n personally, me too. But that is not what the site tells us, AND (I think) the majority of Windows users are able to use...

**Comment by jef-n** [comment]
It recommends the standalone installer to new users only.

**Comment by AlisterH** [comment]
See pull request #886
Re point 1, I have just added hints rather than changing the order as I originally suggested.  Hopefully seeing "recommended for regular users" will prompt new users to keep reading and see the "recommended for new users".  Or do you guys think thIs is a cop-out?

**Comment by DelazJ** [comment]
Anything left or can we close this report?
