### ISSUE TITLE
QGIS mistakenly depicting the Crimean peninsula in the app

### ISSUE THREAD

**Issue by olekrd7** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#859]
QGIS app for some reason depicts and defines Crimea and the entire peninsula as part of Russia although the UN, OSCE, EU and many other international organizations have not recognized the occupation of Crimea by Russia. Hence, according to the international law in the app Crimea should be depicted as part of Ukraine.

**Comment by DelazJ** [comment]
@olekrd7 can you detail which dataset you are referring to, please?

**Comment by olekrd7** [comment]
Yes, this is the most recent large scale countries (version 4.1.0) from natural earth data, so I assume I should inform its creators?

https://www.naturalearthdata.com/downloads/10m-cultural-vectors/

**Comment by DelazJ** [comment]
Sorry, I fail to see where QGIS is in the play, here. Does QGIS provide that data somewhere?
And yes, better keep in touch with data creators. But maybe read the disclaimer at https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-countries/

**Comment by DelazJ** [comment]
So @olekrd7 should we close this one? Afaict, this is a dataset "issue" and the information of what is shown is provided in their metadata. And in all cases it doesn't seem to be a QGIS **website** issue.

**Comment by olekrd7** [comment]
Yes, this case more relates to naturalearthdata error, not to qgis itself.
