### ISSUE TITLE
Error while using raster calculator (NDVI)

### ISSUE THREAD

**Issue by sigitpsetyo** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#861]
I always get this result when i am using raster calculator to define NDVI. Is this software bug or my computer error? I tried re-installed my Qgis many times but the result always same. Plis someone help me:(

![image](https://user-images.githubusercontent.com/67414712/107317733-ccb22900-6acd-11eb-9df1-5b48ca33d051.png)
![image](https://user-images.githubusercontent.com/67414712/107317766-d9cf1800-6acd-11eb-918c-30b9373541c4.png)

**Comment by kikislater** [comment]
Your issue is not related to qgis website but user usage.
Nobody will answer you as you are requesting a problem on qgis website whereas you use qgis desktop ...

**Comment by DelazJ** [comment]
@sigitpsetyo for questions, please use the [mailing list](https://qgis.org/en/site/getinvolved/mailinglists.html#qgis-mailinglists) and provide people enough details about what you do, data you use, what you expect to get... And if it's proven to be a QGIS bug, then the place to report is https://github.com/qgis/QGIS/issues. This repository is for managing the QGIS website. Thanks.
Closing.
