### ISSUE TITLE
[Urls] Mobile Apps for Windows without installers (QField and Input)

### ISSUE THREAD

**Issue by jonnyforestGIS** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#864]
Hi guys,

## Description
Page URL: https://qgis.org/en/site/forusers/download.html#apps
MIssing installers in the  Windows apps URL links for Input and Qfield point to directories without installers. 

## Qfield - empty diretories:
- [x] https://download.opengis.ch/qfield/ci-builds/win/ - OK

- [x] https://download.opengis.ch/qfield/ci-builds/win/beta  - OK

## Input - empty directory:
- [ ] https://www.dropbox.com/s/7su0dvsg4qsgyiy/inputapp-win-x86_64-7fa4844736f549dc12e1def1ac26ad36a994c3ec.exe?dl=0 

@m-kuhn and @saberraz.

Cheers

**Comment by rduivenvoorde** [comment]
@jonnyforestGIS please create an issue on the Input and QField sites, or ping @mbernasocchi or @saberraz

**Comment by jonnyforestGIS** [comment]
Hi @rduivenvoorde  the QField link is working. Only Input is broken. If you want we can close this for now and I try to speak with @saberraz . Cheers
