### ISSUE TITLE
|image8| in index.rst from "visualchangelog318" points to the wrong gif

### ISSUE THREAD

**Issue by TurboGraphxBeige** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#867]
|image8| should point to [this](https://user-images.githubusercontent.com/59714546/101234295-f1cc8a80-368b-11eb-9b52-8f42a4f994a2.gif) gif instead.

**Comment by DelazJ** [comment]
@TurboGraphxBeige could you upload it to the visualchangelog318/images folder and fix the reference at the end of the visualchangelog318/index.rst file, please? Thanks.

**Comment by rduivenvoorde** [comment]
Hi People. please refrain from adding new fixes for a couple of hours....
Andreas added the list of 'notable fixes', AND the url to the author is fixed on changelog.qgis.org, so
I will download a new version (and I'm not 100% sure if that changes the uuid's of the images.
I will try to take other pr's into account, and build and let you know here

**Comment by TurboGraphxBeige** [comment]
@DelazJ I can't upload files there, I don't have write permission.

**Comment by DelazJ** [comment]
By "there", you mean the changelog website (in which case, I think you need (to subscribe and?) ask maintainers, eg @timlinux) or the QGIS website repo (as usual, this is doable through pr from your own fork)?
Anyway, for this round, I think @rduivenvoorde mentioned he fixed the issues in another thread.

**Comment by rduivenvoorde** [comment]
I missed this one, but at will look if I can change it on both places...
At least in the visual changelog in qgis.org it should work...

**Comment by rduivenvoorde** [comment]
And to be sure, what is the original image8 pointing to then?
Or should it just be removed?
This one: https://qgis.org/en/_images/87f084dd1397520cbf91befe3faaccb68a941263-1.gif
for item: https://qgis.org/en/site/forusers/visualchangelog318/index.html#feature-zoom-to-selection-for-multiple-layers
(note that the other pr's I should have included...)

**Comment by TurboGraphxBeige** [comment]
@rduivenvoorde #869 should clarify things.
