### ISSUE TITLE
CSV change data source doesn't work

### ISSUE THREAD

**Issue by quarkcz** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#883]
If I have CSV data layer and change data source through menu, it stops working. 

Problem is, that it looses additional params and while selecting NEW CSV, user can't add them or select them.

When I change data source for CSV file, it has to maintain everything after "?" in source URI, because it's not user editable thing.

**Example:**
_Original source URI:_ file:///C:/Users/kquast/Downloads/RUIAN-SHP/Temp-20210413-OFF.csv?type=csv&maxFields=10000&detectTypes=yes&xField=GPS_X&yField=GPS_Y&crs=EPSG:4326&spatialIndex=no&subsetIndex=no&watchFile=no

_New source URI:_ file:///C:/Users/kquast/Downloads/RUIAN-SHP/Moved-temp-20210413-OFF.csv

**Comment by DelazJ** [comment]
Hi @quarkcz 
Not the right issue tracker. Please report at https://github.com/qgis/QGIS/issues.
Thanks.
