### ISSUE TITLE
Potential Enhancement? Not an issue -  Atlas control

### ISSUE THREAD

**Issue by LucySaluki** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#885]
Hi
I have a multipoint datasets that I want to use for data driven pages in the atlas but I only get the option on the map for Fixed Scale (I can see the logic in this with point data).  However I would like to have the margin around feature option as well. Currently I am using convex_hull( @atlas_geometry )  to control the atlas to move location but it is always at the same fixed scale rather than that varying with the size of the convex hull (plus a percentage if desired).  Could we have it so, where the multipoint has more than one point in the record, the extent  is used with the ability to set a margin around this extent as you are able with polygons now?  Thanks

**Comment by DelazJ** [comment]
Hi @LucySaluki 
Issue reports and feature requests for the application should go to https://github.com/qgis/QGIS/issues. This repository is for the website. Please report there. Thanks for your understanding.
