### ISSUE TITLE
no page about plugin development

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#89]
This page:

http://qgis.org/en/site/getinvolved/index.html

pointed to a page plugindev, which was supposed to tell you how to write a python plugin.

Currently this page was empty, therefor removed, and link put in comments.

When somebody writes the text, we can make link visible again

**Comment by m-kuhn** [comment]
How about listing some good references on the plugin development page [1]? At the moment this is rather crude, while the cookbook is an excellent resource.

E.g:
pyqgis cookbook
gis.stackexchange.com
IRC

http://qgis.org/en/site/getinvolved/development/pythonplugindevelopment.html

**Comment by anitagraser** [comment]
I would suggest to link "Want to write your own Python plugin? Go here: Developing Python plugins" to http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/

**Comment by alexbruy** [comment]
Can we close this? Seems now all links are here

**Comment by anitagraser** [comment]
Looks fine to me.
