### ISSUE TITLE
Debian/Ubuntu install instructions typos

### ISSUE THREAD

**Issue by acrosome** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#890]
Hi, 

In the instructions for a Debian/Ubuntu install there are some errors.  First, I don't think that -qO is a valid operator for wget.  Neither is --1mport a gpg operator.  I think the latter is supposed to be --import

Anyway, I think I figured this out (I just left -qO out and changed --1mport to --import, and it at least runs), but I still get an error:

gpg: no valid openGPG data found

Is the key valid?

If I ignore this and run sudo apt update I get another error:

The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F7E06F06199EF2F2

Then despite having adding the LTS repository to my sources.list file it only installs v2.18 instead of v3.16.  So it seems that there is some sort of problem with the key (or the instructions, and I'm just not smart enough to figure it out).

Thank you.

**Comment by jef-n** [comment]
* `-qO -` is short for `-q -O -`.  By leaving it out you download the key to a file instead of stdout and gpg/apt-key gets no input.
* I don't see `--1mport` anywhere.
* any without the key the qgis.org is ignored and you only get the qgis from your distribution (ie. 2.18) - or you're using an older version that is not supported anymore.

**Comment by rduivenvoorde** [comment]
> Anyway, I think I figured this out (I just left -qO out and changed --1mport to --import, and it at least runs), but I still get an error

@acrosome is it possible that you were looking into a translation (of the site)? If so, let us know which language, then we can (at least) fix a type as `--1import` if we can find it

**Comment by jef-n** [comment]
> is it possible that you were looking into a translation (of the site)? If so, let us know which language, then we can (at least) fix a type as `--1import` if we can find it

I don't find it in qgis2:/var/www/qgisdata/QGIS-Website/live/html either.
