### ISSUE TITLE
Download Link Incorrect for QGIS 3.16.7 LTR

### ISSUE THREAD

**Issue by bitwhyz** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#892]
It appears the download link for QGIS 3.16.7 LTR for MacOS still references the previous 3.16.6 LTR version to be downloaded. 
(See https://qgis.org/en/site/forusers/download.html) and the resulting module that is downloaded still says 3.16.6-Hannover when after installation (Dated April 28, 2021, and is 3.2GB size).
Please provide the updated QGIS 3.16.7 LTR module for MacOS. Thanks!

**Comment by PeterPetrik** [comment]
all available versions can be listed here https://qgis.org/downloads/macos/ltr

the last version is
https://qgis.org/downloads/macos/ltr/qgis_ltr_final-3_16_8_20210619_044746.dmg
