### ISSUE TITLE
the plugin "Quick Map Services" is installed but don't apears in the "web"

### ISSUE THREAD

**Issue by Leonardosantos1236** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#893]
I installed the plugin "Quick Map Services" but this plugin don't apears in te "web"

**Comment by DelazJ** [comment]
Hi @Leonardosantos1236 
Issues with plugins should be reported in the plugin issue tracker. This one is for QGIS website so I'll close your report.
You can also ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)).

**Comment by Leonardosantos1236** [comment]
whre is "plugin issue tracker"?

________________________________
De: Harrissou Sant-anna ***@***.***>
Enviado: sexta-feira, 21 de maio de 2021 10:28
Para: qgis/QGIS-Website ***@***.***>
Cc: Leonardosantos1236 ***@***.***>; Mention ***@***.***>
Assunto: Re: [qgis/QGIS-Website] the plugin "Quick Map Services" is installed but don't apears in the "web" (#893)


Hi @Leonardosantos1236<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLeonardosantos1236&data=04%7C01%7C%7Ca2843906f39549322c7e08d91c5401ed%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637571969399355212%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NTcXQXQBL0onio1XW7FH0KtTgU%2FhQNnqVpq8nW%2B5wOk%3D&reserved=0>
Issues with plugins should be reported in the plugin issue tracker. This one is for QGIS website so I'll close your report.
You can also ask for help in qgis-user list (see support channels<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fqgis.org%2Fen%2Fsite%2Fforusers%2Fsupport.html&data=04%7C01%7C%7Ca2843906f39549322c7e08d91c5401ed%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637571969399365207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nJjZnyB%2FbGz4F1aGicU%2BPTiDGKzIS8NZ7etPQUAwtkw%3D&reserved=0>).

**Comment by DelazJ** [comment]
When you are reading a plugin description from the plugin manager dialog, you have a "More info" section with such an information. This one is https://github.com/nextgis/quickmapservices/issues
