### ISSUE TITLE
Download Link Incorrect for QGIS 3.18.3 (MacOS) 

### ISSUE THREAD

**Issue by alspringsteen** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#894]
Not a big deal, but there is no file available for the 3.18.3 version for Mac (not sure about the other operating systems). When I open QGIS, it tells me there is a new version available, and the website also confirms this, but the actual file that gets downloaded is still 3.18.2 instead of 3.18.3. I can't find a 3.18.3 dmg for download in the 'All Releases' either. 

This is similar to issue #892 for the LTR release. 

Somewhat anecdotal, but I think this happened last time with the 3.18.2 release to me as well. If so, it seems there is some sort of lag between what is actually available on qgis.org and what is posted as available in the text of the site and in the current QGIS app when the user opens it.

**Comment by PeterPetrik** [comment]
all available versions can be listed here https://qgis.org/downloads/macos/pr

last available version is https://qgis.org/downloads/macos/pr/qgis_pr_final-3_20_0_20210618_170557.dmg
