### ISSUE TITLE
Hillshade fails  QGIS version 3.20.0-Odense

### ISSUE THREAD

**Issue by rmarkRCS** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#905]
GDAL command:
gdaldem hillshade "/Volumes/Pegasus32/Arizona/Coconino Co/Chavez Pass/6-1-21/MME/ChavezPassRuins20210611-DEM.tif" /private/var/folders/6b/ys55yq0d6536cj_fgm76458r0000gr/T/processing_txWYOE/ff9c817002544a4bb4b008880069b1f8/OUTPUT.tif -of GTiff -b 1 -z 1.0 -s 1.0 -az 315.0 -alt 45.0
GDAL command output:
/Applications/QGIS 2.app/Contents/MacOS/bin/gdaldem: line 3: /Applications/QGIS: No such file or directory
Process returned error code 127

Runs on previous version.

**Comment by rduivenvoorde** [comment]
Hi, sorry this is the issue tracker for the QGIS-Website please use the one at qgis/qgis for QGIS itself (though this seems a gdal issue?)
