### ISSUE TITLE
Errore su funzione "Mostra totale elementi"

### ISSUE THREAD

**Issue by Fenonx** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#918]
Buongiorno volevo segnalare un problema che riscontrato nella funzione "Mostra totale elementi", nei casi in cui si utilizza lo stile basato su regole con la funzione "ELSE", se successivamente affino la regola con una categoria, non vengono più contati gli elementi, riporto alcuni screenshot esplicativi:

![image](https://user-images.githubusercontent.com/87801777/126607197-849eed03-70da-42d8-be6a-0243663e6335.png)

![image](https://user-images.githubusercontent.com/87801777/126607018-bbeaff57-1569-4bd4-9b6c-74719e99a302.png)

**Comment by DelazJ** [comment]
Hi @Fenonx 
This repository is to manage only [QGIS website](https://qgis.org). For issues with application, report at https://github.com/qgis/QGIS/issues in English and version number (with some more requested information). Please also check beforehand that there's no existing report. Thanks.
Closing...
