### ISSUE TITLE
Latest Versions Not Appearing on macOS Downloads Page

### ISSUE THREAD

**Issue by davidafuller01** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#926]
## Description
PR and LTR available downloads are still on Jun'21 release.

Page URL: https://qgis.org/downloads/macos/

**Comment by agiudiceandrea** [comment]
Also previously reported in this and other related repositories: qgis/QGIS-Website#925, https://github.com/qgis/QGIS-Mac-Packager/issues/136, qgis/QGIS#44381 and qgis/QGIS#44408

**Comment by agiudiceandrea** [comment]
@davidafuller01 see https://github.com/qgis/QGIS-Website/issues/925#issuecomment-894182670

> The macOS packages are ready for use:
> 
> Point Release (PR) 3.20.1
> https://qgis.org/downloads/macos/pr/qgis_pr_final-3_20_1_20210805_162007.dmg
> 
> Long Term Release (LTR) 3.16.9
> https://qgis.org/downloads/macos/ltr/qgis_ltr_final-3_16_9_20210806_022813.dmg
> 
> and Nightly 3.21.0
> https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20210805_123338.dmg

**Comment by DelazJ** [comment]
Let's close it then
