### ISSUE TITLE
Ubuntu gpg key expired?

### ISSUE THREAD

**Issue by valpo** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#928]
## Description

Looks like the gpg key https://qgis.org/downloads/qgis-2020.gpg.key is expired and there is no new key. 

Mathias

**Comment by agiudiceandrea** [comment]
See also https://github.com/qgis/QGIS/issues/44612

**Comment by jef-n** [comment]
Fixed in 7831f972025d4599a122c573a654d6dde4e548a9

**Comment by stragu** [comment]
One last thing: line 301 of source/site/forusers/alldownloads.rst also needs to be changed from 2020 to 2021

**Comment by agiudiceandrea** [comment]
> One last thing: line 301 of source/site/forusers/alldownloads.rst also needs to be changed from 2020 to 2021

Already changed. See https://github.com/qgis/QGIS-Website/commit/72e19904804066da0ab55552c0df6f532c38122b

**Comment by stragu** [comment]
Fab, thanks! :slightly_smiling_face:
