### ISSUE TITLE
Add anchor to donwload page

### ISSUE THREAD

**Issue by yjacolin** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#93]
Is it possible to add anchor to the download pag, for example: http://qgis.org/en/site/forusers/download.html#windows

**Comment by rduivenvoorde** [comment]
there actually already is: try: http://qgis.org/en/site/forusers/download.html#android

BUT the screen scrolls up a little too much AND the accordeon does not open for that item.

The download page could use some care: also see #85 and #59

**Comment by yjacolin** [comment]
ok, so I would change the description to "when using anchor in url open the accordeon which has the correct anchor name + when clicking on one of the accordeon item, change url to add anchor to it".

Because we can't find the anchor by ourself.

**Comment by rduivenvoorde** [comment]
I think no nessecary leave it as is. 

And if you hover over the accordeon titles, I see the anchors in my footer of my browser?

**Comment by eshon** [comment]
Anchors have been added so that they are referenced first.  User's OS is referenced second if no anchor hash tag is present.

the BSD anchor is #bsd and not #unix.
