### ISSUE TITLE
plugin: profile tool crashes qgis

### ISSUE THREAD

**Issue by drewbingrun** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#932]

**Comment by rduivenvoorde** [comment]
Hi, this is the issue tracker of the QGIS website. 

Please create an issue on the issue tracker of the profile tool plugin(? which one are you talking about?), providing more info then what you provide here:
- show info about OS, what you were doing, kind of data etc etc

Closing this one here.
