### ISSUE TITLE
Download Package Error

### ISSUE THREAD

**Issue by eugeniousone** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#935]
When I download a package it downloads the file with 0bits and indicates a download error.  This is occurring on both mac os installations.  I am able to download the alternative versions but not the standalone versions.  

<img width="371" alt="Screen Shot 2021-08-30 at 10 26 39 AM" src="https://user-images.githubusercontent.com/41980421/131379720-b7d78f44-03ee-478e-8d7c-43c0c1dbe0c2.png">

**Comment by jef-n** [comment]
https://qgis.org/downloads/macos/qgis-macos-ltr.dmg works fine here.

**Comment by eugeniousone** [comment]
Very Interesting, if I try to open the file I get this error/warning.

<img width="398" alt="Screen Shot 2021-08-30 at 11 43 18 AM" src="https://user-images.githubusercontent.com/41980421/131388860-cf158842-1284-4393-b35d-70ce6eec452c.png">

On 2 different computers

**Comment by jef-n** [comment]
I meant I can download the file fine and it matches the sha256sum - but I don't have a mac.

**Comment by icetasker** [comment]
I have had this problem since last Thursday. It won't download, but if it does it can't be opened. Also the dmg is 262 KB. Does that sound right?

**Comment by jef-n** [comment]
no, 1235074578 bytes.

**Comment by icetasker** [comment]
I tried with multiple browsers and even using curl in terminal. All 262 KB

**Comment by jef-n** [comment]
odd. 

```
$ curl -O https://qgis.org/downloads/macos/qgis-macos-ltr.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1177M  100 1177M    0     0  7702k      0  0:02:36  0:02:36 --:--:-- 7399k
$ curl -O https://qgis.org/downloads/macos/qgis-macos-ltr.sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   148  100   148    0     0   1309      0 --:--:-- --:--:-- --:--:--  1309
$ ls -l qgis-macos-ltr.dmg
-rw-r--r-- 1 fischer fischer 1235074578 Aug 30 21:05 qgis-macos-ltr.dmg
$ sha256sum qgis-macos-ltr.dmg
b622a2f8ba2148e0fb77ac9029131411182d078758071d78a88ce2db62c479b6  qgis-macos-ltr.dmg
$ cat qgis-macos-ltr.sha256sum
b622a2f8ba2148e0fb77ac9029131411182d078758071d78a88ce2db62c479b6  /Users/admin/qgis/builds/ltr/build/..//qgis_ltr_final-3_16_10_20210813_174425.dmg
```

**Comment by icetasker** [comment]
`% curl -o ./downloads/qgis_pr.dmg -k https://qgis.org/downloads/macos/qgis-macos-ltr.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  256k  100  256k    0     0  1673k      0 --:--:-- --:--:-- --:--:-- 1673k
`

**Comment by icetasker** [comment]
![image](https://user-images.githubusercontent.com/89805684/131395536-4731140f-9bb8-4ab5-bb4a-9b30fffda79e.png)

**Comment by jef-n** [comment]
Do you need `-k`?   Maybe a proxy inbetween?  Did you try `-H 'Cache-Control: no-cache'`

**Comment by icetasker** [comment]
I tried without the -k as well. However, with the -k and with the -H... It appears to be working. The download link on the website is still broken however.

**Comment by jef-n** [comment]
> I tried without the -k as well.

You mean it complains about the site's certificate otherwise?

> However, with the -k and with the -H... It appears to be working. The download link on the website is still broken however.

What do you mean?  Doesn't the link also point at https://qgis.org/downloads/macos/qgis-macos-ltr.dmg?

**Comment by icetasker** [comment]
Using the -k doesn't seem to make a difference.

I don't understand it. When I click that link. it works now, whereas when I clicked the link in the top of this chat, it still downloads the defunct version. When I go to the QGIS download page, the link works now. Well, hopefully things are fine now. I got QGIS working on my machine yesterday anyway.

**Comment by eugeniousone** [comment]
Still not able to sdownload here.

 

curl -o ./downloads/qgis_pr.dmg  https://qgis.org/downloads/macos/qgis-macos-ltr.dmg

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100  256k  100  256k    0     0  3555k      0 --:--:-- --:--:-- --:--:-- 3555k

 

 

Using the -k doesn't seem to make a difference.

I don't understand it. When I click that link. it works now, whereas when I clicked the link in the top of this chat, it still downloads the defunct version. When I go to the QGIS download page, the link works now. Well, hopefully things are fine now. I got QGIS working on my machine yesterday anyway.

**Comment by jef-n** [comment]
Maybe a local cache or proxy issue  - or maybe cloudflare.  Unfortunately not reproducable for me.

**Comment by icetasker** [comment]
Eugeneious, did you try -H 'Cache-Control: no-cache'

That seemed to make a difference for me.

**Comment by jef-n** [comment]
We use [cloudflare](https://www.cloudflare.com/) to handle traffic.   I guess  someone tried to download the file while it was still uploading and cloudflare cached that incomplete copy (or maybe just on one cloudflare node that handles qgis.org traffic for the region that first request originated from; not exactly sure how cloudflare actually works) .  `-H 'Cache-Control: no-cache'` suggests it to ignore the cached copy and fetch it again from qgis.org.  That should also update the cache and so after that the link works for everyone (from the affected region).
