### ISSUE TITLE
Spatial Database doesn't connect

### ISSUE THREAD

**Issue by aaronmar1994** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#936]
## Description

Trying to connect a spatial database from the intermediate training
**training.c1erymiua9dx.us-east-1.rds.amazonaws.com** but it doesn't connect to host. 

-->
Page URL:
**https://training.datapolitan.com/qgis-training/Intermediate_GIS/#173**

**Comment by DelazJ** [comment]
@aaronmar1994 This training material is not provided by the QGIS project and has no relation with us. I'm afraid we can't help. You'd need to report to the authors directly.
