### ISSUE TITLE
Current & past sustaining members not showing on site

### ISSUE THREAD

**Issue by johnwbryant** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#940]
## Description
The current & past sustaining members are not listed on the website. It looks like the feed is broken:

![image](https://user-images.githubusercontent.com/1100600/137826728-35dc16a0-6bea-498e-a778-7393409baae4.png)

Same issue occurs on both Firefox and Chrome on Ubuntu.

Page URL: https://www.qgis.org/en/site/about/sustaining_members.html

**Comment by rduivenvoorde** [comment]
Ah, Thanks for noting!

It appears our 'curl' which pulls the feeds for changelog.qgis.org does not have the right certs anymore...

Temporarily fixed by skipping cert check with option -k
