### ISSUE TITLE
Blog link to planet.qgis.org on website redirects to the wrong page

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#946]
## Description

The "Blogs" item in the page https://planet.qgis.org/en/site/about/index.html is linked to http://planet.qgis.org/ which is incorrectly redirected to https://qgis.org/it/site/ instead of https://plugins.qgis.org/planet/

See the previously reported same issue https://github.com/qgis/QGIS-Website/issues/819 fixed by @rduivenvoorde 

If the redirect cannot be changed, the link of the "Blogs" item should be changed to https://plugins.qgis.org/planet/ or https://blog.qgis.org/

Page URL:
https://planet.qgis.org/en/site/about/index.html

**Comment by rduivenvoorde** [comment]
Mmm, not sure what to do here. It used to point to:
https://plugins.qgis.org/planet/
which was a blog aggregator in the plugins.qgis.org app.

We do have now one official QGIS blog too (blog.qgis.org), but the earlier idea was to have a page to all planet blogs about QGIS...

I'll update the toc in the toc in the index.rst of about part: https://github.com/qgis/QGIS-Website/blob/master/source/site/about/index.rst

**Comment by rduivenvoorde** [comment]
Let's see what tomorrow's build brings...

**Comment by agiudiceandrea** [comment]
@rduivenvoorde, what about the redirection?

**Comment by rduivenvoorde** [comment]
Don't know, we had several 'apps' before: planet and plugins, they all are now into one Django app at plugins.qgis.org

Maybe remove the planet.qgis.org sub domeain from our dns? @timlinux any opinion in this?

**Comment by agiudiceandrea** [comment]
Fixed with https://github.com/qgis/QGIS-Website/commit/e0dd6c78580ab8a2af5c9a14285bd8a6869afe7f
