### ISSUE TITLE
Ubuntu Installation instructions wont work for Linux Mint.

### ISSUE THREAD

**Issue by barryrowlingson** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#947]
## Description

The installation instructions https://qgis.org/en/site/forusers/alldownloads.html don't include Linux Mint, and anyone exactly following the "Debian/Ubuntu" instructions will get a failure. 

The instructions say 

```
sudo add-apt-repository "deb https://qgis.org/ubuntu $(lsb_release -c -s) main"
```

which on a Mint system puts the Mint codename into the repository line ("uma"). What is needed here is the *ubuntu* codename ("focal").

```
$ echo deb https://qgis.org/ubuntu $(lsb_release -c -s) main
deb https://qgis.org/ubuntu uma main
```

I'm not sure of an absolutely reliable way of getting the Ubuntu codename but possibly sourcing `/etc/os-release` will set `$UBUNTU_CODENAME` on both a Mint "uma" system and a vanilla Ubuntu "focal" system. The alternative is adding a note to the page saying something like "Linux Mint users - find your Ubuntu version codename and put it here". Or maybe `uma` can be linked to `focal` on the server?

Adding the repository with "focal" instead of "uma" (and then doing the usual update/install stuff) results in a working QGIS 3.22 :)

Page URL:  https://qgis.org/en/site/forusers/alldownloads.html

**Comment by rduivenvoorde** [comment]
@jef-n is it feasible to add uma to the server list? 

@barryrowlingson would that work? Could you test it if so?

Another option would change the note: 

Note: “lsb_release -c -s” in those lines will return your distro name:

To

Note: “lsb_release -c -s” in those lines will return your distro name:
If on Mint you can use 'focal' (or result of <find right command> instead of “lsb_release -c -s” because that returns the distro name and you need the Ubuntu repo name.

(or something in line with that...)

Would be nice to be able to change the Header to Debian/Ubuntu/Mint then :-)

**Comment by barryrowlingson** [comment]
Note on Mint "focal" is only correct for "Mint Uma" at the moment. I don't really know Mint's codename change process but it might change more often than the underlying Ubuntu codename. Other Mint versions might map to other Ubuntu versions but I guess there's limited support for other Ubuntus in the qgis repo anyway...

Am happy to test changes - I have a Mint VM set up I can play with.

**Comment by jef-n** [comment]
> @jef-n is it feasible to add uma to the server list?

done.  Not sure whether it sticks - can't seem to get anything right these days.

**Comment by rduivenvoorde** [comment]
Cool Thanks! @barryrowlingson it's yours now ;-)

**Comment by barryrowlingson** [comment]
I'm getting a warning which I think is apt finding a mention of "focal" in the InRelease file instead of expected "uma":

```
Get:8 https://qgis.org/ubuntu uma InRelease [2,731 B]                          
Get:10 https://qgis.org/ubuntu uma/main amd64 Packages [23.9 kB]   
Fetched 241 kB in 1s (304 kB/s)  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Conflicting distribution: https://qgis.org/ubuntu uma InRelease (expected uma but got focal)
N: Skipping acquisition of configured file 'main/binary-i386/Packages', as repository 'https://qgis.org/ubuntu uma InRelease' doesn't support architecture 'i386'
```
Is that fixable server-side? Also, I don't understand the "N:" message but its amd64 so not applicable.

My additional repostories file is now:
```
deb https://qgis.org/ubuntu uma main
```

**Comment by agiudiceandrea** [comment]
Please see also this thread https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg46920.html

This should work for both Ubuntu and Mint (at least for recent versions):

```sudo add-apt-repository "deb https://qgis.org/ubuntu $(. /etc/os-release; echo "$UBUNTU_CODENAME") main"```

instead of
```sudo add-apt-repository "deb https://qgis.org/ubuntu `lsb_release -c -s` main"```

**Comment by agiudiceandrea** [comment]
@barryrowlingson
> I don't really know Mint's codename change process but it might change more often than the underlying Ubuntu codename

https://linuxmint.com/download_all.php
https://en.wikipedia.org/wiki/Linux_Mint

**Comment by rduivenvoorde** [comment]
Ok, then (I think) is is better to remove the 'uma' symbolic link from the repo (also because it is apparently failing anyway @jef-n ?).

And if @barryrowlingson is able to confirm the use of the "$UBUNTU_CODENAME" I think we should just spend one or two lines of text to it it in the documentation:
- header like: 'Debian/Ubuntu/Mint' or 'Debian/Ubuntu and derivatives'
- add the text
```
# note: for Linux Mint use:
sudo add-apt-repository "deb https://qgis.org/ubuntu $(. /etc/os-release; echo "$UBUNTU_CODENAME") main"
```
below the debian/ubuntu line ?

**Comment by barryrowlingson** [comment]
That works for Mint. The repo line is then:
```
deb https://qgis.org/ubuntu focal main
```

It should also work for plain Ubuntu - at least with my focal I have that set in /etc/os-release as well.
 
Barry

**Comment by agiudiceandrea** [comment]
Why was this closed?

**Comment by jef-n** [comment]
> Why was this closed?

Um, I thought this was fixed - but mint is neither debian/ubuntu.

**Comment by rduivenvoorde** [comment]
Sorry, I had a converstation with barry, but apperently failed to DO it..
Will do this evening...

**Comment by agiudiceandrea** [comment]
> Sorry, I had a converstation with barry, but apperently failed to DO it.. Will do this evening...

Hi @rduivenvoorde, is the addition planned?

**Comment by agiudiceandrea** [comment]
Just in case... I would remember to update the gpg key which usually expires at August the 9th.

**Comment by nicogodet** [comment]
This issue can be closed now.
