### ISSUE TITLE
Missing QGIS 3.22 docs in QGIS Documentation page

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#948]
## Description

The QGIS 3.22 docs are missing in QGIS Documentation page.

Page URL: https://www.qgis.org/en/docs/index.html

**Comment by rduivenvoorde** [comment]
Yep, I'm aware of it, but because 3.22 is not really stable yet AND the strings are not yet uploaded to Transifex (@DelazJ ?), I thought to wait a little.

But if @anitagraser maybe is willing to create the 3.22 image, I'm ok to add it (and remove 3.10?)

**Comment by agiudiceandrea** [comment]
OK, so the docs for 3.22 will be available when QGIS 3.22 will became LTR... It makes sense.

**Comment by anitagraser** [comment]
@rduivenvoorde here's the 3.22 image: https://drive.google.com/file/d/1S19Ed6fIVR9DH_gdlP_qSrc8xgW04KL9/view?usp=sharing

This image is created using Gimp and the following project file: https://drive.google.com/file/d/0Bwc-5JFVTnfIa0U1M3RFSDhzT2s/view?usp=sharing&resourcekey=0-C9t7Hk_vsJweUiYo8RAhdg

1. Duplicate the text layer and update text to reflect the desired version
2. Use "text to path" on the new text layer
3. Use "path to selection" to create a selection reflecting the version text
4. Create a new layer with white fill
5. Delete the selected areas from the white fill to create the version text-shaped mask image

**Comment by rduivenvoorde** [comment]
@anitagraser Thanks! Sorry for asking, I will try again next time. If I'm right I tried before but then did not have the right font on my Linux machine or so.

**Comment by anitagraser** [comment]
No worries, just putting the steps here if anyone wants to reproduce / do something similar.

**Comment by agiudiceandrea** [comment]
QGIS 3.22 is LTR now.
Anyway it seems the Web version of the docs is only available in English and the PDF version in English of the User Guide / Manual is not valid / broken: see https://docs.qgis.org/3.22/pdf/en/ and https://docs.qgis.org/3.22/pdf/en/QGIS-testing-DesktopUserGuide-en.pdf
https://github.com/qgis/QGIS-Documentation/issues/7379

**Comment by rduivenvoorde** [comment]
@agiudiceandrea mmm, the pdf build I will look into, that's a real issue.

Today I'm going to look  with Hans to move the serving of the www and docs sites to fresh servers.
When that is finished/working I'm going (probably next week) to go with @DelazJ dive into the redirection jungle of apache to setup a /3.22 route, make current testing 3.22 and create a new testing build. 
So please stay tuned :-)
