### ISSUE TITLE
Stop longtime query

### ISSUE THREAD

**Issue by shaninandrew** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#950]
Please, add window for processing query in "Attributes table" (Advanced filter) to able stop this process.

**Comment by DelazJ** [comment]
Hi @shaninandrew,
This repository is for issues encountered when browsing the https://qgis.org website. For issues or requests related to the software itself, please go to https://github.com/qgis/QGIS/issues.
Closing.
