### ISSUE TITLE
I can't run a geopackage

### ISSUE THREAD

**Issue by laurasanttoss** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#957]
I'm having problems with QGIS and I can't solve it at all, when I created a geopackage I had some problems and it deletes, since then I can't create any geopackage anymore, it's like the one I deleted was still there. I've uninstalled and installed the program countless times and it doesn't work. I was only able to perform the first part of the practical activity, this second I am not doing due to this problem. What do I do?

**Comment by rduivenvoorde** [comment]
This is the issue tracker for the website, sorry.

But did you tell QGIS where to save it, it looks like you only gave a name (without browsing to a directory), in that case you save the geopackage probably in your qgis install dir...?
