### ISSUE TITLE
Crashed during simple digitization work. It happened on periodic bases

### ISSUE THREAD

**Issue by Sheigt** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#959]

**Comment by Sheigt** [comment]
Crash ID: cbbdf4dc1d1c76df53148e01cc03c42d5832a57c


Stack Trace


QgsGeometryValidator::checkRingIntersections :
QgsGeometryValidator::validatePolygon :
QgsGeometryValidator::run :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

I am just doing digitization wprk and it is happening rapidly from couple of days.

**Comment by DelazJ** [comment]
@Sheigt This is the issue report tracker for the QGIS website, not the application. That one is at https://github.com/qgis/QGIS/issues. Try to run QGIS without any third-party plugin, in a new profile, and if crash still happens, report there with more details (as much possible, to help devs reproduce it).
Closing.
