### ISSUE TITLE
Text Annotation in 3.22 dissappears when any edits are made

### ISSUE THREAD

**Issue by cssander** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#962]
I'm trying to use the new annotation features in 3.22.  When I add a text annotation it initially shows up as you would expect, but when I try to edit anything (like the "text" or the font size) it disappears.  If I can find the exact location, I can still select and delete it, but when you can see it it is almost impossible to find and select it.

**Comment by DelazJ** [comment]
@cssander this is the issue tracker of the QGIS website, not for the software itself. You should report at https://github.com/qgis/QGIS.
Thanks for understanding. Closing.
