### ISSUE TITLE
Feature request: SVG marker, one-sided arrow

### ISSUE THREAD

**Issue by dhasterok** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#963]
There is a half arrow available in the SVG markers that allow for adding one sided marker arrows, but it cannot be reflected.  It would be helpful for producing strike-slip fault directions if there was the option of reflecting a symbol in addition to the rotation that currently exists, or adding the reflected SVG marker to the set of arrows.

**Comment by DelazJ** [comment]
Hi @dhasterok 

This repository is dedicated to [QGIS Website](https://qgis.org) issues. You should report at https://github.com/qgis/QGIS/issues for software issues/ requests. I'm closing.
Thanks.
