### ISSUE TITLE
Raster Conversion is missing in QGIS 3.16

### ISSUE THREAD

**Issue by Emma23sv** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#971]
## Description

I have installed QGIS 3.16 on my windows 11 and unfortunately when I click on "Raster" it doesn't give me the "Conversion" option. I need to polygonise something and I'm even unable to activate processing tool box to search it there! 

The thing is I have the same problems with other versions of QGIS including 3.10 and 3.14!
Can anybody help with that?
<img width="960" alt="2022-02-01 (2)" src="https://user-images.githubusercontent.com/98819676/151970463-f4dba235-30ca-441f-8e12-8b21a214c5aa.png">
<img width="960" alt="2022-02-01" src="https://user-images.githubusercontent.com/98819676/151970466-170c2e0b-51b0-41d6-8664-3bd19de5ee4a.png">

**Comment by DelazJ** [comment]
Turn on Processing in the Plugin manager.
FYI, this is the issue report for QGIS website (https://qgis.org) not the one for the software which is at https://github.com/qgis/QGIS/issues (as indicated in the issue report form)

**Comment by Emma23sv** [comment]
Thank you for your email. It was the biggest help!
Also, thank you for mentioning the correct place to put the issue. I'm a
new comer to this environment

**Comment by Emma23sv** [comment]
Hello,

How can I get help for the following error I receive while working with the
raster calculator in attribute table?

I receive  "syntax error" after putting in the commands in the Expression
part and then I'm unable to click okay.

Thank you,
Shaghayegh
