### ISSUE TITLE
Standalone Version need "admin right" on windows

### ISSUE THREAD

**Issue by penalva34** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#973]
All the versions on the downlaod page "Standalone installers" need admin rights in windows. Is it possible to have a complete standalone version (with all in user space in windows) ?

  Thanks
-->
Page URL:
https://www.qgis.org/en/site/forusers/download.html#

**Comment by jef-n** [comment]
The osgeo4w installer doesn't need admin rights.

**Comment by penalva34** [comment]
Yes, thank you.
You can close this issue.
