### ISSUE TITLE
Windows download links are not working

### ISSUE THREAD

**Issue by diegosps** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#984]
## Description

Both download links for the standalones returns 403 forbidden.

![image](https://user-images.githubusercontent.com/1766388/158823678-4df97c3f-6d62-440e-bba7-f197883b7d4a.png)

Page URL:
https://qgis.org/downloads/QGIS-OSGeo4W-3.24.0-2.msi
https://qgis.org/downloads/QGIS-OSGeo4W-3.22.4-1.msi

**Comment by solzard** [comment]
Similarly, macOS links return `404 Not Found`.

URLs:
[QGIS macOS Installer Version 3.24](https://qgis.org/downloads/macos/qgis-macos-pr.dmg)
[QGIS macOS Installer Version 3.22](https://qgis.org/downloads/macos/qgis-macos-ltr.dmg)

![Screenshot](https://user-images.githubusercontent.com/29563481/158827052-a41264fc-4c28-4af2-a004-fb9e0599658d.jpg)

**Comment by DelazJ** [comment]
We are currently doing some server update work. @rduivenvoorde would this be related to your upgrade?

**Comment by rduivenvoorde** [comment]
Yep, working on it....

**Comment by rduivenvoorde** [comment]
I think it is fixed...

**Comment by DelazJ** [comment]
the macos seems to work but not the msi

**Comment by rduivenvoorde** [comment]
it is now :-)

**Comment by DelazJ** [comment]
I confirm msi is downloading.
The docs however are 10 days old. See footer of https://docs.qgis.org/3.22/en/docs/user_manual/ (no translated versions is available - The url works correctly so probably a matter of docs source updates)

**Comment by DelazJ** [comment]
And https://qgis.org/pyqgis and https://qgis.org/api site are also down

**Comment by rduivenvoorde** [comment]
docs will be rebuild and rsynced this night.
Others... are fine now ...
Closing...

**Comment by DelazJ** [comment]
Thanks @rduivenvoorde
