### ISSUE TITLE
'Http' site shows directory listing instead of the website

### ISSUE THREAD

**Issue by eldorel** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#985]
It looks like the virtualhost config in apache is separate for the https and http versions of the site, and http is pointing to the wrong directory. 

Page URL: http://www.qgis.org/ 

result: 
![image](https://user-images.githubusercontent.com/3990437/159111958-8c6d068e-38df-4d9d-9205-80696fc1b89c.png)

**Comment by jef-n** [comment]
apparently "already" fixed
