### ISSUE TITLE
Error 404 on French site, link "Découvrir les fonctionnalités de QGIS"

### ISSUE THREAD

**Issue by manugr788** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#986]
## Description

Error 404 on the French version web site when clicking the link [Découvrir les fonctionnalités de QGIS](http://docs.qgis.org/latest/fr/docs/user_manual/preamble/features.html)

Page URL: https://www.qgis.org/fr/site/about/index.html

**Comment by DelazJ** [comment]
Actually it's the same for anything non English
@rduivenvoorde For some reason, the docs has reverted again to 6th march, before we release translation.

**Comment by rduivenvoorde** [comment]
@DelazJ I fixed the build, some dirs were owned by root. I also added a docker-world script, seems there is only a cronjob.sh script for 3.16 and 3.22???
Tested by a 'fr' run... later this evening the normal cron run will do all other languages...

**Comment by rduivenvoorde** [comment]
Ok, cronjob was still running cronjob.sh... which only builds english..
Fixed cronjob, should be running now

**Comment by DelazJ** [comment]
Fine now that the 3.22 docs build is stable.
