### ISSUE TITLE
Download link for 3.24.1 broken

### ISSUE THREAD

**Issue by sxwebster** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#987]
## Description

The FTP site is currently missing this file: https://qgis.org/downloads/QGIS-OSGeo4W-3.24.1-1.msi
The installer is linked from the downloads page. 

Page URL:
https://www.qgis.org/en/site/forusers/download.html

**Comment by rduivenvoorde** [comment]
It's working for me, can you seen where it is trying to get it from? 
We are sending people to some different servers

![Screenshot-20220321075659-300x143](https://user-images.githubusercontent.com/731673/159216671-b554b09c-9f90-4a18-9495-b463d72e2123.png)
