### ISSUE TITLE
Website donation link appears to be broken.

### ISSUE THREAD

**Issue by bholtdwyer** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#988]
I clicked the "Donate" link after hitting the download page for the latest stable release (3.22) but there was no response:
![Screen Shot 2022-03-30 at 23 20 08](https://user-images.githubusercontent.com/54458986/160989560-b7eb7bc7-1706-47b5-81b7-cb54c5d5780f.png)

Page URL: https://qgis.org/en/site/getinvolved/donations.html

**Comment by rduivenvoorde** [comment]
Where did you get that url from? Because that is an old URL...

Ah wait, it is still hidden in some javascript....

Thanks for noting!

**Comment by rduivenvoorde** [comment]
https://github.com/qgis/QGIS-Website/commit/f75618b830ba4873c580ae679082e7139d909f6d

Should show up tomorrow after next rebuild of website.

We should also do some redirects in case people have the javascript cached...

Will close later

**Comment by andreasneumann** [comment]
Thank you @rduivenvoorde

**Comment by DelazJ** [comment]
Good to close, @rduivenvoorde ?

**Comment by rduivenvoorde** [comment]
yep...
