### ISSUE TITLE
Debian/ubuntu LTR installers download version 3.10 instead 3.22

### ISSUE THREAD

**Issue by Esteban-CalP** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#989]
## Description

Tried to install with:
https://qgis.org/debian-ltr

Purged and tried a fresh install with:
https://qgis.org/ubuntu-ltr

The result is QGIS  3.10 getting installed
OS used is Linux mint 20.3

Page URL:
https://download.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

**Comment by jef-n** [comment]
which codename are you using?

**Comment by Esteban-CalP** [comment]
sudo add-apt-repository "deb https://qgis.org/debian-ltr $(lsb_release
-c -s) main"
sudo add-apt-repository "deb https://qgis.org/ubuntu-ltr $(lsb_release
-c -s) main"

**Comment by rduivenvoorde** [comment]
I think he means: what is the result of `lsb_release
-c -s`, that gives you a 'code name' for the release of your distro.
(IF we do not have that you can maybe use a comparable code name (the one on which your Mint version is based?)

**Comment by jef-n** [comment]
Fixed in 167cb8bd3abb9d59b8196d4d16647cb40e490992

**Comment by Esteban-CalP** [comment]
Thank you, i've already read the changes you made.
Greetings.

**Comment by jef-n** [comment]
> Thank you, i've already read the changes you made. 

Already?
