### ISSUE TITLE
no link or page « About the QGIS website » or « Contact webmaster team » in QGIS.org pages.

### ISSUE THREAD

**Issue by pboulerie** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#99]
There is no link or page « About the QGIS website » or « Contact webmaster team » in QGIS.org pages.

(Usually, if I want to comment the content of a given website, I like to find more info about it.)

Documentation and Help. Feature request.

PS I originally asked my question in http://hub.qgis.org/issues/8684 and I was told to visit here.

**Comment by rduivenvoorde** [comment]
ok, added an about/contact link in the footer of the website. Linking to http://www.qgis.org/en/site/getinvolved/about.html (to be fleshed out more)
