### ISSUE TITLE
404 Not Found on Previous releases of QGIS Download Page

### ISSUE THREAD

**Issue by MoreAlameda** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#990]
It seems that there are problems with some downloads of old versions, via https://download.qgis.org/downloads/.
For example, when trying to download version 2.18.0 (https://ftp.osuosl.org/pub/osgeo/download/qgis/windows/QGIS-OSGeo4W-2.18.0-1-Setup-x86_64.exe ), I get a 404 Not Found error.

Page URL:  https://ftp.osuosl.org/pub/osgeo/download/qgis/windows/QGIS-OSGeo4W-2.18.0-1-Setup-x86_64.exe 
https://download.qgis.org/downloads/

**Comment by DelazJ** [comment]
I didn't check them all but looks like only the latest release of each version is still available... It can make sense but if it is on purpose, we should probably only list those, and not the whole list.

**Comment by jef-n** [comment]
synced download.osgeo.org (which ftp.osuosl.org will mirror) with download.qgis.org.
