### ISSUE TITLE
Missing  https://qgis.org/downloads/qgis-2021.gpg.key

### ISSUE THREAD

**Issue by BenFGA** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#991]
Good Morning,

I'm trying to install qgis for ubuntu but I find that the qgis-2021.gpg.key is missing from here https://qgis.org/downloads/

Is it possible to reload the missing key?

Thanks

a work around for anyone having issues is to use the key from here:

https://raw.githubusercontent.com/qgis/QGIS-Website/master/qgis-2021.gpg.key 

wget -qO - https://raw.githubusercontent.com/qgis/QGIS-Website/master/qgis-2021.gpg.key | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import
sudo chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg

**Comment by rduivenvoorde** [comment]
Done

**Comment by BenFGA** [comment]
> 

Amazing thank you
