### ISSUE TITLE
404 Not Found for the french user group

### ISSUE THREAD

**Issue by jmonticolo** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#993]
## Description

Current link to change (404 not found) : http://osgeo.asso.fr/content/project/qgis-user-fr/
Good link (@DelazJ for validation) : https://www.osgeo.asso.fr/

(I tested all the others, they works (sometimes with security issues but works)

Page URL : https://qgis.org/en/site/forusers/usergroups.html
Impacted file : https://github.com/qgis/QGIS-Website/blob/master/source/site/forusers/usergroups.rst

**Comment by DelazJ** [comment]
Thanks @jef-n
