### ISSUE TITLE
API C++ docs pages (https://qgis.org/api/ - https://api.qgis.org/api/) not working: 403 Forbidden

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#994]
## Description

The API C++ docs pages are linked in https://www.qgis.org/en/docs/index.html#testing to https://qgis.org/api/ which redirects to https://api.qgis.org/api/.
The https://api.qgis.org/api/ returns:

```
403 Forbidden
Forbidden
You don't have permission to access this resource.

Apache/2.4.53 (Debian) Server at api.qgis.org Port 443
```

Page URL:
https://qgis.org/api/ - https://api.qgis.org/api/

**Comment by rduivenvoorde** [comment]
@jef-n that still runs on qgis2? Something changed?

**Comment by rduivenvoorde** [comment]
I see there has been a Debian update on that machine :-)
It's not that a directory has wrong permissions or so.

So I think this is 'work in progress' of Juergen...

**Comment by agiudiceandrea** [comment]
Anyway it seems https://api.qgis.org/api/3.22/ and https://api.qgis.org/api/3.16/ are working, while https://api.qgis.org/api/ still does not work.

**Comment by jef-n** [comment]
> I see there has been a Debian update on that machine :-) It's not that a directory has wrong permissions or so.

Um, so it's not just the debian/ubuntu builds and downloads.  Well, makes sense, as that api data is take from the packages too.    Revived.   But the outdated website is now gone.   docker is defunct now too (aufs vs. overlay2!?).   What about stripe?

**Comment by rduivenvoorde** [comment]
> . But the outdated website is now gone.

define 'outdate website'. 
The qgis.org website? That is fine: all is on www2 for that
The api site versions? Mmm, are you sure? Did that not end up in some local dir?

That was the reason I did not want to upgrade a running qgis2, afraid I'd end up with non working docker/apache stuff.

Docker: well: /var/lib/docker/aufs/layers is still filled...  But I'm not sure if the aufs back-end is still usable with newer docker?
I think we installed docker at that time via those docker scripts. Nowadays, in Debian I just use: 'apt install docker.io' if I am right...

Stripe is on new machine/www2, so no worries

**Comment by jef-n** [comment]
> define 'outdate website'. The qgis.org website? That is fine: all is on www2 for that The api site versions? Mmm, are you sure? Did that not end up in some local dir?

download.qgis.org was als serving a outdated version (pointing at the previous qgis versions).

> Docker: well: /var/lib/docker/aufs/layers is still filled... But I'm not sure if the aufs back-end is still usable with newer docker? I think we installed docker at that time via those docker scripts. Nowadays, in Debian I just use: 'apt install docker.io' if I am right...

Which needs overlay2 and cannot handle aufs.

**Comment by Gustry** [comment]
There are still links with 404 : https://api.qgis.org/api/classQgsGeometry.html
Is-it expected ?

**Comment by agiudiceandrea** [comment]
It seems the URLs like https://api.qgis.org/api/classQgsGeometry.html (as they were previously and as they are currently also indexed by Google) are now like https://api.qgis.org/api/master/classQgsGeometry.html.

**Comment by Gustry** [comment]
Hum ok, thanks for the tip. It's going to take sometimes to update all links, training materials etc. Would it be possible to have a redirection ?

Side question, is-it possible to have the same keyword for the latest dev version as in https://docs.qgis.org ?

* Latest version of the docs : https://docs.qgis.org/testing/en/docs/user_manual/  `testing`
* Latest version of the API : https://api.qgis.org/api/master/index.html  `master`

Sorry, I'm often confused between `latest`, `master`, `testing`... :) Maybe I should create another ticket for this one ?

**Comment by rduivenvoorde** [comment]
Should https://api.qgis.org/api/ not just be symlinked to either the master (dev) version or the latest stable one (3.22)? So no changes of links in material?

**Comment by jef-n** [comment]
> It seems the URLs like https://api.qgis.org/api/classQgsGeometry.html (as they were previously and as they are currently also indexed by Google) are now like https://api.qgis.org/api/master/classQgsGeometry.html.

Both work now.
