### ISSUE TITLE
Several Ubuntu qgis repositories return a 404 HTTP error

### ISSUE THREAD

**Issue by phasenohr** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#995]
Hello,

Some Ubuntu QGIS repository urls are not working and return a 404 error:
URLs affected:
 - https://ubuntu.qgis.org/ubuntu
 - https://ubuntu.qgis.org/ubuntu-nightly-release

Thanks for looking into it,
Paul

**Comment by jef-n** [comment]
ubuntu symlinks to debian restored
